package client

import (
	"strings"
	"testing"

	"github.com/paulmanoni/nexus/registry"
)

// TestGenerateDTS_TinyManifestSnapshot pins the .d.ts output for a
// representative tiny manifest covering: a named struct in Refs, a
// REST endpoint with typed args + array return, a GraphQL query
// with object args, a WebSocket path with two msgTypes, and a
// custom token store (auth section).
//
// Pure-function test — no fx, no HTTP. Covers every branch in the
// type-expression renderer (primitive, ref, array, object inline,
// optional field) plus the discriminated-map writers.
func TestGenerateDTS_TinyManifestSnapshot(t *testing.T) {
	str := func(p string) *registry.TypeRef { return &registry.TypeRef{Kind: "primitive", Primitive: p} }
	intRef := func() *registry.TypeRef { return &registry.TypeRef{Kind: "primitive", Primitive: "integer"} }
	arrayOf := func(inner *registry.TypeRef) *registry.TypeRef {
		return &registry.TypeRef{Kind: "array", Of: inner}
	}
	ref := func(name string) *registry.TypeRef { return &registry.TypeRef{Kind: "ref", Ref: name} }

	m := Manifest{
		Version:  SchemaVersion,
		BasePath: "/api/v1",
		Services: []ServiceInfo{{Name: "pets"}},
		Refs: map[string]registry.NamedType{
			"Pet": {
				Description: "A pet record",
				Fields: []registry.FieldSchema{
					{Name: "ID", JSONName: "id", Type: *str("string")},
					{Name: "Name", JSONName: "name", Type: *str("string"), Description: "Display name"},
					{Name: "Age", JSONName: "age", Type: *intRef(), Optional: true},
				},
			},
		},
		Endpoints: []EndpointInfo{
			{
				Service: "pets", Transport: "rest", Method: "GET", Path: "/pets",
				Args: &registry.TypeRef{Kind: "object", Object: &registry.NamedType{
					Fields: []registry.FieldSchema{
						{Name: "Limit", JSONName: "limit", Type: *intRef(), Optional: true},
					},
				}},
				Return: arrayOf(ref("Pet")),
			},
			{
				Service: "pets", Transport: "rest", Method: "POST", Path: "/pets",
				Args: ref("Pet"), Return: ref("Pet"),
			},
			{
				Service: "pets", Transport: "graphql", Method: "query", Name: "listPets",
				Path:   "/graphql",
				Args:   nil,
				Return: arrayOf(ref("Pet")),
			},
			{
				Service: "pets", Transport: "graphql", Method: "mutation", Name: "createPet",
				Path: "/graphql",
				Args: ref("Pet"), Return: ref("Pet"),
			},
		},
		WS: []WSPathInfo{
			{
				Path: "/events", Service: "events",
				Messages: []WSMessage{
					{Type: "chat.send", Args: &registry.TypeRef{Kind: "object", Object: &registry.NamedType{
						Fields: []registry.FieldSchema{
							{Name: "Text", JSONName: "text", Type: *str("string")},
						},
					}}},
					{Type: "chat.typing"},
				},
			},
		},
	}

	out := GenerateDTS(m)

	// Header
	wantSubstrings := []string{
		"Auto-generated by the nexus client SDK",
		"Schema version: " + SchemaVersion,
		"Base path:      /api/v1",
		// Pet interface: id required, name has JSDoc, age optional
		"export interface Pet {",
		"id: string",
		"/** Display name */",
		"name: string",
		"age?: number",
		// REST map keyed by 'METHOD PATH'
		"export interface RestEndpoints {",
		"'GET /pets': { args: { limit?: number }; return: Pet[] }",
		"'POST /pets': { args: Pet; return: Pet }",
		// GraphQL ops
		"export interface GraphqlOps {",
		"listPets: { kind: 'query'; args: {}; return: Pet[] }",
		"createPet: { kind: 'mutation'; args: Pet; return: Pet }",
		// WS messages
		"export interface WSMessages {",
		"'/events': {",
		"'chat.send': { text: string }",
		"'chat.typing': {}",
		// Top-level runtime exports — paired with client.js by file
		// proximity (no `declare module` wrapper).
		"export class NexusClient",
		"export class NexusError",
		"export interface CrudHandle",
		"export class WSHandle<P extends keyof WSMessages>",
		"export interface AuthNamespace",
		"export type ExtractRestMethod<K>",
	}

	for _, s := range wantSubstrings {
		if !strings.Contains(out, s) {
			t.Errorf("client.d.ts missing substring %q\n--- output ---\n%s\n--- end ---", s, out)
		}
	}
	// Must NOT wrap exports in a declare-module block — that
	// stops TS from auto-pairing the .d.ts with its .js sibling on
	// disk. Regression marker for the v0.28.6 fix.
	if strings.Contains(out, "declare module '/__nexus/client/client.js'") {
		t.Error("client.d.ts should not wrap exports in a `declare module` block — they must be top-level so TS auto-pairs with client.js")
	}

	// Vue half — separate file, top-level composable exports,
	// imports shared types from the './client.js' sibling.
	vueOut := GenerateVueDTS(m)
	wantVueSubstrings := []string{
		"export function useNexus",
		"export function useQuery<K extends keyof RestEndpoints>",
		"export function useMutation<K extends keyof RestEndpoints>",
		"export function useGqlQuery<K extends keyof GraphqlOps>",
		"export function useGqlMutation<K extends keyof GraphqlOps>",
		"export function useCrud<T = unknown>",
		"export function useWS<P extends keyof WSMessages>",
		"export function useAuth(opts?: UseAuthOptions): UseAuthHandle",
		"export interface QueryHandle<T>",
		"export interface CrudListHandle<T>",
		"export interface UseAuthHandle",
		"import type { Ref, ComputedRef } from 'vue'",
		"from './client.js'",
	}
	for _, s := range wantVueSubstrings {
		if !strings.Contains(vueOut, s) {
			t.Errorf("vue.d.ts missing substring %q\n--- output ---\n%s\n--- end ---", s, vueOut)
		}
	}
	if strings.Contains(vueOut, "declare module '/__nexus/client/vue.js'") {
		t.Error("vue.d.ts should not wrap exports in a `declare module` block")
	}

	// Stability — same inputs, byte-equal outputs (snapshot tests
	// downstream rely on this).
	if GenerateClientDTS(m) != out {
		t.Error("GenerateClientDTS not deterministic — same input produced different output")
	}
	if GenerateVueDTS(m) != vueOut {
		t.Error("GenerateVueDTS not deterministic — same input produced different output")
	}
}

// TestGenerateDTS_EmptyManifest verifies the generator works on a
// freshly-booted app with no endpoints registered yet — should
// emit just the header + module declaration without crashing on
// nil maps / empty slices.
func TestGenerateDTS_EmptyManifest(t *testing.T) {
	out := GenerateClientDTS(Manifest{Version: SchemaVersion})
	if !strings.Contains(out, "Schema version: "+SchemaVersion) {
		t.Error("header missing")
	}
	// Runtime classes must always be present — they're the type
	// pair for client.js regardless of whether endpoints are
	// registered yet.
	if !strings.Contains(out, "export class NexusClient") {
		t.Error("NexusClient export missing on empty manifest")
	}
	// Empty discriminated maps ARE emitted (as `{}` shells) so the
	// runtime surface's `K extends keyof RestEndpoints` constraint
	// resolves to `never` rather than triggering a "cannot find
	// name" error in the consuming app's TS.
	if !strings.Contains(out, "export interface RestEndpoints {}") {
		t.Error("expected empty RestEndpoints shell for typeof-keyof use sites")
	}
}

// TestTsType_AllKinds covers the type-expression renderer's branches
// in isolation. Catches regressions in any single arm without
// regenerating a whole manifest.
func TestTsType_AllKinds(t *testing.T) {
	cases := []struct {
		name string
		in   *registry.TypeRef
		want string
	}{
		{"nil", nil, "unknown"},
		{"string", &registry.TypeRef{Kind: "primitive", Primitive: "string"}, "string"},
		{"integer", &registry.TypeRef{Kind: "primitive", Primitive: "integer"}, "number"},
		{"number", &registry.TypeRef{Kind: "primitive", Primitive: "number"}, "number"},
		{"boolean", &registry.TypeRef{Kind: "primitive", Primitive: "boolean"}, "boolean"},
		{"any", &registry.TypeRef{Kind: "any"}, "unknown"},
		{"ref", &registry.TypeRef{Kind: "ref", Ref: "User"}, "User"},
		{"array of string", &registry.TypeRef{Kind: "array", Of: &registry.TypeRef{Kind: "primitive", Primitive: "string"}}, "string[]"},
		{"map string-int", &registry.TypeRef{Kind: "map",
			KeyOf: &registry.TypeRef{Kind: "primitive", Primitive: "string"},
			Of:    &registry.TypeRef{Kind: "primitive", Primitive: "integer"}},
			"Record<string, number>"},
		{"map int-Pet", &registry.TypeRef{Kind: "map",
			KeyOf: &registry.TypeRef{Kind: "primitive", Primitive: "integer"},
			Of:    &registry.TypeRef{Kind: "ref", Ref: "Pet"}},
			"Record<number, Pet>"},
		{"empty object", &registry.TypeRef{Kind: "object", Object: &registry.NamedType{}}, "{}"},
		{"object inline",
			&registry.TypeRef{Kind: "object", Object: &registry.NamedType{Fields: []registry.FieldSchema{
				{Name: "X", JSONName: "x", Type: registry.TypeRef{Kind: "primitive", Primitive: "string"}},
				{Name: "Y", JSONName: "y", Type: registry.TypeRef{Kind: "primitive", Primitive: "integer"}, Optional: true},
			}}},
			"{ x: string; y?: number }"},
		{"optional propagates",
			&registry.TypeRef{Kind: "ref", Ref: "Pet", Optional: true},
			"Pet | undefined"},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			got := tsType(c.in)
			if got != c.want {
				t.Errorf("tsType: got %q, want %q", got, c.want)
			}
		})
	}
}
