package client

import (
	"fmt"
	"sort"
	"strings"

	"github.com/paulmanoni/nexus/registry"
)

// GenerateDTS projects a SDK manifest into a TypeScript declaration
// (.d.ts) file. The output is a single string the embed handler
// serves verbatim from /__nexus/client/client.d.ts; consumers point
// their tsconfig at it (or paste it into their repo if they prefer
// a checked-in artifact via `nexus client --out`).
//
// Output shape:
//
//   1. // header comment carrying the schema version + a "do not edit"
//      banner.
//   2. One `export interface <Name>` per entry in manifest.Refs —
//      the deduped pool of named struct types referenced by endpoints.
//   3. `export interface RestEndpoints` discriminated map keyed by
//      "<METHOD> <PATH>" → { args, return }. Apps pin call sites by
//      using these keys in TS overloads.
//   4. `export interface GraphqlOps` keyed by op name.
//   5. `export interface WSMessages` keyed by WS path; each path is
//      a map of msgType → args.
//   6. `declare module '/__nexus/client/client.js'` — typed runtime
//      surface (NexusClient, NexusError, CrudHandle, WSHandle,
//      AuthNamespace, token stores).
//   7. `declare module '/__nexus/client/vue.js'` — typed Vue 3
//      composables (useNexus, useQuery, useMutation, useCrud,
//      useWS, useAuth, …) so TS apps importing from the SDK's
//      vue.js URL get completion + signature checks.
//
// Pure function: same manifest in, same string out. Caller
// (Handler.build) memoizes via sync.Once.
func GenerateDTS(m Manifest) string {
	var b strings.Builder
	writeHeader(&b, m)
	writeRefInterfaces(&b, m.Refs)
	writeRestEndpoints(&b, m)
	writeGraphqlOps(&b, m)
	writeWSMessages(&b, m)
	writeClientOverloads(&b)
	writeVueOverloads(&b)
	return b.String()
}

// -- writers -------------------------------------------------------

func writeHeader(b *strings.Builder, m Manifest) {
	b.WriteString("// Auto-generated by the nexus client SDK — do not edit.\n")
	b.WriteString("// Edits will be overwritten on next request to /__nexus/client/client.d.ts.\n")
	fmt.Fprintf(b, "// Schema version: %s\n", m.Version)
	if m.BasePath != "" {
		fmt.Fprintf(b, "// Base path:      %s\n", m.BasePath)
	}
	b.WriteString("\n")
}

// writeRefInterfaces emits one `export interface <Name>` block per
// named type, sorted alphabetically so byte-equal manifests produce
// byte-equal TS output (snapshot tests rely on it).
func writeRefInterfaces(b *strings.Builder, refs map[string]registry.NamedType) {
	if len(refs) == 0 {
		return
	}
	b.WriteString("// ── Type definitions ─────────────────────────────────────────\n\n")
	names := make([]string, 0, len(refs))
	for n := range refs {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, n := range names {
		nt := refs[n]
		fmt.Fprintf(b, "export interface %s {\n", tsIdent(n))
		writeFields(b, nt.Fields, "  ")
		b.WriteString("}\n\n")
	}
}

func writeFields(b *strings.Builder, fields []registry.FieldSchema, indent string) {
	for _, f := range fields {
		name := f.JSONName
		if name == "" {
			name = f.Name
		}
		opt := ""
		if f.Optional {
			opt = "?"
		}
		if f.Description != "" {
			fmt.Fprintf(b, "%s/** %s */\n", indent, escapeComment(f.Description))
		}
		fmt.Fprintf(b, "%s%s%s: %s\n", indent, tsKey(name), opt, tsType(&f.Type))
	}
}

func writeRestEndpoints(b *strings.Builder, m Manifest) {
	rest := filterByTransport(m.Endpoints, "rest")
	if len(rest) == 0 {
		return
	}
	b.WriteString("// ── REST endpoints (keyed by '<METHOD> <PATH>') ──────────────\n\n")
	b.WriteString("export interface RestEndpoints {\n")
	for _, e := range rest {
		key := fmt.Sprintf("%s %s", e.Method, e.Path)
		fmt.Fprintf(b, "  %s: { args: %s; return: %s }\n",
			tsLiteral(key), tsTypeOrEmpty(e.Args, "{}"), tsTypeOrEmpty(e.Return, "void"))
	}
	b.WriteString("}\n\n")
}

func writeGraphqlOps(b *strings.Builder, m Manifest) {
	gql := filterByTransport(m.Endpoints, "graphql")
	if len(gql) == 0 {
		return
	}
	b.WriteString("// ── GraphQL ops (keyed by op name) ───────────────────────────\n\n")
	b.WriteString("export interface GraphqlOps {\n")
	for _, e := range gql {
		fmt.Fprintf(b, "  %s: { kind: %s; args: %s; return: %s }\n",
			tsKey(e.Name), tsLiteral(e.Method),
			tsTypeOrEmpty(e.Args, "{}"), tsTypeOrEmpty(e.Return, "unknown"))
	}
	b.WriteString("}\n\n")
}

// writeWSMessages emits a per-path map of msgType → args. Reads
// Manifest.WS rather than walking Endpoints because the manifest
// already grouped them; the discriminated nested map is the most
// useful TS shape for `ws.on(type, handler)` IDE completion.
func writeWSMessages(b *strings.Builder, m Manifest) {
	if len(m.WS) == 0 {
		return
	}
	b.WriteString("// ── WebSocket message types (keyed by path → type) ──────────\n\n")
	b.WriteString("export interface WSMessages {\n")
	for _, ws := range m.WS {
		fmt.Fprintf(b, "  %s: {\n", tsLiteral(ws.Path))
		for _, msg := range ws.Messages {
			fmt.Fprintf(b, "    %s: %s\n", tsLiteral(msg.Type), tsTypeOrEmpty(msg.Args, "{}"))
		}
		b.WriteString("  }\n")
	}
	b.WriteString("}\n\n")
}

// writeClientOverloads re-exports the runtime classes with typed
// overloads pulling from the discriminated maps above. The runtime
// itself stays untyped JS — these declarations augment its public
// surface for tooling.
//
// We declare the module under the served URL so apps importing
// `import { NexusClient } from '/__nexus/client/client.js'` see the
// types automatically; bundler users can re-route to the same .d.ts
// via tsconfig paths.
func writeClientOverloads(b *strings.Builder) {
	b.WriteString(`// ── Typed runtime surface ────────────────────────────────────

declare module '/__nexus/client/client.js' {
  /** Throws on non-2xx responses; status + payload + endpoint surfaced. */
  export class NexusError extends Error {
    status?: number
    code?: string
    payload?: unknown
    endpoint?: string
  }

  export interface TokenStore {
    get(): string | null
    set(token: string | null): void
    clear(): void
  }

  export function memoryTokenStore(): TokenStore
  export function localStorageTokenStore(key?: string): TokenStore

  export interface NexusClientOptions {
    origin?: string
    manifestPath?: string
    fetch?: typeof globalThis.fetch
    tokenStore?: TokenStore
  }

  export class NexusClient {
    constructor(opts?: NexusClientOptions)
    readonly auth: AuthNamespace

    /** Fetch + cache the manifest. */
    ready(): Promise<unknown>
    /** Force a manifest re-fetch (rare; use in dev hot-reload). */
    reload(): Promise<unknown>

    /** Typed REST call — completion picks key from RestEndpoints. */
    rest<K extends keyof RestEndpoints>(
      method: ExtractRestMethod<K>,
      path:   ExtractRestPath<K>,
      args?:  RestEndpoints[K]['args'],
      opts?:  { headers?: Record<string, string>; signal?: AbortSignal },
    ): Promise<RestEndpoints[K]['return']>
    /** Untyped escape hatch. */
    rest(method: string, path: string, args?: object, opts?: object): Promise<unknown>

    /** Typed GraphQL query. */
    query<K extends keyof GraphqlOps>(
      name: K, vars?: GraphqlOps[K]['args'],
    ): Promise<GraphqlOps[K]['return']>
    /** Typed GraphQL mutation. */
    mutate<K extends keyof GraphqlOps>(
      name: K, vars?: GraphqlOps[K]['args'],
    ): Promise<GraphqlOps[K]['return']>

    /** CRUD handle for AsCRUD-registered entities. */
    crud(name: string): CrudHandle

    /** WebSocket handle — typed by path via WSMessages. */
    ws<P extends keyof WSMessages>(path: P): WSHandle<P>
  }

  export interface CrudHandle {
    list(args?: object): Promise<unknown[]>
    get(id: string | number): Promise<unknown>
    create(body: object): Promise<unknown>
    update(id: string | number, body: object): Promise<unknown>
    delete(id: string | number): Promise<void>
  }

  export class WSHandle<P extends keyof WSMessages> {
    /** Register a per-message-type handler. */
    on<T extends keyof WSMessages[P]>(
      type: T, handler: (data: WSMessages[P][T], envelope: WSEnvelope) => void,
    ): this
    /** Wildcard handler — fires for every message regardless of type. */
    on(type: '*', handler: (data: unknown, envelope: WSEnvelope) => void): this
    /** Lifecycle hooks. */
    on(type: '@close' | '@error', handler: (e?: unknown) => void): this

    send<T extends keyof WSMessages[P]>(type: T, data: WSMessages[P][T]): this
    connect(): Promise<this>
    close(): void
    readonly socket: WebSocket | null
  }

  export interface WSEnvelope {
    type: string
    data: unknown
    timestamp?: number
  }

  export interface AuthNamespace {
    readonly token: string | null
    setToken(t: string): void
    clearToken(): void
    /** POSTs to the manifest's auth.loginPath; auto-stashes returned token. */
    login(creds: object): Promise<unknown>
    /** POSTs to auth.logoutPath (if declared); always clears local token. */
    logout(): Promise<void>
    /** GETs auth.mePath. */
    me(): Promise<unknown>
  }

  export default NexusClient
}

// Helpers — extract the METHOD and PATH halves of a 'METHOD PATH' literal.
type ExtractRestMethod<K> = K extends ` + "`${infer M} ${string}`" + ` ? M : never
type ExtractRestPath<K>   = K extends ` + "`${string} ${infer P}`" + ` ? P : never
`)
}

// writeVueOverloads emits the typed module declaration for the
// composables runtime served at /__nexus/client/vue.js. Pulls the
// reactive primitives from 'vue' (host-provided) and the SDK types
// from the sibling client.js module. Same trick that powers the
// rest()/query()/ws() overloads in client.js — the discriminated
// maps (RestEndpoints, GraphqlOps, WSMessages) drive completion +
// signature checks on every composable's returned refs.
func writeVueOverloads(b *strings.Builder) {
	b.WriteString(`// ── Typed Vue composables surface ────────────────────────────

declare module '/__nexus/client/vue.js' {
  import type { Ref, ComputedRef } from 'vue'
  import {
    NexusClient,
    NexusClientOptions,
    NexusError,
    CrudHandle,
    WSHandle,
    AuthNamespace,
    TokenStore,
  } from '/__nexus/client/client.js'

  // Shared opts every composable accepts: pass an explicit client
  // when an app wants to drive a non-default backend without
  // touching the page-shared singleton.
  export interface UseOptions {
    client?: NexusClient
  }

  // ──────── Singleton client ────────

  /** Get or lazy-construct the page-shared NexusClient. */
  export function useNexus(opts?: NexusClientOptions): NexusClient
  /** Replace the shared client — for tests / SSR harnesses. */
  export function setNexus(client: NexusClient): void

  // ──────── REST: useQuery / useMutation ────────

  /**
   * Reactive REST query handle. data/error/loading mutate as the
   * call resolves; refresh() forces a new fetch with current args;
   * abort() cancels the in-flight request.
   */
  export interface QueryHandle<T> {
    data: Ref<T | null>
    error: Ref<NexusError | null>
    loading: Ref<boolean>
    refresh(): Promise<void>
    abort(): void
  }

  export interface UseQueryOptions extends UseOptions {
    /** Request headers per call. */
    headers?: Record<string, string>
    /**
     * When false, suppresses the deep-watch on args. Caller drives
     * via refresh() manually. Default true.
     */
    watch?: boolean
  }

  /** Args supplied as a plain value, a ref, or a getter. */
  export type ArgsSource<A> = A | Ref<A> | (() => A)

  /** Typed REST query — picks args + return from RestEndpoints. */
  export function useQuery<K extends keyof RestEndpoints>(
    method: ExtractRestMethod<K>,
    path: ExtractRestPath<K>,
    args?: ArgsSource<RestEndpoints[K]['args']>,
    opts?: UseQueryOptions,
  ): QueryHandle<RestEndpoints[K]['return']>

  /** Untyped escape hatch for arbitrary REST calls. */
  export function useQuery<T = unknown>(
    method: string, path: string,
    args?: ArgsSource<object>,
    opts?: UseQueryOptions,
  ): QueryHandle<T>

  /**
   * Manual-fire mutation handle. Does not run on mount; mutate()
   * fires the call, populates data, and resolves with the response.
   */
  export interface MutationHandle<A, T> {
    mutate(args?: A, opts?: { headers?: Record<string, string>; signal?: AbortSignal }): Promise<T>
    data: Ref<T | null>
    error: Ref<NexusError | null>
    loading: Ref<boolean>
  }

  export function useMutation<K extends keyof RestEndpoints>(
    method: ExtractRestMethod<K>,
    path: ExtractRestPath<K>,
    opts?: UseOptions,
  ): MutationHandle<RestEndpoints[K]['args'], RestEndpoints[K]['return']>

  export function useMutation<A = object, T = unknown>(
    method: string, path: string, opts?: UseOptions,
  ): MutationHandle<A, T>

  // ──────── GraphQL: useGqlQuery / useGqlMutation ────────

  export function useGqlQuery<K extends keyof GraphqlOps>(
    name: K,
    args?: ArgsSource<GraphqlOps[K]['args']>,
    opts?: UseQueryOptions,
  ): QueryHandle<GraphqlOps[K]['return']>

  export function useGqlMutation<K extends keyof GraphqlOps>(
    name: K, opts?: UseOptions,
  ): MutationHandle<GraphqlOps[K]['args'], GraphqlOps[K]['return']>

  // ──────── CRUD ────────

  /**
   * Reactive CRUD list with optimistic updates and optional WS-
   * backed live sync. T is the entity shape; supply via the
   * generic param when the entity name doesn't match a Refs key.
   */
  export interface CrudListHandle<T> {
    items: Ref<T[]>
    loading: Ref<boolean>
    error: Ref<NexusError | null>
    refresh(args?: object): Promise<void>
    create(body: Partial<T>): Promise<T>
    update(id: string | number, body: Partial<T>): Promise<T>
    remove(id: string | number): Promise<void>
    ws: WSHandle<keyof WSMessages> | null
  }

  export interface UseCrudOptions extends UseOptions {
    /** WS path to subscribe for <name>.created / .updated / .deleted events. */
    wsPath?: string
    /** Disable the WS subscription entirely. Default true (subscribe). */
    subscribe?: boolean
    /** Skip the initial list() on mount; caller drives via refresh(). */
    lazy?: boolean
    /** Field used as the entity identifier. Defaults to 'id'. */
    idField?: string
    /** Args supplied to the initial list() call. */
    initialArgs?: object
  }

  export function useCrud<T = unknown>(
    name: string, opts?: UseCrudOptions,
  ): CrudListHandle<T>

  // ──────── WebSocket ────────

  /** Reactive WebSocket handle scoped to one path. */
  export interface UseWSHandle<P extends keyof WSMessages> {
    connected: Ref<boolean>
    handle: WSHandle<P>
    on<T extends keyof WSMessages[P]>(
      type: T, fn: (data: WSMessages[P][T]) => void,
    ): WSHandle<P>
    on(type: '*' | '@close' | '@error', fn: (data: unknown) => void): WSHandle<P>
    send<T extends keyof WSMessages[P]>(type: T, data: WSMessages[P][T]): WSHandle<P>
    connect(): Promise<WSHandle<P>>
    close(): void
  }

  export interface UseWSOptions extends UseOptions {
    /** Connect immediately on mount. Default true. */
    eager?: boolean
  }

  export function useWS<P extends keyof WSMessages>(
    path: P, opts?: UseWSOptions,
  ): UseWSHandle<P>

  // ──────── Auth ────────

  /** Reactive auth state + login/logout/me actions. */
  export interface UseAuthHandle {
    token: Ref<string | null>
    identity: Ref<unknown>
    loading: Ref<boolean>
    error: Ref<NexusError | null>
    isAuthenticated: ComputedRef<boolean>
    login(creds: object): Promise<unknown>
    logout(): Promise<void>
    refresh(): Promise<void>
  }

  export interface UseAuthOptions extends UseOptions {
    /** Bootstrap by calling /me on mount when a token is present. Default true. */
    eager?: boolean
  }

  export function useAuth(opts?: UseAuthOptions): UseAuthHandle

  // Default export — most-common composable, paired with
  //   import useNexus from '/__nexus/client/vue.js'
  export default useNexus
}
`)
}

// -- type expression builders --------------------------------------

// tsType renders a TypeRef as a TypeScript type expression.
//   primitive:string|number|integer|boolean → string|number|boolean
//   array                                   → T[]
//   map                                     → Record<K, V>
//   ref                                     → Name (reference to interface)
//   object                                  → { fields }
//   any | unknown                           → unknown
//
// Optionality on a TypeRef is rendered as `T | undefined` so the
// type composes inside larger expressions; field-level optionality
// uses `?:` in writeFields.
func tsType(t *registry.TypeRef) string {
	if t == nil {
		return "unknown"
	}
	core := tsTypeCore(t)
	if t.Optional {
		return core + " | undefined"
	}
	return core
}

func tsTypeCore(t *registry.TypeRef) string {
	switch t.Kind {
	case "primitive":
		switch t.Primitive {
		case "string":
			return "string"
		case "boolean":
			return "boolean"
		case "integer", "number":
			return "number"
		}
		return "unknown"
	case "array":
		return tsType(t.Of) + "[]"
	case "map":
		key := "string"
		if t.KeyOf != nil && t.KeyOf.Kind == "primitive" && t.KeyOf.Primitive == "integer" {
			key = "number"
		}
		return fmt.Sprintf("Record<%s, %s>", key, tsType(t.Of))
	case "ref":
		return tsIdent(t.Ref)
	case "object":
		if t.Object == nil || len(t.Object.Fields) == 0 {
			return "{}"
		}
		var b strings.Builder
		b.WriteString("{ ")
		for i, f := range t.Object.Fields {
			if i > 0 {
				b.WriteString("; ")
			}
			name := f.JSONName
			if name == "" {
				name = f.Name
			}
			opt := ""
			if f.Optional {
				opt = "?"
			}
			fmt.Fprintf(&b, "%s%s: %s", tsKey(name), opt, tsType(&f.Type))
		}
		b.WriteString(" }")
		return b.String()
	case "any", "":
		return "unknown"
	default:
		return "unknown"
	}
}

// tsTypeOrEmpty renders a TypeRef or a fallback when the ref is nil.
// Used for endpoint args/return where nil means "no schema declared".
func tsTypeOrEmpty(t *registry.TypeRef, fallback string) string {
	if t == nil {
		return fallback
	}
	return tsType(t)
}

// tsIdent sanitizes a Go type name into a TS identifier. Most names
// pass through unchanged; this exists so future additions
// (generics, unicode-named types) have one place to grow.
func tsIdent(name string) string {
	if name == "" {
		return "unknown"
	}
	return name
}

// tsKey returns the field-name form for an object literal — quoted
// when the name contains characters that need escaping (dots,
// hyphens, etc., common in JSON tags), bare otherwise.
func tsKey(name string) string {
	if isPlainIdent(name) {
		return name
	}
	return tsLiteral(name)
}

func isPlainIdent(s string) bool {
	if s == "" {
		return false
	}
	for i, r := range s {
		if i == 0 {
			if !(r == '_' || r == '$' || (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z')) {
				return false
			}
			continue
		}
		if !(r == '_' || r == '$' || (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9')) {
			return false
		}
	}
	return true
}

func tsLiteral(s string) string {
	// Single-quoted string literal. Escape backslashes + single quotes.
	var b strings.Builder
	b.WriteByte('\'')
	for _, r := range s {
		if r == '\\' || r == '\'' {
			b.WriteByte('\\')
		}
		b.WriteRune(r)
	}
	b.WriteByte('\'')
	return b.String()
}

func escapeComment(s string) string {
	// Block-comment safety — kill any embedded "*/" so the comment
	// doesn't accidentally close.
	return strings.ReplaceAll(s, "*/", "* /")
}

func filterByTransport(eps []EndpointInfo, transport string) []EndpointInfo {
	out := make([]EndpointInfo, 0, len(eps))
	for _, e := range eps {
		if e.Transport == transport {
			out = append(out, e)
		}
	}
	return out
}
