package client

import (
	"fmt"
	"sort"
	"strings"

	"github.com/paulmanoni/nexus/registry"
)

// GenerateNexusTS produces a "barrel" wiring file that:
//   1. constructs the page-shared NexusClient via setNexus()
//   2. re-exports composables so the rest of the app imports from
//      one place (`import { useNexus, useAuth, … } from '@/sdk/nexus'`)
//   3. re-exports manifest-derived type names so callers can
//      annotate with `import type` from the same place.
//
// Designed as a STARTER scaffold — Dump uses WriteIfMissing so a
// second boot doesn't clobber edits the developer has made (custom
// origin logic, extra exports, conditional token stores, …).
//
// Reads Vite-style env vars at runtime:
//
//	VITE_NEXUS_API   — origin override; empty = same-origin (dev proxy)
//	VITE_NEXUS_TOKEN — localStorage key for the bearer token; default 'access_token'
//
// The same shape works for non-Vite bundlers too — `import.meta.env`
// is a no-op object and the defaults take over.
func GenerateNexusTS(m Manifest) string {
	var b strings.Builder
	b.WriteString(`// Auto-generated by the nexus client SDK as a one-time scaffold.
// Edit freely — re-running the dump will NOT overwrite this file
// once it exists. Delete it to regenerate from scratch.
//
// Wires the page-shared NexusClient and re-exports composables so
// the rest of the app imports from one place:
//
//   import { useNexus, useGqlQuery, useAuth } from '@/sdk/nexus'
//
// Build-time config (Vite env vars; harmless under other bundlers):
//   VITE_NEXUS_API   — origin override (e.g. "https://api.example.com").
//                       Empty = same-origin so the dev proxy works.
//   VITE_NEXUS_TOKEN — localStorage key for the bearer token.
//                       Default: "access_token".

import { NexusClient, localStorageTokenStore, memoryTokenStore } from './client.js'
import {
  useNexus,
  setNexus,
  useAuth,
  useQuery,
  useMutation,
  useGqlQuery,
  useGqlMutation,
  useCrud,
  useWS,
} from './vue.js'

const env = (import.meta as any).env ?? {}

const origin: string = String(env.VITE_NEXUS_API ?? '').replace(/\/+$/, '')
const tokenKey: string = String(env.VITE_NEXUS_TOKEN ?? 'access_token')

// Construct the page-shared NexusClient once. useNexus() ignores
// opts after the first call, so this seeds the singleton for every
// composable invocation across the app.
setNexus(
  new NexusClient({
    origin: origin || undefined,
    tokenStore:
      typeof window === 'undefined'
        ? memoryTokenStore()
        : localStorageTokenStore(tokenKey),
  }),
)

export {
  useNexus,
  useAuth,
  useQuery,
  useMutation,
  useGqlQuery,
  useGqlMutation,
  useCrud,
  useWS,
}

// Re-export the discriminated maps so apps can write
//   const r: GraphqlOps['listPets']['return'] = …
export type {
  RestEndpoints,
  GraphqlOps,
  WSMessages,
} from './client.js'
`)

	// Re-export named types from the manifest's Refs pool. Sorted
	// for byte-stable output. Only names that are valid TS
	// identifiers — sanitizeTypeName already enforced that, but the
	// nexus.ts file is also human-edited so quoting around bad
	// names would be ugly; skip them defensively.
	if len(m.Refs) > 0 {
		names := refExportNames(m.Refs)
		if len(names) > 0 {
			b.WriteString("\n// Manifest-derived named types — annotate locals via `import type`.\n")
			b.WriteString("export type {\n")
			for _, n := range names {
				fmt.Fprintf(&b, "  %s,\n", n)
			}
			b.WriteString("} from './client.js'\n")
		}
	}
	return b.String()
}

// refExportNames returns the set of ref keys that are safe to write
// as bare TS identifiers (no quoting / no special chars).
// sanitizeTypeName guarantees this for every entry it emits, but
// the function double-checks so a hand-edited Manifest.Refs (custom
// projection in Config.Client.Manifest) can't crash the generator.
func refExportNames(refs map[string]registry.NamedType) []string {
	out := make([]string, 0, len(refs))
	for k := range refs {
		if isPlainIdent(k) {
			out = append(out, k)
		}
	}
	sort.Strings(out)
	return out
}
