package client

import (
	"strings"
	"testing"

	"github.com/paulmanoni/nexus/registry"
)

// TestGenerateNexusTS_Shape pins the wiring scaffold's output: it
// imports from sibling './client.js' and './vue.js' (no @ts-ignore
// because types auto-pair on disk), constructs the singleton via
// setNexus, re-exports the eight composables, the discriminated
// maps, and every named ref from the manifest.
func TestGenerateNexusTS_Shape(t *testing.T) {
	m := Manifest{
		Version: SchemaVersion,
		Refs: map[string]registry.NamedType{
			"Pet":     {Fields: []registry.FieldSchema{{Name: "ID", JSONName: "id", Type: registry.TypeRef{Kind: "primitive", Primitive: "string"}}}},
			"User":    {Fields: []registry.FieldSchema{{Name: "ID", JSONName: "id", Type: registry.TypeRef{Kind: "primitive", Primitive: "string"}}}},
			"Permission": {},
		},
	}
	out := GenerateNexusTS(m)

	for _, want := range []string{
		"// Auto-generated by the nexus client SDK as a one-time scaffold.",
		// Sibling-relative imports — no URL paths, no @ts-ignore.
		"from './client.js'",
		"from './vue.js'",
		// Vite env wiring with sane defaults.
		"VITE_NEXUS_API",
		"VITE_NEXUS_TOKEN",
		"localStorageTokenStore(tokenKey)",
		"memoryTokenStore()",
		// Singleton wired via setNexus.
		"setNexus(",
		"new NexusClient({",
		// All eight composables re-exported.
		"useNexus,",
		"useAuth,",
		"useQuery,",
		"useMutation,",
		"useGqlQuery,",
		"useGqlMutation,",
		"useCrud,",
		"useWS,",
		// Discriminated maps re-exported as types.
		"export type {",
		"RestEndpoints,",
		"GraphqlOps,",
		"WSMessages,",
		// Manifest-derived types re-exported, alphabetized.
		"Pet,",
		"Permission,",
		"User,",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("nexus.ts missing %q\n--- output ---\n%s\n--- end ---", want, out)
		}
	}

	// Must NOT use the runtime URL imports — the whole point of
	// v0.28.6 is sibling-relative imports that auto-pair with the
	// dumped .d.ts files.
	if strings.Contains(out, "/__nexus/client/client.js") || strings.Contains(out, "/__nexus/client/vue.js") {
		t.Error("nexus.ts should import via sibling-relative './client.js' / './vue.js', not the runtime URL")
	}
	// @ts-ignore is allowed only on the import.meta.env line —
	// Vite-style env access without forcing every consumer to
	// pull in vite/client types.
	if strings.Count(out, "@ts-ignore") != 1 {
		t.Errorf("nexus.ts should have exactly one @ts-ignore (on import.meta.env), got %d", strings.Count(out, "@ts-ignore"))
	}
	if !strings.Contains(out, "// @ts-ignore — import.meta.env") {
		t.Error("expected @ts-ignore guard immediately above the import.meta.env line")
	}
}

// TestGenerateNexusTS_NoRefs covers the empty-manifest branch — the
// extra `export type` block for manifest names is omitted, the rest
// (composable wiring + discriminated maps) still emits.
func TestGenerateNexusTS_NoRefs(t *testing.T) {
	out := GenerateNexusTS(Manifest{Version: SchemaVersion})
	if !strings.Contains(out, "useNexus,") {
		t.Error("composable re-exports missing on empty manifest")
	}
	if strings.Contains(out, "// Manifest-derived named types") {
		t.Error("ref-export block emitted on empty manifest — should be skipped")
	}
}
