package client

import (
	"fmt"
	"sort"
	"strings"

	"github.com/paulmanoni/nexus/registry"
)

// GenerateNexusTS produces an OPTIONAL barrel file that re-exports
// every composable + the discriminated maps + manifest-derived
// named types from one place. Apps that prefer importing directly
// from './vue.js' can ignore (or delete) this file entirely — the
// page-shared NexusClient now picks up Vite env vars
// (VITE_NEXUS_API, VITE_NEXUS_TOKEN) inside useNexus() itself, so
// no client-construction wiring is needed.
//
// Designed as a STARTER scaffold — Dump uses WriteIfMissing so a
// second boot doesn't clobber edits the developer has made.
//
// Use it when you want a single import path:
//
//	import { useNexus, useGqlQuery, useAuth } from '@/sdk/nexus'
//	import type { Pet, User } from '@/sdk/nexus'
//
// Skip it when bare imports from './vue.js' / './client.js' are
// fine — useNexus() is a singleton either way.
func GenerateNexusTS(m Manifest) string {
	var b strings.Builder
	b.WriteString(`// Auto-generated by the nexus client SDK as a one-time scaffold.
// Edit freely — re-running the dump will NOT overwrite this file
// once it exists. Delete it to regenerate from scratch.
//
// Optional barrel: re-exports every composable + shared types so
// the rest of the app imports from one place. Skipping this file
// and importing from './vue.js' directly is equally fine — the
// useNexus() singleton already reads Vite env vars
// (VITE_NEXUS_API, VITE_NEXUS_TOKEN) on first call.

export {
  useNexus,
  setNexus,
  useAuth,
  useQuery,
  useMutation,
  useGqlQuery,
  useGqlMutation,
  useCrud,
  useWS,
} from './vue.js'

// Re-export the discriminated maps so apps can write
//   const r: GraphqlOps['listPets']['return'] = …
export type {
  RestEndpoints,
  GraphqlOps,
  WSMessages,
} from './client.js'
`)

	// Re-export named types from the manifest's Refs pool. Sorted
	// for byte-stable output. Only names that are valid TS
	// identifiers — sanitizeTypeName already enforced that, but the
	// nexus.ts file is also human-edited so quoting around bad
	// names would be ugly; skip them defensively.
	if len(m.Refs) > 0 {
		names := refExportNames(m.Refs)
		if len(names) > 0 {
			b.WriteString("\n// Manifest-derived named types — annotate locals via `import type`.\n")
			b.WriteString("export type {\n")
			for _, n := range names {
				fmt.Fprintf(&b, "  %s,\n", n)
			}
			b.WriteString("} from './client.js'\n")
		}
	}
	return b.String()
}

// refExportNames returns the set of ref keys that are safe to write
// as bare TS identifiers (no quoting / no special chars).
// sanitizeTypeName guarantees this for every entry it emits, but
// the function double-checks so a hand-edited Manifest.Refs (custom
// projection in Config.Client.Manifest) can't crash the generator.
func refExportNames(refs map[string]registry.NamedType) []string {
	out := make([]string, 0, len(refs))
	for k := range refs {
		if isPlainIdent(k) {
			out = append(out, k)
		}
	}
	sort.Strings(out)
	return out
}
