// Code generated by 'nexus gen clients'; DO NOT EDIT.
// To regenerate, run: nexus gen clients ./...

package checkout

import (
	"context"

	"github.com/paulmanoni/nexus"
)

// CheckoutClient is the typed client surface for the "checkout" module.
// One method per AsRest / AsQuery / AsMutation handler in that
// module's declaration. The implementation is selected at construction
// time based on the running binary's deployment.
type CheckoutClient interface {
	Submit(ctx context.Context, args SubmitArgs) (*Receipt, error)
}

// NewCheckoutClient returns the appropriate implementation for the
// running binary:
//   - In-process LocalInvoker when this binary owns the "checkout-svc"
//     deployment, OR when no deployment is set (monolith mode).
//   - HTTP RemoteCaller reading CHECKOUT_SVC_URL otherwise. The local
//     binary's version is threaded in so RemoteCaller can detect
//     peer-version skew on the first call (single warning line, no
//     fail-fast).
func NewCheckoutClient(app *nexus.App) CheckoutClient {
	if dep := app.Deployment(); dep == "" || dep == "checkout-svc" {
		return &checkoutClientLocal{call: nexus.NewLocalInvoker(app)}
	}
	return &checkoutClientRemote{call: nexus.NewRemoteCallerFromEnv(
		"CHECKOUT_SVC_URL",
		nexus.WithLocalVersion(app.Version()),
	)}
}

type checkoutClientLocal struct{ call nexus.ClientCallable }

func (c *checkoutClientLocal) Submit(ctx context.Context, args SubmitArgs) (*Receipt, error) {
	var out *Receipt
	err := c.call.Invoke(ctx, "POST", "/checkout", args, &out)
	return out, err

}

type checkoutClientRemote struct{ call nexus.ClientCallable }

func (c *checkoutClientRemote) Submit(ctx context.Context, args SubmitArgs) (*Receipt, error) {
	var out *Receipt
	err := c.call.Invoke(ctx, "POST", "/checkout", args, &out)
	return out, err

}
