package migration

import (
	"fmt"
	"go/format"
	"strconv"
	"strings"

	"github.com/paulmanoni/nexus/orm/internal/schema"
)

// Source is the Go file registering mg in package pkg, as nexus
// makemigrations writes it: notes[i] ("" for none) is a comment above
// operation i.
func Source(pkg string, mg Migration, notes []string) ([]byte, error) {
	var b strings.Builder
	b.WriteString("// Generated by nexus makemigrations. It is the app's own: review it, and edit it as you need.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	usesContext := false
	for _, op := range mg.Operations {
		if _, ok := op.(RunGo); ok {
			usesContext = true
		}
	}
	if usesContext {
		b.WriteString("import (\n\t\"context\"\n\n\tm \"github.com/paulmanoni/nexus/orm/migration\"\n)\n\n")
	} else {
		b.WriteString("import m \"github.com/paulmanoni/nexus/orm/migration\"\n\n")
	}
	b.WriteString("func init() {\n\tm.Register(m.Migration{\n")
	fmt.Fprintf(&b, "Name: %s,\n", strconv.Quote(mg.Name))
	if mg.DB != "" {
		fmt.Fprintf(&b, "DB: %s,\n", strconv.Quote(mg.DB))
	}
	if len(mg.Dependencies) > 0 {
		deps := make([]string, len(mg.Dependencies))
		for i, d := range mg.Dependencies {
			deps[i] = strconv.Quote(d)
		}
		fmt.Fprintf(&b, "Dependencies: []string{%s},\n", strings.Join(deps, ", "))
	}
	b.WriteString("Operations: []m.Operation{\n")
	for i, op := range mg.Operations {
		if i < len(notes) && notes[i] != "" {
			fmt.Fprintf(&b, "// NOTE: %s\n", notes[i])
		}
		b.WriteString(op.source() + ",\n")
	}
	b.WriteString("},\n})\n}\n")
	out, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("migration: writing %s: %w\n%s", mg.Name, err, b.String())
	}
	return out, nil
}

// str is s as a Go string literal: raw when it reads better so.
func str(s string) string {
	if strings.ContainsAny(s, "\"\n") && !strings.ContainsAny(s, "`\r") {
		return "`" + s + "`"
	}
	return strconv.Quote(s)
}

func strs(ss []string) string {
	q := make([]string, len(ss))
	for i, s := range ss {
		q[i] = str(s)
	}
	return strings.Join(q, ", ")
}

func (f Field) source() string {
	c := f.c
	var s string
	switch {
	case c.Auto && c.Kind == schema.Int:
		s = "m.BigAuto()"
	case c.Auto:
		s = "m.Auto()"
	case c.Vector != 0:
		s = "m.Vector(" + strconv.Itoa(max(c.Vector, 0)) + ")"
	case c.TSVector:
		s = "m.TSVector()"
	case c.Kind == schema.String && c.Size > 0:
		s = "m.Varchar(" + strconv.Itoa(c.Size) + ")"
	default:
		s = "m." + map[schema.Kind]string{
			schema.Bool: "Bool", schema.Int: "BigInt", schema.Int32: "Int", schema.Float: "Float", schema.Float32: "Float32",
			schema.String: "Text", schema.Time: "Time", schema.Bytes: "Bytes", schema.Custom: "Custom",
		}[c.Kind] + "()"
	}
	if c.PK && !c.Auto {
		s += ".PK()"
	}
	if c.Nullable {
		s += ".Null()"
	}
	if c.Unique {
		s += ".Unique()"
	}
	if c.Index {
		s += ".Index()"
	}
	if c.Type != "" {
		s += ".Type(" + str(c.Type) + ")"
	}
	if c.Default != "" {
		s += ".DefaultSQL(" + str(c.Default) + ")"
	}
	if !c.Generated.Zero() {
		s += ".Generated(" + dialects(c.Generated) + ")"
	}
	if c.FK != nil {
		s += ".FK(" + str(c.FK.Table) + ", " + str(c.FK.Ref) + ")"
		if c.FK.OnDelete != "" {
			s += ".OnDelete(" + map[string]string{Cascade: "m.Cascade", SetNull: "m.SetNull", Restrict: "m.Restrict"}[c.FK.OnDelete] + ")"
		}
	}
	return s
}

func dialects(x Dialects) string {
	var parts []string
	for _, p := range []struct{ name, sql string }{{"Postgres", x.Postgres}, {"MySQL", x.MySQL}, {"SQLite", x.SQLite}} {
		if p.sql != "" {
			parts = append(parts, p.name+": "+str(p.sql))
		}
	}
	return "m.Dialects{" + strings.Join(parts, ", ") + "}"
}

func index(ix Index) string {
	return "m.Index{Name: " + str(ix.Name) + ", SQL: " + dialects(ix.SQL) + "}"
}

func constraint(k Constraint) string {
	if k.Check != "" {
		return "m.Check(" + str(k.Name) + ", " + str(k.Check) + ")"
	}
	return "m.Unique(" + str(k.Name) + ", " + strs(k.Columns) + ")"
}

func (o CreateModel) source() string {
	var b strings.Builder
	b.WriteString("m.CreateModel{\nTable: " + str(o.Table) + ",\nFields: []m.NamedField{\n")
	for _, f := range o.Fields {
		b.WriteString("m.F(" + str(f.Name) + ", " + f.Field.source() + "),\n")
	}
	b.WriteString("},\n")
	if len(o.Constraints) > 0 {
		b.WriteString("Constraints: []m.Constraint{\n")
		for _, k := range o.Constraints {
			b.WriteString(constraint(k) + ",\n")
		}
		b.WriteString("},\n")
	}
	if len(o.Indexes) > 0 {
		b.WriteString("Indexes: []m.Index{\n")
		for _, ix := range o.Indexes {
			b.WriteString(strings.TrimPrefix(index(ix), "m.Index") + ",\n")
		}
		b.WriteString("},\n")
	}
	return b.String() + "}"
}

func (o DeleteModel) source() string { return "m.DeleteModel{Table: " + str(o.Table) + "}" }
func (o RenameModel) source() string {
	return "m.RenameModel{Old: " + str(o.Old) + ", New: " + str(o.New) + "}"
}
func (o AddField) source() string {
	return "m.AddField{Table: " + str(o.Table) + ", Name: " + str(o.Name) + ", Field: " + o.Field.source() + "}"
}
func (o RemoveField) source() string {
	return "m.RemoveField{Table: " + str(o.Table) + ", Name: " + str(o.Name) + "}"
}
func (o AlterField) source() string {
	return "m.AlterField{Table: " + str(o.Table) + ", Name: " + str(o.Name) + ", Field: " + o.Field.source() + "}"
}
func (o RenameField) source() string {
	return "m.RenameField{Table: " + str(o.Table) + ", Old: " + str(o.Old) + ", New: " + str(o.New) + "}"
}
func (o AddIndex) source() string {
	return "m.AddIndex{Table: " + str(o.Table) + ", Index: " + index(o.Index) + "}"
}
func (o RemoveIndex) source() string {
	return "m.RemoveIndex{Table: " + str(o.Table) + ", Name: " + str(o.Name) + "}"
}
func (o AddConstraint) source() string {
	return "m.AddConstraint{Table: " + str(o.Table) + ", Constraint: " + constraint(o.Constraint) + "}"
}
func (o RemoveConstraint) source() string {
	return "m.RemoveConstraint{Table: " + str(o.Table) + ", Name: " + str(o.Name) + "}"
}
func (o CreateExtension) source() string { return "m.CreateExtension{Name: " + str(o.Name) + "}" }

func (o RunSQL) source() string {
	s := "m.RunSQL{SQL: " + str(o.SQL)
	if o.ReverseSQL == Noop {
		s += ", ReverseSQL: m.Noop"
	} else if o.ReverseSQL != "" {
		s += ", ReverseSQL: " + str(o.ReverseSQL)
	}
	if o.Dialect != "" {
		s += ", Dialect: " + str(o.Dialect)
	}
	return s + "}"
}

// source is a RunGo to fill in: its functions can't be written back.
func (o RunGo) source() string {
	return `m.RunGo{
Forward: func(ctx context.Context, tx m.Tx) error {
return nil
},
Backward: func(ctx context.Context, tx m.Tx) error {
return nil
},
}`
}
