package main

import (
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// execCommand is package-level so tests can stub it out; same
// pattern the rest of cmd/nexus uses.
var execCommand = exec.Command

// generateEmbedFile writes a temporary embed_gen.go next to
// the main package source so `go build` picks up //go:embed
// directives for templates + islands without the user having
// to write them by hand.
//
// Strategy: scan mainDir for the conventional asset directories
// (templates/, islands/, plus anything custom passed via
// extraDirs). For each one that exists AND has at least one
// file, include it in the //go:embed line. If no asset
// directories exist, write nothing — the call is a no-op for
// pure-API apps that don't use live/template.
//
// Returns the path to the generated file (or "" if nothing was
// written) so the caller can defer its removal regardless of
// whether the subsequent build succeeded.
//
// The generated file's package declaration matches mainPkg
// (typically "main" for a binary entry point). It registers
// the embed.FS with template.SetDefaultFS in an init() so the
// embed is active before main() (and before any nexus.Run()
// call) runs.
func generateEmbedFile(mainDir, mainPkg string, extraDirs []string, stderr io.Writer) (string, error) {
	dirs := scanEmbedDirs(mainDir, extraDirs)
	if len(dirs) == 0 {
		return "", nil
	}
	path := filepath.Join(mainDir, "embed_gen.go")
	body := renderEmbedGenSource(mainPkg, dirs)
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		return "", fmt.Errorf("write %s: %w", path, err)
	}
	fmt.Fprintf(stderr, "nexus build: embedded %s into %s\n", strings.Join(dirs, " + "), filepath.Base(path))
	return path, nil
}

// scanEmbedDirs returns the directory names (relative to
// mainDir) that exist AND contain at least one regular file.
// Empty directories are skipped because //go:embed on an empty
// dir is a compile error. extraDirs lets callers add custom
// names beyond the conventional islands/.
//
// templates/ used to be conventional too, but the .nlt engine
// removal dropped its embed-time wiring. Scaffolded projects
// now own their own go:embed directives in main.go.
func scanEmbedDirs(mainDir string, extraDirs []string) []string {
	candidates := append([]string{filepath.Join(frontendDirName(), "dist")}, extraDirs...)
	seen := map[string]bool{}
	out := make([]string, 0, len(candidates))
	for _, d := range candidates {
		if seen[d] {
			continue
		}
		seen[d] = true
		full := filepath.Join(mainDir, d)
		info, err := os.Stat(full)
		if err != nil || !info.IsDir() {
			continue
		}
		if !dirHasFiles(full) {
			continue
		}
		out = append(out, d)
	}
	return out
}

// dirHasFiles is a shallow check — //go:embed walks recursively
// at build time, so we just need to confirm the directory isn't
// completely empty. An empty templates/ would compile but waste
// the embed entry; one with files is the case we care about.
func dirHasFiles(dir string) bool {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return false
	}
	for _, e := range entries {
		if !e.IsDir() {
			return true
		}
		// One level of recursion handles templates/foo/Bar.nlt.
		sub := filepath.Join(dir, e.Name())
		subEntries, err := os.ReadDir(sub)
		if err != nil {
			continue
		}
		if len(subEntries) > 0 {
			return true
		}
	}
	return false
}

// renderEmbedGenSource produces the generated Go file body.
// Marked "Code generated" per the Go convention so `go vet`,
// gofmt, and IDEs treat it as machine-generated (don't lint,
// don't reformat, etc.). The leading underscore on the
// filename (embed_gen.go) makes the file conventionally
// "internal artifact" and is recognized by some tooling.
//
// Note on package: the user's main is usually `package main`
// but build also supports cmd-subpackage layouts. We match
// whatever the caller resolved as the entry-point package.
func renderEmbedGenSource(pkgName string, dirs []string) string {
	var b strings.Builder
	b.WriteString("// Code generated by `nexus build`. DO NOT EDIT.\n")
	b.WriteString("// Auto-removed after the build completes.\n")
	b.WriteString("//\n")
	b.WriteString("// `nexus build` scans the main package for conventional asset\n")
	b.WriteString("// directories (islands/) and writes this file so the\n")
	b.WriteString("// //go:embed directive bakes them into the binary. The\n")
	b.WriteString("// exported nexusEmbeddedAssets var is what the user's\n")
	b.WriteString("// main.go (or ServeFrontend caller) consumes.\n\n")
	b.WriteString("package " + pkgName + "\n\n")
	b.WriteString("import \"embed\"\n\n")
	b.WriteString("//go:embed " + strings.Join(dirs, " ") + "\n")
	b.WriteString("var nexusEmbeddedAssets embed.FS\n\n")
	b.WriteString("// _ keeps the var from being flagged unused when no\n")
	b.WriteString("// downstream code references it directly (scaffolded\n")
	b.WriteString("// projects usually carry their own //go:embed in main.go).\n")
	b.WriteString("var _ = nexusEmbeddedAssets\n")
	return b.String()
}

// removeEmbedFile cleans up the generated file. Run via defer
// so the file disappears whether the build succeeded or failed
// — leaving a stray embed_gen.go in the working tree would
// shadow the user's no-embed dev workflow on the next `go run`.
//
// Silent on success; logs to stderr on failure so the user
// knows to delete it manually.
func removeEmbedFile(path string, stderr io.Writer) {
	if path == "" {
		return
	}
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		fmt.Fprintf(stderr, "nexus build: failed to clean up %s: %v\n", path, err)
	}
}

// simpleBuildOptions is the no-deployment variant of buildOptions.
// Used when a project has no nexus.toml — the user just
// wants the embed-gen pass + plain `go build`.
type simpleBuildOptions struct {
	Output      string
	MainPackage string
	Stdout      io.Writer
	Stderr      io.Writer
}

// runSimpleBuild generates the embed file (templates/, islands/
// if present) and shells to `go build`. No overlay, no shadows,
// no manifest. Most live-template apps live here.
//
// Pipeline order matters:
//
//  1. frontendBuild runs Vite (npm install if needed + npm run build)
//     in web/, producing web/dist. Skipped silently when there's no
//     web/package.json (pure-Go projects).
//  2. generateEmbedFile inspects the now-fresh web/dist and writes
//     embed_gen.go so go:embed picks it up.
//  3. go build absorbs it via the generated embed file → single binary.
func runSimpleBuild(opts simpleBuildOptions) error {
	pkg := opts.MainPackage
	if pkg == "" {
		pkg = "."
	}
	cwd, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("getwd: %w", err)
	}
	mainDir := resolveMainDir(cwd, pkg)

	if err := frontendBuild(mainDir, opts.Stdout, opts.Stderr); err != nil {
		return fmt.Errorf("nexus build: %w", err)
	}

	embedPath, err := generateEmbedFile(mainDir, "main", nil, opts.Stderr)
	if err != nil {
		return fmt.Errorf("nexus build: embed-gen: %w", err)
	}
	defer removeEmbedFile(embedPath, opts.Stderr)

	args := []string{"build"}
	if opts.Output != "" {
		args = append(args, "-o", opts.Output)
	}
	args = append(args, pkg)
	cmd := execCommand("go", args...)
	cmd.Stdout = opts.Stdout
	cmd.Stderr = opts.Stderr
	fmt.Fprintf(opts.Stdout, "go %s\n", strings.Join(args, " "))
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("go build failed: %w", err)
	}
	out := opts.Output
	if out == "" {
		out = filepath.Base(mainDir)
	}
	fmt.Fprintf(opts.Stdout, "built %s\n", out)
	return nil
}

// resolveMainDir converts the user-facing main-package import
// path (e.g. ".", "./cmd/server", "github.com/foo/bar/cmd/x")
// into an absolute directory on disk relative to projectRoot.
// Used by the embed-gen pass to find where to drop
// embed_gen.go.
//
// Relative paths join with projectRoot; absolute import paths
// are best-effort treated as projectRoot's relative
// equivalents (split on the module path is the caller's
// problem in v1 — most apps use "." or "./cmd/x" style).
func resolveMainDir(projectRoot, mainPkg string) string {
	if mainPkg == "" || mainPkg == "." {
		return projectRoot
	}
	if strings.HasPrefix(mainPkg, "./") || strings.HasPrefix(mainPkg, "../") {
		return filepath.Join(projectRoot, mainPkg)
	}
	// Absolute import path: not always resolvable to a path
	// without `go list -m` plumbing. Fall back to projectRoot;
	// the embed file lands at the root, which works for module-
	// rooted main packages and is harmless when wrong (just
	// embeds dirs from the wrong place — caller sees no assets
	// loaded and re-runs with --package=./cmd/foo).
	return projectRoot
}
