package main

import (
	"bytes"
	"fmt"
	"go/format"
	"go/types"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"golang.org/x/tools/go/packages"
)

// writeDeployInitFile generates a Go source file for the active
// deployment's main package whose init() block calls
// nexus.SetDeploymentDefaults(...). Returns the path to the
// generated file (under .nexus/build/<deployment>/) and "" when
// nothing needed generating (manifest defines no port + no peers).
//
// The caller adds the generated file to overlay.json as an "added"
// file mapped to a logical path inside the main package directory.
// go build sees it and includes it in the binary; the user's source
// tree is untouched.
func writeDeployInitFile(deployment string, manifest *DeployManifest, projectRoot, mainPackage, shadowDir string, mods []modInfo) (string, error) {
	spec, ok := manifest.Deployments[deployment]
	if !ok {
		return "", nil
	}

	portByTag := map[string]int{}
	for depName, depSpec := range manifest.Deployments {
		if depSpec.Port == 0 {
			continue
		}
		// The deployment name is the DeployAs tag the codegen'd
		// remote client looks up. Match by name; the convention is
		// 1:1 in microsplit.
		portByTag[depName] = depSpec.Port
	}

	// Skip generating the file when there's nothing to set: no port,
	// no peers. The framework's existing fallbacks (Config / env vars)
	// handle that case fine.
	if spec.Port == 0 && len(manifest.Peers) == 0 {
		return "", nil
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by 'nexus build --deployment %s'; DO NOT EDIT.\n", deployment)
	fmt.Fprintf(&b, "// This file is overlay-added at compile time and is not on disk.\n\n")
	fmt.Fprintln(&b, "package main")
	fmt.Fprintln(&b)
	// Conditionally import only what the generated body actually
	// references. `os` is always needed (fmt_addr / envOr use it).
	// `time` is referenced in the Topology block only when a peer
	// declares a Timeout. `context` is referenced only when a peer
	// declares Auth. Without conditional emission, projects with
	// no peer timeouts hit "imported and not used" build errors.
	fmt.Fprintln(&b, "import (")
	fmt.Fprintln(&b, `	"os"`)
	if anyPeerHasTimeout(manifest) {
		fmt.Fprintln(&b, `	"time"`)
	}
	if anyPeerHasAuth(manifest) {
		fmt.Fprintln(&b, `	"context"`)
	}
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, `	"github.com/paulmanoni/nexus"`)
	fmt.Fprintln(&b, ")")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "// nexusDeployInit wires the manifest-derived defaults into the\n")
	fmt.Fprintf(&b, "// framework before main() runs. The generated init() runs once\n")
	fmt.Fprintf(&b, "// per binary; nexus.Run consults these when Config fields are\n")
	fmt.Fprintf(&b, "// zero.\n")
	// A deployment is a "split unit" iff its manifest owns list is
	// non-empty. Empty owns means monolith (owns every module, no
	// tagging). The previous version of this check looked at
	// source-side DeployAs tags, but auto-inject means source can
	// omit the tag entirely — so consult the manifest, which is the
	// source of truth either way.
	isSplitUnit := len(spec.Owns) > 0

	// Module → deployment tag inference. Each non-monolith deployment
	// (one with a non-empty owns list) means "this binary's split
	// unit owns these modules"; emit a registration so those modules'
	// nexus.Module(...) calls auto-pick up DeployAs(<unit>) without
	// the user having to type it. Skipped when the deployment is
	// the monolith (empty owns), since monoliths don't tag anything.
	moduleTagRegistrations := buildModuleTagRegistrations(manifest)

	// Cross-module dep registrations — every (consumer, peer) pair
	// where the consumer's package has a struct field of type
	// *<peer>.Service. The dashboard reads these as
	// service-level edges between module cards, drawing the
	// "checkout calls users" topology line that's invisible
	// otherwise (handlers don't take peer Services directly;
	// they go through svc.peer).
	crossDepRegistrations := buildCrossModuleDepRegistrations(manifest, mods)

	fmt.Fprintln(&b, "func init() {")
	for _, line := range moduleTagRegistrations {
		fmt.Fprintln(&b, "\t"+line)
	}
	if len(moduleTagRegistrations) > 0 {
		fmt.Fprintln(&b)
	}
	for _, line := range crossDepRegistrations {
		fmt.Fprintln(&b, "\t"+line)
	}
	if len(crossDepRegistrations) > 0 {
		fmt.Fprintln(&b)
	}
	fmt.Fprintln(&b, "\tdefaults := nexus.DeploymentDefaults{")
	if isSplitUnit {
		fmt.Fprintf(&b, "\t\tDeployment: %q,\n", deployment)
	}
	if spec.Port > 0 {
		fmt.Fprintf(&b, "\t\tAddr:       fmt_addr(%q, %d),\n", "PORT", spec.Port)
	}
	if len(spec.Listeners) > 0 {
		listenersExpr, err := manifestListenersExpr(spec.Listeners)
		if err != nil {
			return "", fmt.Errorf("listeners for %q: %w", deployment, err)
		}
		fmt.Fprintln(&b, "\t\tListeners: "+listenersExpr+",")
	}
	if len(manifest.Peers) > 0 {
		fmt.Fprintln(&b, "\t\tTopology: nexus.Topology{")
		fmt.Fprintln(&b, "\t\t\tPeers: map[string]nexus.Peer{")
		peerNames := sortedKeysStr(manifest.Peers)
		for _, peer := range peerNames {
			ps := manifest.Peers[peer]
			fmt.Fprintf(&b, "\t\t\t\t%q: {\n", peer)
			// Always emit URLs as a slice. Single-replica peers
			// (manifest declares one entry, or none + the framework
			// falls back to envOr) get a one-element slice; multi-
			// replica peers get N entries. One emit path, one
			// runtime mental model.
			fmt.Fprintln(&b, "\t\t\t\t\tURLs: []string{")
			if len(ps.URLs) > 0 {
				for _, u := range ps.URLs {
					fmt.Fprintf(&b, "\t\t\t\t\t\t%s,\n", urlEntryExpr(u))
				}
			} else {
				// No urls declared — fall back to the singleton env-
				// var convention dev_split uses (USERS_SVC_URL etc.)
				// with the local port as the default. Keeps current
				// dev workflow working without manifest changes.
				fmt.Fprintf(&b, "\t\t\t\t\t\t%s,\n", peerFallbackURLExpr(peer, portByTag[peer]))
			}
			fmt.Fprintln(&b, "\t\t\t\t\t},")
			if ps.Timeout > 0 {
				fmt.Fprintf(&b, "\t\t\t\t\tTimeout: %d * time.Nanosecond,\n", ps.Timeout.Nanoseconds())
			}
			if ps.MinVersion != "" {
				fmt.Fprintf(&b, "\t\t\t\t\tMinVersion: %q,\n", ps.MinVersion)
			}
			if ps.Retries > 0 {
				fmt.Fprintf(&b, "\t\t\t\t\tRetries: %d,\n", ps.Retries)
			}
			if ps.Auth != nil {
				authExpr, err := peerAuthExpr(ps.Auth)
				if err != nil {
					return "", fmt.Errorf("peer %q auth: %w", peer, err)
				}
				fmt.Fprintf(&b, "\t\t\t\t\tAuth: %s,\n", authExpr)
			}
			fmt.Fprintln(&b, "\t\t\t\t},")
		}
		fmt.Fprintln(&b, "\t\t\t},")
		fmt.Fprintln(&b, "\t\t},")
	}
	fmt.Fprintln(&b, "\t}")
	fmt.Fprintln(&b, "\tnexus.SetDeploymentDefaults(defaults)")
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "// fmt_addr resolves the listen address: env var wins (so")
	fmt.Fprintln(&b, "// containers can override), manifest port is the default.")
	fmt.Fprintln(&b, "func fmt_addr(envVar string, defaultPort int) string {")
	fmt.Fprintln(&b, "\tif v := os.Getenv(envVar); v != \"\" {")
	fmt.Fprintln(&b, "\t\tif v[0] == ':' {")
	fmt.Fprintln(&b, "\t\t\treturn v")
	fmt.Fprintln(&b, "\t\t}")
	fmt.Fprintln(&b, "\t\treturn \":\" + v")
	fmt.Fprintln(&b, "\t}")
	fmt.Fprintln(&b, "\treturn fmt_port(defaultPort)")
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "func fmt_port(p int) string {")
	fmt.Fprintln(&b, "\tb := []byte{':'}")
	fmt.Fprintln(&b, "\tif p == 0 { return \":0\" }")
	fmt.Fprintln(&b, "\tdigits := []byte{}")
	fmt.Fprintln(&b, "\tfor p > 0 { digits = append([]byte{byte('0'+p%10)}, digits...); p /= 10 }")
	fmt.Fprintln(&b, "\treturn string(append(b, digits...))")
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "// envOr returns the env var when set, otherwise the fallback.")
	fmt.Fprintln(&b, "// Used so peer URLs default to local-loopback in dev but can be")
	fmt.Fprintln(&b, "// overridden per-environment without code changes.")
	fmt.Fprintln(&b, "func envOr(key, fallback string) string {")
	fmt.Fprintln(&b, "\tif v := os.Getenv(key); v != \"\" {")
	fmt.Fprintln(&b, "\t\treturn v")
	fmt.Fprintln(&b, "\t}")
	fmt.Fprintln(&b, "\treturn fallback")
	fmt.Fprintln(&b, "}")

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return "", fmt.Errorf("gofmt deploy init: %w (raw output:\n%s)", err, b.String())
	}

	out := filepath.Join(shadowDir, "zz_deploy_gen.go")
	if err := os.WriteFile(out, formatted, 0o644); err != nil {
		return "", fmt.Errorf("write deploy init %s: %w", out, err)
	}
	return out, nil
}

// peerFallbackURLExpr builds the Go expression used as the single
// URLs entry for peers that don't declare an explicit `urls:` block.
// Convention: envOr("<TAG>_URL", "http://localhost:<peer-port>") so
// `nexus dev --split`'s env wiring keeps working out of the box,
// with operators able to override per-environment via the env var.
//
// When peerPort is 0 (manifest didn't pin one), the fallback is just
// os.Getenv("<TAG>_URL") — operators MUST set the env var or the
// runtime will see an empty replica.
func peerFallbackURLExpr(tag string, peerPort int) string {
	envVar := tagToURLEnvVar(tag)
	if peerPort > 0 {
		return fmt.Sprintf("envOr(%q, %q)", envVar, fmt.Sprintf("http://localhost:%d", peerPort))
	}
	return fmt.Sprintf("os.Getenv(%q)", envVar)
}

// tagToURLEnvVar mirrors the convention used by dev_split.go
// ("users-svc" → "USERS_SVC_URL"), so the codegen'd envOr fallback
// reads the same env var dev_split sets per subprocess.
func tagToURLEnvVar(tag string) string {
	out := strings.ToUpper(tag)
	out = strings.ReplaceAll(out, "-", "_")
	return out + "_URL"
}

// manifestListenersExpr renders the listeners map from a deployment
// spec into a Go composite literal. Empty Addr stays empty in the
// emitted struct — the framework's fillListenerAddrs auto-fills
// from cfg.Addr at boot. Unknown scope values fail the build with a
// clear message so YAML typos surface immediately.
func manifestListenersExpr(listeners map[string]ListenerSpec) (string, error) {
	if len(listeners) == 0 {
		return "nil", nil
	}
	names := make([]string, 0, len(listeners))
	for n := range listeners {
		names = append(names, n)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("map[string]nexus.Listener{\n")
	for _, name := range names {
		l := listeners[name]
		scope, err := scopeLiteral(l.Scope)
		if err != nil {
			return "", fmt.Errorf("listener %q: %w", name, err)
		}
		fmt.Fprintf(&b, "\t\t\t%q: {\n", name)
		fmt.Fprintf(&b, "\t\t\t\tScope: %s,\n", scope)
		if l.Addr != "" {
			fmt.Fprintf(&b, "\t\t\t\tAddr: %q,\n", l.Addr)
		}
		fmt.Fprintln(&b, "\t\t\t},")
	}
	b.WriteString("\t\t}")
	return b.String(), nil
}

// scopeLiteral maps the YAML scope string to its Go constant. Returns
// an error for unknown values so the build fails before producing a
// binary that ignores the scope (silent dashboard leak).
func scopeLiteral(scope string) (string, error) {
	switch strings.ToLower(strings.TrimSpace(scope)) {
	case "", "public":
		return "nexus.ScopePublic", nil
	case "admin":
		return "nexus.ScopeAdmin", nil
	case "internal":
		return "nexus.ScopeInternal", nil
	default:
		return "", fmt.Errorf("unknown scope %q (want public, admin, or internal)", scope)
	}
}

// urlEntryExpr builds the Go source for one entry in a Peer.URLs
// slice. Recognized YAML forms:
//
//   - `http://...` literal → quoted string
//   - `${VAR}`             → os.Getenv("VAR")
//   - `${VAR:-fallback}`   → envOr("VAR", "fallback")
//
// The :- shell-style default keeps `nexus dev --split` working with
// a manifest that declares replicas: each entry falls back to the
// dev port when the per-replica env var isn't set, so the multi-
// replica code path runs without operator setup. Production sets
// the env vars per replica and the fallback is unused.
func urlEntryExpr(entry string) string {
	if !strings.HasPrefix(entry, "${") || !strings.HasSuffix(entry, "}") || len(entry) <= 3 {
		return fmt.Sprintf("%q", entry)
	}
	inner := entry[2 : len(entry)-1]
	if i := strings.Index(inner, ":-"); i > 0 {
		varName := inner[:i]
		fallback := inner[i+2:]
		return fmt.Sprintf("envOr(%q, %q)", varName, fallback)
	}
	return fmt.Sprintf("os.Getenv(%q)", inner)
}

// peerAuthExpr emits the Go source for a Peer.Auth closure built
// from the manifest's auth block. Only `bearer` is supported in v1;
// other types fail at build time so the operator finds out at the
// CI gate, not at first request.
//
// The closure body is:
//
//	func(ctx context.Context) (string, error) {
//	    return "Bearer " + os.Getenv("USERS_SVC_TOKEN"), nil
//	}
//
// When the manifest's token is `${VAR}`, we emit os.Getenv("VAR").
// Bare strings emit as a Go string literal — useful for tests, but
// `nexus build` warns operators not to commit real secrets that way.
func peerAuthExpr(spec *AuthSpec) (string, error) {
	switch spec.Type {
	case "bearer":
		tokenExpr, err := tokenExpr(spec.Token)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf(
			"func(ctx context.Context) (string, error) { return \"Bearer \" + %s, nil }",
			tokenExpr,
		), nil
	case "":
		return "", fmt.Errorf("auth.type is required (e.g. \"bearer\")")
	default:
		return "", fmt.Errorf("unsupported auth.type %q (only \"bearer\" is implemented)", spec.Type)
	}
}

// tokenExpr converts a manifest token value into its Go-source
// equivalent: `${VAR}` → `os.Getenv("VAR")`; everything else → a
// quoted string literal. Returns an error when the token is empty
// (a no-token bearer auth makes no sense — fail at build).
func tokenExpr(token string) (string, error) {
	if token == "" {
		return "", fmt.Errorf("auth.token is empty")
	}
	if strings.HasPrefix(token, "${") && strings.HasSuffix(token, "}") {
		varName := strings.TrimSuffix(strings.TrimPrefix(token, "${"), "}")
		if varName == "" {
			return "", fmt.Errorf("auth.token uses empty ${} interpolation")
		}
		return fmt.Sprintf("os.Getenv(%q)", varName), nil
	}
	return fmt.Sprintf("%q", token), nil
}

// anyPeerHasAuth reports whether any peer in the manifest declared
// an auth block. Drives whether the generated zz_deploy_gen.go needs
// to import `context` (Peer.Auth's signature uses context.Context).
func anyPeerHasAuth(manifest *DeployManifest) bool {
	for _, p := range manifest.Peers {
		if p.Auth != nil {
			return true
		}
	}
	return false
}

// anyPeerHasTimeout reports whether any peer declared a non-zero
// timeout. Drives whether the generated zz_deploy_gen.go needs to
// import `time` (Timeout: N * time.Nanosecond is the only reference).
// Without this guard, projects whose peers omit timeouts hit
// "time imported and not used".
func anyPeerHasTimeout(manifest *DeployManifest) bool {
	for _, p := range manifest.Peers {
		if p.Timeout > 0 {
			return true
		}
	}
	return false
}

// buildCrossModuleDepRegistrations scans each owned module's package
// for struct fields whose type is *<peer>.Service where <peer> is
// another known module. Emits one
// nexus.RegisterCrossModuleDep("consumer", "peer") line per detected
// dep so the registry's ServiceDeps slice is populated at app boot
// — the dashboard then draws module-card → module-card edges for
// the cross-module dependency.
//
// The scan looks at every top-level struct in the package, which
// captures the common case (consumer's own *Service struct holding
// peer client fields) plus any auxiliary structs that hold them.
// Fields named "Service" are skipped — that's the embedded
// *nexus.Service field, never a peer reference.
func buildCrossModuleDepRegistrations(manifest *DeployManifest, mods []modInfo) []string {
	if manifest == nil || len(mods) == 0 {
		return nil
	}
	// Reverse lookup: import path → module name. Used to resolve a
	// field type's package path back to the peer module's name.
	moduleByPath := map[string]string{}
	for _, m := range mods {
		if m.PackagePath != "" {
			moduleByPath[m.PackagePath] = m.Name
		}
	}

	type pair struct{ Consumer, Dep string }
	seen := map[pair]bool{}
	var out []string

	for _, m := range mods {
		if m.Pkg == nil || m.Pkg.Types == nil {
			continue
		}
		scope := m.Pkg.Types.Scope()
		for _, name := range scope.Names() {
			obj := scope.Lookup(name)
			if obj == nil {
				continue
			}
			named, ok := obj.Type().(*types.Named)
			if !ok {
				continue
			}
			st, ok := named.Underlying().(*types.Struct)
			if !ok {
				continue
			}
			for i := 0; i < st.NumFields(); i++ {
				f := st.Field(i)
				peer := peerServiceName(f.Type(), moduleByPath)
				if peer == "" || peer == m.Name {
					continue // not a peer reference
				}
				p := pair{Consumer: m.Name, Dep: peer}
				if seen[p] {
					continue
				}
				seen[p] = true
				out = append(out, fmt.Sprintf(`nexus.RegisterCrossModuleDep(%q, %q)`, p.Consumer, p.Dep))
			}
		}
	}
	sort.Strings(out)
	return out
}

// peerServiceName returns the peer module's Name if t is a pointer
// to a Named type whose package path matches a known module, AND
// the Named type is called "Service". Otherwise returns "".
//
// This matches the convention every nexus module uses: the
// cross-module client field is `peer *peer.Service`. Catches the
// 99% case without needing to track every type name in the project.
func peerServiceName(t types.Type, moduleByPath map[string]string) string {
	ptr, ok := t.(*types.Pointer)
	if !ok {
		return ""
	}
	named, ok := ptr.Elem().(*types.Named)
	if !ok {
		return ""
	}
	obj := named.Obj()
	if obj == nil || obj.Name() != "Service" || obj.Pkg() == nil {
		return ""
	}
	return moduleByPath[obj.Pkg().Path()]
}

// buildModuleTagRegistrations turns the manifest's deployments into
// nexus.RegisterModuleDeployment(name, tag) calls, one per (split
// deployment, module) pair. A deployment is a "split unit" iff its
// owns list is non-empty — empty owns means monolith (owns
// everything, no tagging). Returns the lines stably sorted so
// re-runs produce identical output.
//
// When the same module appears in two split deployments (a
// configuration that doesn't make sense — a module can't be local
// in two binaries), the lexically-first deployment wins. The
// duplicate is silently dropped; if this becomes an issue in
// practice, surface it as a build error here.
func buildModuleTagRegistrations(manifest *DeployManifest) []string {
	if manifest == nil {
		return nil
	}
	// First pass: dedupe by module name, deterministic by sorting
	// deployment names. So if two deployments claim the same module,
	// the lexically-earlier deployment's tag is the one that lands.
	deploymentNames := make([]string, 0, len(manifest.Deployments))
	for name := range manifest.Deployments {
		deploymentNames = append(deploymentNames, name)
	}
	sort.Strings(deploymentNames)

	tagByModule := map[string]string{}
	for _, dep := range deploymentNames {
		spec := manifest.Deployments[dep]
		if len(spec.Owns) == 0 {
			continue // monolith — owns everything, tags nothing
		}
		for _, mod := range spec.Owns {
			if _, claimed := tagByModule[mod]; claimed {
				continue
			}
			tagByModule[mod] = dep
		}
	}
	if len(tagByModule) == 0 {
		return nil
	}

	modules := make([]string, 0, len(tagByModule))
	for m := range tagByModule {
		modules = append(modules, m)
	}
	sort.Strings(modules)

	out := make([]string, 0, len(modules))
	for _, m := range modules {
		out = append(out, fmt.Sprintf("nexus.RegisterModuleDeployment(%q, %q)", m, tagByModule[m]))
	}
	return out
}

// mainPackageDir resolves the absolute directory of the named main
// package. Used to compute the logical overlay path for the
// generated zz_deploy_gen.go. The package must already be loadable
// by go/packages.
func mainPackageDir(projectRoot, pkg string) (string, error) {
	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedFiles,
		Dir:  projectRoot,
	}
	pkgs, err := packages.Load(cfg, pkg)
	if err != nil {
		return "", fmt.Errorf("locate main package %q: %w", pkg, err)
	}
	for _, p := range pkgs {
		if len(p.GoFiles) > 0 {
			return filepath.Dir(p.GoFiles[0]), nil
		}
	}
	// Fallback: treat pkg as a relative path.
	abs, err := filepath.Abs(filepath.Join(projectRoot, pkg))
	if err != nil {
		return "", err
	}
	return abs, nil
}

// sortedKeysStr is a typed copy of the sortedKeys helper for
// PeerSpec maps (the original takes map[string]struct{}).
func sortedKeysStr(m map[string]PeerSpec) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
