package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"golang.org/x/tools/go/packages"
)

// writeDeployInitFile generates a Go source file for the active
// deployment's main package whose init() block calls
// nexus.SetDeploymentDefaults(...). Returns the path to the
// generated file (under .nexus/build/<deployment>/) and "" when
// nothing needed generating (manifest defines no port + no peers).
//
// The caller adds the generated file to overlay.json as an "added"
// file mapped to a logical path inside the main package directory.
// go build sees it and includes it in the binary; the user's source
// tree is untouched.
func writeDeployInitFile(deployment string, manifest *DeployManifest, projectRoot, mainPackage, shadowDir string) (string, error) {
	spec, ok := manifest.Deployments[deployment]
	if !ok {
		return "", nil
	}

	portByTag := map[string]int{}
	for depName, depSpec := range manifest.Deployments {
		if depSpec.Port == 0 {
			continue
		}
		// The deployment name is the DeployAs tag the codegen'd
		// remote client looks up. Match by name; the convention is
		// 1:1 in microsplit.
		portByTag[depName] = depSpec.Port
	}

	// Skip generating the file when there's nothing to set: no port,
	// no peers. The framework's existing fallbacks (Config / env vars)
	// handle that case fine.
	if spec.Port == 0 && len(manifest.Peers) == 0 {
		return "", nil
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by 'nexus build --deployment %s'; DO NOT EDIT.\n", deployment)
	fmt.Fprintf(&b, "// This file is overlay-added at compile time and is not on disk.\n\n")
	fmt.Fprintln(&b, "package main")
	fmt.Fprintln(&b)
	// Conditionally import only what the generated body actually
	// references. `os` is always needed (fmt_addr / envOr use it).
	// `time` is referenced in the Topology block only when a peer
	// declares a Timeout. `context` is referenced only when a peer
	// declares Auth. Without conditional emission, projects with
	// no peer timeouts hit "imported and not used" build errors.
	fmt.Fprintln(&b, "import (")
	fmt.Fprintln(&b, `	"os"`)
	if anyPeerHasTimeout(manifest) {
		fmt.Fprintln(&b, `	"time"`)
	}
	if anyPeerHasAuth(manifest) {
		fmt.Fprintln(&b, `	"context"`)
	}
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, `	"github.com/paulmanoni/nexus"`)
	fmt.Fprintln(&b, ")")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "// nexusDeployInit wires the manifest-derived defaults into the\n")
	fmt.Fprintf(&b, "// framework before main() runs. The generated init() runs once\n")
	fmt.Fprintf(&b, "// per binary; nexus.Run consults these when Config fields are\n")
	fmt.Fprintf(&b, "// zero.\n")
	// A deployment is a "split unit" iff its manifest owns list is
	// non-empty. Empty owns means monolith (owns every module, no
	// tagging). The previous version of this check looked at
	// source-side DeployAs tags, but auto-inject means source can
	// omit the tag entirely — so consult the manifest, which is the
	// source of truth either way.
	isSplitUnit := len(spec.Owns) > 0

	// Module → deployment tag inference. Each non-monolith deployment
	// (one with a non-empty owns list) means "this binary's split
	// unit owns these modules"; emit a registration so those modules'
	// nexus.Module(...) calls auto-pick up DeployAs(<unit>) without
	// the user having to type it. Skipped when the deployment is
	// the monolith (empty owns), since monoliths don't tag anything.
	moduleTagRegistrations := buildModuleTagRegistrations(manifest)

	fmt.Fprintln(&b, "func init() {")
	for _, line := range moduleTagRegistrations {
		fmt.Fprintln(&b, "\t"+line)
	}
	if len(moduleTagRegistrations) > 0 {
		fmt.Fprintln(&b)
	}
	fmt.Fprintln(&b, "\tdefaults := nexus.DeploymentDefaults{")
	if isSplitUnit {
		fmt.Fprintf(&b, "\t\tDeployment: %q,\n", deployment)
	}
	if spec.Port > 0 {
		fmt.Fprintf(&b, "\t\tAddr:       fmt_addr(%q, %d),\n", "PORT", spec.Port)
	}
	if len(manifest.Peers) > 0 {
		fmt.Fprintln(&b, "\t\tTopology: nexus.Topology{")
		fmt.Fprintln(&b, "\t\t\tPeers: map[string]nexus.Peer{")
		peerNames := sortedKeysStr(manifest.Peers)
		for _, peer := range peerNames {
			ps := manifest.Peers[peer]
			urlExpr := peerURLExpr(peer, ps.URL, portByTag[peer])
			fmt.Fprintf(&b, "\t\t\t\t%q: {\n", peer)
			fmt.Fprintf(&b, "\t\t\t\t\tURL: %s,\n", urlExpr)
			if ps.Timeout > 0 {
				fmt.Fprintf(&b, "\t\t\t\t\tTimeout: %d * time.Nanosecond,\n", ps.Timeout.Nanoseconds())
			}
			if ps.MinVersion != "" {
				fmt.Fprintf(&b, "\t\t\t\t\tMinVersion: %q,\n", ps.MinVersion)
			}
			if ps.Retries > 0 {
				fmt.Fprintf(&b, "\t\t\t\t\tRetries: %d,\n", ps.Retries)
			}
			if ps.Auth != nil {
				authExpr, err := peerAuthExpr(ps.Auth)
				if err != nil {
					return "", fmt.Errorf("peer %q auth: %w", peer, err)
				}
				fmt.Fprintf(&b, "\t\t\t\t\tAuth: %s,\n", authExpr)
			}
			fmt.Fprintln(&b, "\t\t\t\t},")
		}
		fmt.Fprintln(&b, "\t\t\t},")
		fmt.Fprintln(&b, "\t\t},")
	}
	fmt.Fprintln(&b, "\t}")
	fmt.Fprintln(&b, "\tnexus.SetDeploymentDefaults(defaults)")
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "// fmt_addr resolves the listen address: env var wins (so")
	fmt.Fprintln(&b, "// containers can override), manifest port is the default.")
	fmt.Fprintln(&b, "func fmt_addr(envVar string, defaultPort int) string {")
	fmt.Fprintln(&b, "\tif v := os.Getenv(envVar); v != \"\" {")
	fmt.Fprintln(&b, "\t\tif v[0] == ':' {")
	fmt.Fprintln(&b, "\t\t\treturn v")
	fmt.Fprintln(&b, "\t\t}")
	fmt.Fprintln(&b, "\t\treturn \":\" + v")
	fmt.Fprintln(&b, "\t}")
	fmt.Fprintln(&b, "\treturn fmt_port(defaultPort)")
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "func fmt_port(p int) string {")
	fmt.Fprintln(&b, "\tb := []byte{':'}")
	fmt.Fprintln(&b, "\tif p == 0 { return \":0\" }")
	fmt.Fprintln(&b, "\tdigits := []byte{}")
	fmt.Fprintln(&b, "\tfor p > 0 { digits = append([]byte{byte('0'+p%10)}, digits...); p /= 10 }")
	fmt.Fprintln(&b, "\treturn string(append(b, digits...))")
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "// envOr returns the env var when set, otherwise the fallback.")
	fmt.Fprintln(&b, "// Used so peer URLs default to local-loopback in dev but can be")
	fmt.Fprintln(&b, "// overridden per-environment without code changes.")
	fmt.Fprintln(&b, "func envOr(key, fallback string) string {")
	fmt.Fprintln(&b, "\tif v := os.Getenv(key); v != \"\" {")
	fmt.Fprintln(&b, "\t\treturn v")
	fmt.Fprintln(&b, "\t}")
	fmt.Fprintln(&b, "\treturn fallback")
	fmt.Fprintln(&b, "}")

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return "", fmt.Errorf("gofmt deploy init: %w (raw output:\n%s)", err, b.String())
	}

	out := filepath.Join(shadowDir, "zz_deploy_gen.go")
	if err := os.WriteFile(out, formatted, 0o644); err != nil {
		return "", fmt.Errorf("write deploy init %s: %w", out, err)
	}
	return out, nil
}

// peerURLExpr builds the Go expression for a Peer.URL value:
//
//   - Manifest-supplied url with `${VAR}` literals → expands to
//     os.Getenv reads at runtime, defaulting to the local URL.
//   - Manifest-supplied url without expansion → emit as a string
//     literal.
//   - No manifest url → emit os.Getenv(<TAG>_URL) with the local
//     port as fallback. Convention matches how dev_split sets env
//     vars and how the legacy NewRemoteCallerFromEnv resolved peers.
func peerURLExpr(tag, manifestURL string, peerPort int) string {
	envVar := tagToURLEnvVar(tag)
	fallback := ""
	if peerPort > 0 {
		fallback = fmt.Sprintf("http://localhost:%d", peerPort)
	}
	if manifestURL != "" {
		// Allow ${VAR} interpolation. Anything else is a literal.
		if strings.Contains(manifestURL, "${") {
			// Conservative: when the manifest URL contains ${VAR},
			// generate an os.Getenv($VAR) call returning the
			// remainder if any. For the spike, support a single ${VAR}
			// occupying the whole string.
			start := strings.Index(manifestURL, "${")
			end := strings.Index(manifestURL[start:], "}")
			if end > 0 && start == 0 && end == len(manifestURL)-1 {
				v := manifestURL[2 : len(manifestURL)-1]
				if fallback != "" {
					return fmt.Sprintf("envOr(%q, %q)", v, fallback)
				}
				return fmt.Sprintf("os.Getenv(%q)", v)
			}
			// Fall through to literal for complex patterns; users
			// can do their own env reads.
		}
		return fmt.Sprintf("%q", manifestURL)
	}
	if fallback != "" {
		return fmt.Sprintf("envOr(%q, %q)", envVar, fallback)
	}
	return fmt.Sprintf("os.Getenv(%q)", envVar)
}

// tagToURLEnvVar mirrors the convention used by dev_split.go and
// the legacy NewRemoteCallerFromEnv ("users-svc" → "USERS_SVC_URL").
func tagToURLEnvVar(tag string) string {
	out := strings.ToUpper(tag)
	out = strings.ReplaceAll(out, "-", "_")
	return out + "_URL"
}

// peerAuthExpr emits the Go source for a Peer.Auth closure built
// from the manifest's auth block. Only `bearer` is supported in v1;
// other types fail at build time so the operator finds out at the
// CI gate, not at first request.
//
// The closure body is:
//
//	func(ctx context.Context) (string, error) {
//	    return "Bearer " + os.Getenv("USERS_SVC_TOKEN"), nil
//	}
//
// When the manifest's token is `${VAR}`, we emit os.Getenv("VAR").
// Bare strings emit as a Go string literal — useful for tests, but
// `nexus build` warns operators not to commit real secrets that way.
func peerAuthExpr(spec *AuthSpec) (string, error) {
	switch spec.Type {
	case "bearer":
		tokenExpr, err := tokenExpr(spec.Token)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf(
			"func(ctx context.Context) (string, error) { return \"Bearer \" + %s, nil }",
			tokenExpr,
		), nil
	case "":
		return "", fmt.Errorf("auth.type is required (e.g. \"bearer\")")
	default:
		return "", fmt.Errorf("unsupported auth.type %q (only \"bearer\" is implemented)", spec.Type)
	}
}

// tokenExpr converts a manifest token value into its Go-source
// equivalent: `${VAR}` → `os.Getenv("VAR")`; everything else → a
// quoted string literal. Returns an error when the token is empty
// (a no-token bearer auth makes no sense — fail at build).
func tokenExpr(token string) (string, error) {
	if token == "" {
		return "", fmt.Errorf("auth.token is empty")
	}
	if strings.HasPrefix(token, "${") && strings.HasSuffix(token, "}") {
		varName := strings.TrimSuffix(strings.TrimPrefix(token, "${"), "}")
		if varName == "" {
			return "", fmt.Errorf("auth.token uses empty ${} interpolation")
		}
		return fmt.Sprintf("os.Getenv(%q)", varName), nil
	}
	return fmt.Sprintf("%q", token), nil
}

// anyPeerHasAuth reports whether any peer in the manifest declared
// an auth block. Drives whether the generated zz_deploy_gen.go needs
// to import `context` (Peer.Auth's signature uses context.Context).
func anyPeerHasAuth(manifest *DeployManifest) bool {
	for _, p := range manifest.Peers {
		if p.Auth != nil {
			return true
		}
	}
	return false
}

// anyPeerHasTimeout reports whether any peer declared a non-zero
// timeout. Drives whether the generated zz_deploy_gen.go needs to
// import `time` (Timeout: N * time.Nanosecond is the only reference).
// Without this guard, projects whose peers omit timeouts hit
// "time imported and not used".
func anyPeerHasTimeout(manifest *DeployManifest) bool {
	for _, p := range manifest.Peers {
		if p.Timeout > 0 {
			return true
		}
	}
	return false
}

// buildModuleTagRegistrations turns the manifest's deployments into
// nexus.RegisterModuleDeployment(name, tag) calls, one per (split
// deployment, module) pair. A deployment is a "split unit" iff its
// owns list is non-empty — empty owns means monolith (owns
// everything, no tagging). Returns the lines stably sorted so
// re-runs produce identical output.
//
// When the same module appears in two split deployments (a
// configuration that doesn't make sense — a module can't be local
// in two binaries), the lexically-first deployment wins. The
// duplicate is silently dropped; if this becomes an issue in
// practice, surface it as a build error here.
func buildModuleTagRegistrations(manifest *DeployManifest) []string {
	if manifest == nil {
		return nil
	}
	// First pass: dedupe by module name, deterministic by sorting
	// deployment names. So if two deployments claim the same module,
	// the lexically-earlier deployment's tag is the one that lands.
	deploymentNames := make([]string, 0, len(manifest.Deployments))
	for name := range manifest.Deployments {
		deploymentNames = append(deploymentNames, name)
	}
	sort.Strings(deploymentNames)

	tagByModule := map[string]string{}
	for _, dep := range deploymentNames {
		spec := manifest.Deployments[dep]
		if len(spec.Owns) == 0 {
			continue // monolith — owns everything, tags nothing
		}
		for _, mod := range spec.Owns {
			if _, claimed := tagByModule[mod]; claimed {
				continue
			}
			tagByModule[mod] = dep
		}
	}
	if len(tagByModule) == 0 {
		return nil
	}

	modules := make([]string, 0, len(tagByModule))
	for m := range tagByModule {
		modules = append(modules, m)
	}
	sort.Strings(modules)

	out := make([]string, 0, len(modules))
	for _, m := range modules {
		out = append(out, fmt.Sprintf("nexus.RegisterModuleDeployment(%q, %q)", m, tagByModule[m]))
	}
	return out
}

// mainPackageDir resolves the absolute directory of the named main
// package. Used to compute the logical overlay path for the
// generated zz_deploy_gen.go. The package must already be loadable
// by go/packages.
func mainPackageDir(projectRoot, pkg string) (string, error) {
	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedFiles,
		Dir:  projectRoot,
	}
	pkgs, err := packages.Load(cfg, pkg)
	if err != nil {
		return "", fmt.Errorf("locate main package %q: %w", pkg, err)
	}
	for _, p := range pkgs {
		if len(p.GoFiles) > 0 {
			return filepath.Dir(p.GoFiles[0]), nil
		}
	}
	// Fallback: treat pkg as a relative path.
	abs, err := filepath.Abs(filepath.Join(projectRoot, pkg))
	if err != nil {
		return "", err
	}
	return abs, nil
}

// sortedKeysStr is a typed copy of the sortedKeys helper for
// PeerSpec maps (the original takes map[string]struct{}).
func sortedKeysStr(m map[string]PeerSpec) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
