package main

import (
	"bytes"
	"fmt"
	"io"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"sync"
)

// Tailwind for server-rendered views. A stylesheet that does
// `@import "tailwindcss"` (outside the Vite frontend, which builds its own
// CSS) is an entry: nexus dev runs the Tailwind standalone CLI on it in
// watch mode, and nexus build runs it once, minified, before go build.
//
//	assets/css/input.css  →  assets/css/output.css   (other.css → other.out.css)
//
// When the entry imports "./sources.generated.css", nexus writes that file:
// an @source for the project's .templ files and one for every Go dependency
// that ships .templ files — how a component library imported as a Go module
// (templUI) gets its class names into the stylesheet.

// tailwindEntry is one stylesheet Tailwind compiles.
type tailwindEntry struct {
	Input, Output string
	Sources       string // the sources.generated.css path, "" when not imported
}

const tailwindSourcesFile = "sources.generated.css"

// findTailwindEntries lists the Tailwind stylesheets under root, skipping
// the frontend dir (Vite's own CSS), dependencies and build output.
func findTailwindEntries(root, frontendDir string) []tailwindEntry {
	var out []tailwindEntry
	_ = filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		if d.IsDir() {
			if path != root && (shouldSkipDir(d.Name()) || (frontendDir != "" && pathUnder(path, []string{frontendDir}))) {
				return filepath.SkipDir
			}
			return nil
		}
		name := d.Name()
		if !strings.HasSuffix(name, ".css") || name == tailwindSourcesFile || name == "output.css" || strings.HasSuffix(name, ".out.css") {
			return nil
		}
		b, err := os.ReadFile(path)
		if err != nil || !importsTailwind(b) {
			return nil
		}
		e := tailwindEntry{Input: path, Output: tailwindOutput(path)}
		if bytes.Contains(b, []byte(tailwindSourcesFile)) {
			e.Sources = filepath.Join(filepath.Dir(path), tailwindSourcesFile)
		}
		out = append(out, e)
		return nil
	})
	return out
}

func importsTailwind(css []byte) bool {
	return bytes.Contains(css, []byte(`@import "tailwindcss"`)) || bytes.Contains(css, []byte(`@import 'tailwindcss'`))
}

func tailwindOutput(input string) string {
	dir, base := filepath.Split(input)
	if base == "input.css" {
		return filepath.Join(dir, "output.css")
	}
	return filepath.Join(dir, strings.TrimSuffix(base, ".css")+".out.css")
}

// templModuleDirs lists the directories of the Go modules the project's
// packages depend on that ship .templ files — a component library.
func templModuleDirs(root string) []string {
	cmd := exec.Command("go", "list", "-deps", "-f", "{{with .Module}}{{if not .Main}}{{.Dir}}{{end}}{{end}}", "./...")
	cmd.Dir = root
	out, err := cmd.Output()
	if err != nil {
		return nil
	}
	seen := map[string]bool{}
	var dirs []string
	for _, dir := range strings.Split(strings.TrimSpace(string(out)), "\n") {
		if dir == "" || seen[dir] {
			continue
		}
		seen[dir] = true
		if hasTemplFile(dir) {
			dirs = append(dirs, dir)
		}
	}
	sort.Strings(dirs)
	return dirs
}

func hasTemplFile(dir string) bool {
	found := false
	_ = filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error {
		if err != nil || found {
			return filepath.SkipAll
		}
		if d.IsDir() && path != dir && (d.Name() == "node_modules" || strings.HasPrefix(d.Name(), ".")) {
			return filepath.SkipDir
		}
		if !d.IsDir() && strings.HasSuffix(d.Name(), ".templ") {
			found = true
			return filepath.SkipAll
		}
		return nil
	})
	return found
}

// writeTailwindSources writes an entry's sources.generated.css: the
// project's templates and every dependency's.
func writeTailwindSources(root string, e tailwindEntry, moduleDirs []string) error {
	if e.Sources == "" {
		return nil
	}
	rel, err := filepath.Rel(filepath.Dir(e.Sources), root)
	if err != nil {
		rel = root
	}
	var b strings.Builder
	b.WriteString("/* Generated by nexus: the templates Tailwind scans for class names. */\n")
	fmt.Fprintf(&b, "@source %q;\n", filepath.ToSlash(filepath.Join(rel, "**/*.templ")))
	for _, dir := range moduleDirs {
		fmt.Fprintf(&b, "@source %q;\n", filepath.ToSlash(filepath.Join(dir, "**/*.templ")))
	}
	if old, err := os.ReadFile(e.Sources); err == nil && string(old) == b.String() {
		return nil
	}
	return os.WriteFile(e.Sources, []byte(b.String()), 0o644)
}

// tailwindBinary finds the Tailwind standalone CLI.
func tailwindBinary() (string, error) {
	path, err := exec.LookPath("tailwindcss")
	if err != nil {
		return "", fmt.Errorf("the Tailwind CLI is not on PATH — install the standalone binary (https://github.com/tailwindlabs/tailwindcss/releases) or `brew install tailwindcss`")
	}
	return path, nil
}

// startDevTailwind runs `tailwindcss --watch` for each entry, its output
// prefixed [css]. It returns a stop that ends the processes and waits.
func startDevTailwind(root, frontendDir string, out, stderr io.Writer) func() {
	entries := findTailwindEntries(root, frontendDir)
	if len(entries) == 0 {
		return func() {}
	}
	bin, err := tailwindBinary()
	if err != nil {
		fmt.Fprintf(stderr, "%s●%s css: %v\n", ansiYellow, ansiReset, err)
		return func() {}
	}
	mods := templModuleDirs(root)
	var stops []func()
	for _, e := range entries {
		if err := writeTailwindSources(root, e, mods); err != nil {
			fmt.Fprintf(stderr, "%s●%s css: %v\n", ansiYellow, ansiReset, err)
		}
		lw := &prefixLineWriter{w: out, prefix: fmt.Sprintf("%s[css]%s ", ansiCyan, ansiReset)}
		cmd := exec.Command(bin, "-i", e.Input, "-o", e.Output, "--watch=always")
		cmd.Dir = root
		cmd.Stdout, cmd.Stderr = lw, lw
		setProcessGroup(cmd)
		if err := cmd.Start(); err != nil {
			fmt.Fprintf(stderr, "%s●%s css: %v\n", ansiYellow, ansiReset, err)
			continue
		}
		rel, _ := filepath.Rel(root, e.Output)
		fmt.Fprintf(out, "  %s● css · tailwind → %s%s\n", ansiDim, rel, ansiReset)
		done := make(chan struct{})
		go func() { _ = cmd.Wait(); lw.flush(); close(done) }()
		stops = append(stops, func() { stopProcessGroup(cmd.Process.Pid, done, viteKillGrace, nil) })
	}
	return func() {
		for _, stop := range stops {
			stop()
		}
	}
}

// buildTailwind compiles every entry once, minified — nexus build.
func buildTailwind(root, frontendDir string, out io.Writer) error {
	entries := findTailwindEntries(root, frontendDir)
	if len(entries) == 0 {
		return nil
	}
	bin, err := tailwindBinary()
	if err != nil {
		return err
	}
	mods := templModuleDirs(root)
	for _, e := range entries {
		if err := writeTailwindSources(root, e, mods); err != nil {
			return err
		}
		cmd := exec.Command(bin, "-i", e.Input, "-o", e.Output, "--minify")
		cmd.Dir = root
		var buf bytes.Buffer
		cmd.Stdout, cmd.Stderr = &buf, &buf
		if err := cmd.Run(); err != nil {
			return fmt.Errorf("tailwind %s: %v\n%s", e.Input, err, buf.String())
		}
		rel, _ := filepath.Rel(root, e.Output)
		fmt.Fprintf(out, "css: tailwind → %s\n", rel)
	}
	return nil
}

// prefixLineWriter prints each line it receives behind a prefix.
type prefixLineWriter struct {
	w      io.Writer
	prefix string
	mu     sync.Mutex
	buf    []byte
}

func (l *prefixLineWriter) Write(p []byte) (int, error) {
	l.mu.Lock()
	defer l.mu.Unlock()
	l.buf = append(l.buf, p...)
	for {
		i := bytes.IndexByte(l.buf, '\n')
		if i < 0 {
			return len(p), nil
		}
		if line := strings.TrimRight(string(l.buf[:i]), "\r"); strings.TrimSpace(line) != "" {
			fmt.Fprintf(l.w, "%s%s\n", l.prefix, line)
		}
		l.buf = l.buf[i+1:]
	}
}

func (l *prefixLineWriter) flush() {
	l.mu.Lock()
	defer l.mu.Unlock()
	if strings.TrimSpace(string(l.buf)) != "" {
		fmt.Fprintf(l.w, "%s%s\n", l.prefix, string(l.buf))
	}
	l.buf = nil
}
