package main

import (
	"encoding/json"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/paulmanoni/deco/transpiler"
	"github.com/paulmanoni/nexus/internal/handlergen"
)

// allHandlerArtifacts returns every file the codegen produces under root: one
// per-package registration file (outName) PLUS a nexus_imports_gen.go in the
// main package that blank-imports the annotated packages — so they're pulled
// into the build (and their init() runs) without the app writing any import.
// The aggregator is omitted when there's no main package or no annotated
// package outside it.
func allHandlerArtifacts(root, outName string) ([]handlergen.Result, error) {
	results, err := scanHandlerSites(root, outName)
	if err != nil {
		return nil, err
	}
	if len(results) == 0 {
		return results, nil
	}
	agg, ok, err := aggregatorResult(root, results)
	if err != nil {
		return nil, err
	}
	if ok {
		results = append(results, agg)
	}
	return results, nil
}

// aggregatorResult builds the main package's blank-import file. ok is false when
// no main package is found or every annotated package already IS the main
// package (nothing to pull in).
func aggregatorResult(root string, results []handlergen.Result) (handlergen.Result, bool, error) {
	mainDir, err := findMainDir(root)
	if err != nil || mainDir == "" {
		return handlergen.Result{}, false, err
	}
	seen := map[string]bool{}
	var paths []string
	for _, r := range results {
		dir := filepath.Dir(r.Path)
		if dir == mainDir {
			continue // annotations in main itself need no import
		}
		ip, err := importPathOf(dir)
		if err != nil {
			return handlergen.Result{}, false, fmt.Errorf("resolve import path of %s: %w", dir, err)
		}
		if ip != "" && !seen[ip] {
			seen[ip] = true
			paths = append(paths, ip)
		}
	}
	if len(paths) == 0 {
		return handlergen.Result{}, false, nil
	}
	sort.Strings(paths)

	var b strings.Builder
	b.WriteString("// Code generated by \"nexus generate handlers\"; DO NOT EDIT.\n\n")
	b.WriteString("package main\n\n")
	b.WriteString("// Blank imports pull every //@-annotated package into the build so its\n")
	b.WriteString("// generated init() registers with decorate; nexus.Boot/Run auto-drains them.\n")
	b.WriteString("import (\n")
	for _, p := range paths {
		fmt.Fprintf(&b, "\t_ %s\n", strconv.Quote(p))
	}
	b.WriteString(")\n")
	content, err := format.Source([]byte(b.String()))
	if err != nil {
		return handlergen.Result{}, false, fmt.Errorf("format aggregator: %w", err)
	}
	return handlergen.Result{Path: filepath.Join(mainDir, "nexus_imports_gen.go"), Content: content}, true, nil
}

// findMainDir returns the absolute dir of the `package main` under root (the
// first, if several), or "" when there is none. Best-effort via `go list`.
func findMainDir(root string) (string, error) {
	cmd := exec.Command("go", "list", "-find", "-f", `{{if eq .Name "main"}}{{.Dir}}{{end}}`, "./...")
	cmd.Dir = root
	out, err := cmd.Output()
	if err != nil {
		return "", nil // no module / unbuildable tree → just skip the aggregator
	}
	for _, line := range strings.Split(strings.TrimSpace(string(out)), "\n") {
		if line = strings.TrimSpace(line); line != "" {
			return line, nil
		}
	}
	return "", nil
}

// importPathOf returns the import path of the package in dir via `go list`.
func importPathOf(dir string) (string, error) {
	cmd := exec.Command("go", "list", "-find", "-f", "{{.ImportPath}}", ".")
	cmd.Dir = dir
	out, err := cmd.Output()
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(string(out)), nil
}

// handlerGenFileName is the file `nexus generate handlers` writes (committed)
// and `nexus dev` injects via overlay (ephemeral). Shared so the two paths
// agree on the target path.
const handlerGenFileName = "nexus_handlers_gen.go"

// scanHandlerSites scans the package tree under root for //@ handler
// annotations and returns the generated registration files in memory, named
// outName per package. root may be "." or "./...".
func scanHandlerSites(root, outName string) ([]handlergen.Result, error) {
	if root == "./..." || root == "..." {
		root = "."
	}
	// Scan ALL //@ directives, then keep the built-in keywords plus any
	// QUALIFIED (pkg.Func) custom-extension decorator. Unqualified directives
	// we don't recognize are ignored (they may belong to another tool).
	hits, err := transpiler.Scan(root)
	if err != nil {
		return nil, fmt.Errorf("scan: %w", err)
	}
	sites := make([]handlergen.Site, 0, len(hits))
	for _, h := range hits {
		kw := h.Keyword
		qualified := strings.Contains(kw, ".")
		if !builtinHandlerKeyword(kw) && !qualified {
			continue
		}
		site := handlergen.Site{
			Dir:     filepath.Dir(h.File),
			Pkg:     h.Pkg,
			Func:    h.Func,
			Keyword: kw,
			Args:    h.Args,
			Line:    h.Pos.Line,
		}
		switch {
		case kw == "use":
			// //@use expressions may reference imported packages (e.g.
			// //@use ratelimit.Per(...)); resolve those from the annotated file.
			imps, err := resolveUseImports(h.File, h.Args)
			if err != nil {
				return nil, fmt.Errorf("%s: //@use on %s: %w", h.File, h.Func, err)
			}
			site.Imports = imps
		case qualified:
			// Custom decorator //@pkg.Func … — import the package from the file.
			sel := kw[:strings.IndexByte(kw, '.')]
			imp, err := resolveSelectorImport(h.File, sel)
			if err != nil {
				return nil, fmt.Errorf("%s: //@%s on %s: %w", h.File, kw, h.Func, err)
			}
			site.Imports = []string{imp}
		}
		sites = append(sites, site)
	}
	return handlergen.Generate(sites, outName)
}

// handlerKeywordSet is handlerKeywords as a set for O(1) membership.
var handlerKeywordSet = func() map[string]bool {
	m := make(map[string]bool, len(handlerKeywords))
	for _, k := range handlerKeywords {
		m[k] = true
	}
	return m
}()

func builtinHandlerKeyword(kw string) bool { return handlerKeywordSet[kw] }

// resolveSelectorImport returns the import line for package selector sel from
// file's import block, erroring if the package isn't imported there.
func resolveSelectorImport(file, sel string) (string, error) {
	imps, err := importsOfFile(file)
	if err != nil {
		return "", err
	}
	line, ok := imps[sel]
	if !ok {
		return "", fmt.Errorf("package %q is not imported in this file — add its import so the generated registration can call %s.…", sel, sel)
	}
	return line, nil
}

// resolveUseImports returns the import lines a //@use expression needs, by
// matching the package selectors in the expression against the annotated file's
// own import block. Selectors that aren't imported packages (a local var or
// type referenced in the expression) are left out — they resolve in the
// generated file's own package.
func resolveUseImports(file string, exprArgs []string) ([]string, error) {
	expr := strings.Join(exprArgs, " ")
	e, err := parser.ParseExpr(expr)
	if err != nil {
		return nil, fmt.Errorf("parse expression %q: %w", expr, err)
	}
	fileImports, err := importsOfFile(file)
	if err != nil {
		return nil, err
	}
	seen := map[string]bool{}
	var lines []string
	ast.Inspect(e, func(n ast.Node) bool {
		if sel, ok := n.(*ast.SelectorExpr); ok {
			if id, ok := sel.X.(*ast.Ident); ok {
				if line, ok := fileImports[id.Name]; ok && !seen[line] {
					seen[line] = true
					lines = append(lines, line)
				}
			}
		}
		return true
	})
	return lines, nil
}

// importsOfFile parses file's import block into selector -> import line
// (`"path"` or `alias "path"`). Blank and dot imports are skipped.
func importsOfFile(file string) (map[string]string, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, file, nil, parser.ImportsOnly)
	if err != nil {
		return nil, err
	}
	out := map[string]string{}
	for _, spec := range f.Imports {
		path, err := strconv.Unquote(spec.Path.Value)
		if err != nil {
			continue
		}
		sel := path[strings.LastIndexByte(path, '/')+1:]
		line := strconv.Quote(path)
		if spec.Name != nil {
			n := spec.Name.Name
			if n == "_" || n == "." {
				continue
			}
			sel = n
			line = n + " " + strconv.Quote(path)
		}
		out[sel] = line
	}
	return out, nil
}

// buildHandlerOverlay scans root, generates the registration files, and writes
// them to a temp dir as a `go build -overlay` JSON — so `nexus dev` injects the
// decorator-form registrations WITHOUT writing anything into the source tree
// (zero churn). The overlay's keys are the absolute paths the committed files
// would occupy, so an existing committed file is transparently shadowed.
//
// Returns ("", noop, nil) when no annotations are found. cleanup removes the
// temp dir; callers must invoke it once the build that consumes the overlay has
// finished.
func buildHandlerOverlay(root string) (overlayPath string, cleanup func(), err error) {
	noop := func() {}
	results, err := allHandlerArtifacts(root, handlerGenFileName)
	if err != nil {
		return "", noop, err
	}
	if len(results) == 0 {
		return "", noop, nil
	}

	tmp, err := os.MkdirTemp("", "nexus-handlers-overlay-")
	if err != nil {
		return "", noop, err
	}
	cleanup = func() { _ = os.RemoveAll(tmp) }

	replace := make(map[string]string, len(results))
	for i, r := range results {
		shadow := filepath.Join(tmp, fmt.Sprintf("%d_%s", i, filepath.Base(r.Path)))
		if err := os.WriteFile(shadow, r.Content, 0o644); err != nil {
			cleanup()
			return "", noop, err
		}
		replace[r.Path] = shadow
	}

	overlayPath = filepath.Join(tmp, "overlay.json")
	doc := struct{ Replace map[string]string }{Replace: replace}
	data, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		cleanup()
		return "", noop, err
	}
	if err := os.WriteFile(overlayPath, data, 0o644); err != nil {
		cleanup()
		return "", noop, err
	}
	return overlayPath, cleanup, nil
}

// writeHandlerFiles scans root and writes the committed registration files,
// skipping byte-equal no-ops. Returns the number written. Used by `nexus build`
// to refresh the committed *_gen.go before compiling, so a plain go build /
// go install (which never run this) sees current registrations.
func writeHandlerFiles(root string) (int, error) {
	results, err := allHandlerArtifacts(root, handlerGenFileName)
	if err != nil {
		return 0, err
	}
	written := 0
	for _, r := range results {
		if cur, err := os.ReadFile(r.Path); err == nil && string(cur) == string(r.Content) {
			continue
		}
		if err := os.WriteFile(r.Path, r.Content, 0o644); err != nil {
			return written, fmt.Errorf("write %s: %w", r.Path, err)
		}
		written++
	}
	return written, nil
}
