package main

import (
	"encoding/json"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	toml "github.com/pelletier/go-toml/v2"

	"github.com/paulmanoni/deco/transpiler"
	"github.com/paulmanoni/nexus/internal/handlergen"
)

// allHandlerArtifacts returns every file the codegen produces under root: one
// per-package registration file (outName) PLUS a nexus_imports_gen.go in the
// main package that blank-imports the annotated packages — so they're pulled
// into the build (and their init() runs) without the app writing any import.
// The aggregator is omitted when there's no main package or no annotated
// package outside it.
func allHandlerArtifacts(root, outName string) ([]handlergen.Result, error) {
	results, err := scanHandlerSites(root, outName)
	if err != nil {
		return nil, err
	}
	if len(results) == 0 {
		return results, nil
	}
	agg, ok, err := aggregatorResult(root, results)
	if err != nil {
		return nil, err
	}
	if ok {
		results = append(results, agg)
	}
	return results, nil
}

// aggregatorResult builds the main package's blank-import file. ok is false when
// no main package is found or every annotated package already IS the main
// package (nothing to pull in).
func aggregatorResult(root string, results []handlergen.Result) (handlergen.Result, bool, error) {
	mainDir, err := pkgs.mainDir(root)
	if err != nil || mainDir == "" {
		return handlergen.Result{}, false, err
	}
	seen := map[string]bool{}
	var paths []string
	for _, r := range results {
		dir := filepath.Dir(r.Path)
		if dir == mainDir {
			continue // annotations in main itself need no import
		}
		ip, err := pkgs.importPath(root, dir)
		if err != nil {
			return handlergen.Result{}, false, fmt.Errorf("resolve import path of %s: %w", dir, err)
		}
		if ip != "" && !seen[ip] {
			seen[ip] = true
			paths = append(paths, ip)
		}
	}
	if len(paths) == 0 {
		return handlergen.Result{}, false, nil
	}
	sort.Strings(paths)

	var b strings.Builder
	b.WriteString("// Code generated by \"nexus generate handlers\"; DO NOT EDIT.\n\n")
	b.WriteString("package main\n\n")
	b.WriteString("// Blank imports pull every //@-annotated package into the build so its\n")
	b.WriteString("// generated init() registers with decorate; nexus.Boot/Run auto-drains them.\n")
	b.WriteString("import (\n")
	for _, p := range paths {
		fmt.Fprintf(&b, "\t_ %s\n", strconv.Quote(p))
	}
	b.WriteString(")\n")
	content, err := format.Source([]byte(b.String()))
	if err != nil {
		return handlergen.Result{}, false, fmt.Errorf("format aggregator: %w", err)
	}
	return handlergen.Result{Path: filepath.Join(mainDir, "nexus_imports_gen.go"), Content: content}, true, nil
}

// handlerGenFileName is the file `nexus generate handlers` writes (committed)
// and `nexus dev` injects via overlay (ephemeral). Shared so the two paths
// agree on the target path.
const handlerGenFileName = "nexus_handlers_gen.go"

// scanHandlerSites scans the package tree under root for //@ handler
// annotations and returns the generated registration files in memory, named
// outName per package. root may be "." or "./...".
func scanHandlerSites(root, outName string) ([]handlergen.Result, error) {
	if root == "./..." || root == "..." {
		root = "."
	}
	// Scan ALL //@ directives, then keep the built-in keywords plus any
	// QUALIFIED (pkg.Func) custom-extension decorator. Unqualified directives
	// we don't recognize are ignored (they may belong to another tool).
	hits, err := transpiler.Scan(root)
	if err != nil {
		return nil, fmt.Errorf("scan: %w", err)
	}
	// One resolver per scan: its per-file/dir caches and the (lazy) module
	// import graph are shared across every qualified //@pkg.Func annotation.
	res := newSelectorResolver(root)
	sites := make([]handlergen.Site, 0, len(hits))
	for _, h := range hits {
		kw := h.Keyword
		qualified := strings.Contains(kw, ".")
		if !builtinHandlerKeyword(kw) && !qualified {
			continue
		}
		site := handlergen.Site{
			Dir:     filepath.Dir(h.File),
			Pkg:     h.Pkg,
			Func:    h.Func,
			Keyword: kw,
			Args:    h.Args,
			Line:    h.Pos.Line,
		}
		switch {
		case kw == "use":
			// //@use expressions may reference imported packages (e.g.
			// //@use ratelimit.Per(...)); resolve those from the annotated file.
			imps, err := resolveUseImports(h.File, h.Args)
			if err != nil {
				return nil, fmt.Errorf("%s: //@use on %s: %w", h.File, h.Func, err)
			}
			site.Imports = imps
		case qualified:
			// Custom decorator //@pkg.Func … — resolve the package import so the
			// generated file can call pkg.Func(...). The resolver looks in the
			// annotated file, then its sibling files, then nexus.toml hints, then
			// the module import graph (see selectorResolver.resolve).
			sel := kw[:strings.IndexByte(kw, '.')]
			imp, err := res.resolve(h.File, sel)
			if err != nil {
				return nil, fmt.Errorf("%s: //@%s on %s: %w", h.File, kw, h.Func, err)
			}
			site.Imports = []string{imp}
		}
		sites = append(sites, site)
	}
	return handlergen.Generate(sites, outName)
}

// handlerKeywordSet is handlerKeywords as a set for O(1) membership.
var handlerKeywordSet = func() map[string]bool {
	m := make(map[string]bool, len(handlerKeywords))
	for _, k := range handlerKeywords {
		m[k] = true
	}
	return m
}()

func builtinHandlerKeyword(kw string) bool { return handlerKeywordSet[kw] }

// selectorResolver maps a package selector from a qualified //@pkg.Func
// decorator (e.g. "inertia") to the import line the generated file should carry,
// so the emitted pkg.Func(...) call compiles. It never edits the user's source:
// the import lands only in the generated nexus_handlers_gen.go.
//
// Resolution is a cascade, cheapest/most-authoritative first (see resolve). All
// layers are cached; the module import graph (the costly one) is built lazily
// and at most once per scan, only when the cheap layers miss.
type selectorResolver struct {
	root string

	fileCache map[string]map[string]string // file -> selector -> import line
	dirCache  map[string]map[string]string // package dir -> merged selector -> import line
	hints     map[string]string            // [decorators.imports] from nexus.toml
}

func newSelectorResolver(root string) *selectorResolver {
	return &selectorResolver{
		root:      root,
		fileCache: map[string]map[string]string{},
		dirCache:  map[string]map[string]string{},
		hints:     loadDecoratorHints(root),
	}
}

// resolve returns the import line for selector sel as referenced from file.
func (r *selectorResolver) resolve(file, sel string) (string, error) {
	// Layer 1 — the annotated file's own imports (honors aliases + blank opt-in).
	if line, ok := r.fileImports(file)[sel]; ok {
		return line, nil
	}
	// Layer 2 — any sibling file in the same package (e.g. module.go).
	if line, ok := r.dirImports(filepath.Dir(file))[sel]; ok {
		return line, nil
	}
	// Layer 4 — explicit nexus.toml [decorators.imports] override.
	if path, ok := r.hints[sel]; ok {
		return importLineFor(sel, path), nil
	}
	// Layer 3 — the module import graph, matched on real package name. It's
	// cached across scans (see pkgIndex); a selector that isn't in the cached
	// copy earns one rebuild, since a dependency added mid-session is exactly
	// what a miss looks like.
	graph, err := pkgs.moduleGraph(r.root, false)
	if err == nil && len(graph[sel]) == 0 {
		graph, err = pkgs.moduleGraph(r.root, true)
	}
	if err != nil {
		return "", fmt.Errorf("package %q is not imported here and the module graph could not be read (%v) — import it or set [decorators.imports].%s in nexus.toml", sel, err, sel)
	}
	switch paths := graph[sel]; len(paths) {
	case 1:
		return importLineFor(sel, paths[0]), nil
	case 0:
		return "", fmt.Errorf("package %q is not a dependency — import it, run `go get`, or set [decorators.imports].%s in nexus.toml", sel, sel)
	default:
		sort.Strings(paths)
		return "", fmt.Errorf("package %q is ambiguous across %s — import it explicitly or set [decorators.imports].%s in nexus.toml", sel, strings.Join(paths, ", "), sel)
	}
}

// fileImports returns (cached) the selector->import map for a single file.
func (r *selectorResolver) fileImports(file string) map[string]string {
	if m, ok := r.fileCache[file]; ok {
		return m
	}
	m, err := importsOfFile(file)
	if err != nil || m == nil {
		m = map[string]string{}
	}
	r.fileCache[file] = m
	return m
}

// dirImports returns (cached) the merged selector->import map for every .go file
// in a package directory, so an import in any sibling file resolves.
func (r *selectorResolver) dirImports(dir string) map[string]string {
	if m, ok := r.dirCache[dir]; ok {
		return m
	}
	merged := map[string]string{}
	entries, _ := os.ReadDir(dir)
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") {
			continue
		}
		for sel, line := range r.fileImports(filepath.Join(dir, e.Name())) {
			if _, ok := merged[sel]; !ok {
				merged[sel] = line
			}
		}
	}
	r.dirCache[dir] = merged
	return merged
}

// importLineFor builds the import line so the generated file's `sel.Func(...)`
// call binds: a plain import when the path's last segment already is sel,
// otherwise an explicit alias.
func importLineFor(sel, path string) string {
	if pathTail(path) == sel {
		return strconv.Quote(path)
	}
	return sel + " " + strconv.Quote(path)
}

func pathTail(path string) string { return path[strings.LastIndexByte(path, '/')+1:] }

// loadDecoratorHints reads the optional [decorators.imports] table from the
// project's nexus.toml (selector -> import path). Absent/unparsable -> nil.
func loadDecoratorHints(root string) map[string]string {
	dir := root
	if fi, err := os.Stat(root); err == nil && !fi.IsDir() {
		dir = filepath.Dir(root)
	}
	b, err := os.ReadFile(filepath.Join(dir, "nexus.toml"))
	if err != nil {
		return nil
	}
	var cfg struct {
		Decorators struct {
			Imports map[string]string `toml:"imports"`
		} `toml:"decorators"`
	}
	if err := toml.Unmarshal(b, &cfg); err != nil {
		return nil
	}
	return cfg.Decorators.Imports
}

// resolveUseImports returns the import lines a //@use expression needs, by
// matching the package selectors in the expression against the annotated file's
// own import block. Selectors that aren't imported packages (a local var or
// type referenced in the expression) are left out — they resolve in the
// generated file's own package.
func resolveUseImports(file string, exprArgs []string) ([]string, error) {
	expr := strings.Join(exprArgs, " ")
	e, err := parser.ParseExpr(expr)
	if err != nil {
		return nil, fmt.Errorf("parse expression %q: %w", expr, err)
	}
	fileImports, err := importsOfFile(file)
	if err != nil {
		return nil, err
	}
	seen := map[string]bool{}
	var lines []string
	ast.Inspect(e, func(n ast.Node) bool {
		if sel, ok := n.(*ast.SelectorExpr); ok {
			if id, ok := sel.X.(*ast.Ident); ok {
				if line, ok := fileImports[id.Name]; ok && !seen[line] {
					seen[line] = true
					lines = append(lines, line)
				}
			}
		}
		return true
	})
	return lines, nil
}

// importsOfFile parses file's import block into selector -> import line
// (`"path"` or `alias "path"`). Dot imports are skipped. A blank import
// (`_ "path"`) is recorded under its path-tail selector as a PLAIN import: it's
// a codegen opt-in for a file that doesn't otherwise use the package (a normal
// import there would be "imported and not used"), and the generated file does
// reference the package, so it needs a real, non-blank import.
func importsOfFile(file string) (map[string]string, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, file, nil, parser.ImportsOnly)
	if err != nil {
		return nil, err
	}
	out := map[string]string{}
	for _, spec := range f.Imports {
		path, err := strconv.Unquote(spec.Path.Value)
		if err != nil {
			continue
		}
		sel := pathTail(path)
		line := strconv.Quote(path)
		if spec.Name != nil {
			n := spec.Name.Name
			switch n {
			case ".":
				continue // dot import: no usable selector
			case "_":
				// keep the path-tail selector + plain import line above
			default:
				sel = n
				line = n + " " + strconv.Quote(path)
			}
		}
		out[sel] = line
	}
	return out, nil
}

// buildHandlerOverlay scans root, generates the registration files, and writes
// them to a temp dir as a `go build -overlay` JSON — so `nexus dev` injects the
// decorator-form registrations WITHOUT writing anything into the source tree
// (zero churn). The overlay's keys are the absolute paths the committed files
// would occupy, so an existing committed file is transparently shadowed.
//
// Returns ("", noop, nil) when no annotations are found. cleanup removes the
// temp dir; callers must invoke it once the build that consumes the overlay has
// finished.
func buildHandlerOverlay(root string) (overlayPath string, cleanup func(), err error) {
	return buildDevOverlay(root, "")
}

// buildDevOverlay is buildHandlerOverlay plus, when distStubRoot is non-empty,
// the frontend-bundle stubs described in distStubReplacements. Go takes a
// single -overlay file, so the two contributions have to share one document.
//
// Only `nexus dev` passes a distStubRoot: `nexus build` produces the real
// binary and must embed the real bundle.
func buildDevOverlay(root, distStubRoot string) (overlayPath string, cleanup func(), err error) {
	noop := func() {}
	results, err := allHandlerArtifacts(root, handlerGenFileName)
	if err != nil {
		return "", noop, err
	}
	if len(results) == 0 && distStubRoot == "" {
		return "", noop, nil
	}

	tmp, err := os.MkdirTemp("", "nexus-handlers-overlay-")
	if err != nil {
		return "", noop, err
	}
	cleanup = func() { _ = os.RemoveAll(tmp) }

	replace := make(map[string]string, len(results))
	for i, r := range results {
		shadow := filepath.Join(tmp, fmt.Sprintf("%d_%s", i, filepath.Base(r.Path)))
		if err := os.WriteFile(shadow, r.Content, 0o644); err != nil {
			cleanup()
			return "", noop, err
		}
		replace[r.Path] = shadow
	}

	stubs, err := distStubReplacements(distStubRoot, tmp)
	if err != nil {
		cleanup()
		return "", noop, err
	}
	for path, shadow := range stubs {
		// Handler artifacts win: they're .go files, the stubs are assets, so
		// a collision shouldn't happen — but a generated file silently
		// replaced by an empty stub would be baffling to debug.
		if _, taken := replace[path]; !taken {
			replace[path] = shadow
		}
	}
	if len(replace) == 0 {
		cleanup()
		return "", noop, nil
	}

	overlayPath = filepath.Join(tmp, "overlay.json")
	doc := struct{ Replace map[string]string }{Replace: replace}
	data, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		cleanup()
		return "", noop, err
	}
	if err := os.WriteFile(overlayPath, data, 0o644); err != nil {
		cleanup()
		return "", noop, err
	}
	return overlayPath, cleanup, nil
}
