package main

import (
	"encoding/json"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	toml "github.com/pelletier/go-toml/v2"

	"github.com/paulmanoni/deco/transpiler"
	"github.com/paulmanoni/nexus/cmd/nexus/v2/internal/handlergen"
	"github.com/paulmanoni/nexus/v2/view/viewgen"
)

// allHandlerArtifacts returns every file the codegen produces under root: one
// per-package registration file (outName) PLUS a nexus_imports_gen.go in the
// main package that blank-imports the annotated packages — so they're pulled
// into the build (and their init() runs) without the app writing any import.
// The aggregator is omitted when there's no main package or no annotated
// package outside it.
func allHandlerArtifacts(root, outName string) ([]handlergen.Result, error) {
	results, err := scanHandlerSites(root, outName)
	if err != nil {
		return nil, err
	}
	if len(results) == 0 {
		return results, nil
	}
	agg, ok, err := aggregatorResult(root, results)
	if err != nil {
		return nil, err
	}
	if ok {
		results = append(results, agg)
	}
	return results, nil
}

// aggregatorResult builds the main package's blank-import file. ok is false when
// no main package is found or every annotated package already IS the main
// package (nothing to pull in).
func aggregatorResult(root string, results []handlergen.Result) (handlergen.Result, bool, error) {
	mainDir, err := pkgs.mainDir(root)
	if err != nil || mainDir == "" {
		return handlergen.Result{}, false, err
	}
	seen := map[string]bool{}
	var paths []string
	for _, r := range results {
		dir := filepath.Dir(r.Path)
		if dir == mainDir {
			continue // annotations in main itself need no import
		}
		ip, err := pkgs.importPath(root, dir)
		if err != nil {
			return handlergen.Result{}, false, fmt.Errorf("resolve import path of %s: %w", dir, err)
		}
		if ip != "" && !seen[ip] {
			seen[ip] = true
			paths = append(paths, ip)
		}
	}
	if len(paths) == 0 {
		return handlergen.Result{}, false, nil
	}
	sort.Strings(paths)

	var b strings.Builder
	b.WriteString("// Code generated by \"nexus generate handlers\"; DO NOT EDIT.\n\n")
	b.WriteString("package main\n\n")
	b.WriteString("// Blank imports pull every //@-annotated package into the build so its\n")
	b.WriteString("// generated init() registers with decorate; nexus.Boot/Run auto-drains them.\n")
	b.WriteString("import (\n")
	for _, p := range paths {
		fmt.Fprintf(&b, "\t_ %s\n", strconv.Quote(p))
	}
	b.WriteString(")\n")
	content, err := format.Source([]byte(b.String()))
	if err != nil {
		return handlergen.Result{}, false, fmt.Errorf("format aggregator: %w", err)
	}
	return handlergen.Result{Path: filepath.Join(mainDir, "nexus_imports_gen.go"), Content: content}, true, nil
}

// devScanCache makes the per-rebuild annotation scan incremental: `nexus
// dev` re-scans the whole tree before every build, and the cache re-parses
// only the files that changed since the previous one. Process-lifetime state
// keyed on (path, mtime, size); a one-shot `nexus generate handlers` simply
// fills it once.
var devScanCache = transpiler.NewScanCache()

// handlerGenFileName is the file `nexus generate handlers` writes (committed)
// and `nexus dev` injects via overlay (ephemeral). Shared so the two paths
// agree on the target path.
const handlerGenFileName = "nexus_handlers_gen.go"

// scanHandlerSites scans the package tree under root for //@ handler
// annotations and returns the generated registration files in memory, named
// outName per package. root may be "." or "./...".
func scanHandlerSites(root, outName string) ([]handlergen.Result, error) {
	if root == "./..." || root == "..." {
		root = "."
	}
	// Scan ALL //@ directives, then keep the built-in keywords plus any
	// QUALIFIED (pkg.Func) custom-extension decorator. Unqualified directives
	// we don't recognize are ignored (they may belong to another tool).
	hits, err := devScanCache.Scan(root)
	if err != nil {
		return nil, fmt.Errorf("scan: %w", err)
	}
	// One resolver per scan: its per-file/dir caches and the (lazy) module
	// import graph are shared across every qualified //@pkg.Func annotation.
	res := newSelectorResolver(root)
	decls := newDeclIndex()
	sites := make([]handlergen.Site, 0, len(hits))
	dirs := map[string]bool{}
	for _, h := range hits {
		// templ copies a component's doc comment into its generated Go, so a
		// view's //@page / //@auth reappears in *_templ.go. Those directives
		// belong to the .templ source, which the views generator compiles.
		if strings.HasSuffix(h.File, "_templ.go") {
			continue
		}
		kw := h.Keyword
		qualified := strings.Contains(kw, ".")
		if !builtinHandlerKeyword(kw) && !qualified {
			// Unknown unqualified keyword: a typo of a nexus keyword is an
			// error (a silently dropped route is baffling to debug); anything
			// else is left for other tools.
			if want, close := nearHandlerKeyword(kw); close {
				return nil, fmt.Errorf("%s:%d: unknown annotation //@%s on %s — did you mean //@%s?",
					displayRel(h.File), h.Pos.Line, kw, h.Func, want)
			}
			continue
		}
		if h.PackageLevel && qualified {
			return nil, fmt.Errorf("%s:%d: //@%s is a custom decorator, which is function-level — annotate a function, not the package doc",
				displayRel(h.File), h.Pos.Line, kw)
		}
		site := handlergen.Site{
			Dir:          filepath.Dir(h.File),
			Pkg:          h.Pkg,
			File:         displayRel(h.File),
			Func:         h.Func,
			Keyword:      kw,
			Args:         h.Args,
			Line:         h.Pos.Line,
			PackageLevel: h.PackageLevel,
		}
		if h.Func != "" && !h.PackageLevel {
			m, err := decls.method(h.File, h.Func, h.Pos.Line)
			if err != nil {
				return nil, fmt.Errorf("%s:%d: //@%s on %s: %w", displayRel(h.File), h.Pos.Line, kw, h.Func, err)
			}
			if m != nil {
				site.Recv, site.Method, site.Func = m.recv, m.name, m.expr()
			}
		}
		dirs[filepath.Dir(h.File)] = true
		switch {
		case kw == "use":
			// //@use expressions may reference packages (e.g.
			// //@use ratelimit.Per(...)); resolve them through the full cascade.
			imps, err := resolveUseImports(res, h.File, h.Args)
			if err != nil {
				return nil, fmt.Errorf("%s:%d: //@use on %s: %w", displayRel(h.File), h.Pos.Line, h.Func, err)
			}
			site.Imports = imps
		case qualified:
			// Custom decorator //@pkg.Func … — resolve the package import so the
			// generated file can call pkg.Func(...). The resolver looks in the
			// annotated file, then its sibling files, then nexus.toml hints, then
			// the module import graph (see selectorResolver.resolve).
			sel := kw[:strings.IndexByte(kw, '.')]
			imp, err := res.resolve(h.File, sel)
			if err != nil {
				return nil, fmt.Errorf("%s:%d: //@%s on %s: %w", displayRel(h.File), h.Pos.Line, kw, h.Func, err)
			}
			site.Imports = []string{imp}
		}
		sites = append(sites, site)
	}
	typeSites, err := decls.typeSites(dirs, res)
	if err != nil {
		return nil, err
	}
	sites = append(sites, typeSites...)
	return handlergen.Generate(sites, outName)
}

// declIndex answers what the directive scan leaves out: which receiver an
// annotated method has, and the //@controller directives on type
// declarations (the scan reads function and package doc comments only).
// Files are parsed once per scan.
type declIndex struct {
	files map[string]*ast.File
	fset  *token.FileSet
}

func newDeclIndex() *declIndex {
	return &declIndex{files: map[string]*ast.File{}, fset: token.NewFileSet()}
}

func (d *declIndex) parse(file string) (*ast.File, error) {
	if f, ok := d.files[file]; ok {
		return f, nil
	}
	f, err := parser.ParseFile(d.fset, file, nil, parser.ParseComments|parser.SkipObjectResolution)
	if err != nil {
		return nil, err
	}
	d.files[file] = f
	return f, nil
}

// methodDecl is an annotated method's receiver.
type methodDecl struct {
	name, recv string
	ptr        bool
}

// expr is the method expression generated code calls: (*T).M or T.M.
func (m methodDecl) expr() string {
	if m.ptr {
		return "(*" + m.recv + ")." + m.name
	}
	return m.recv + "." + m.name
}

// method finds the method named name whose doc comment holds the directive
// on line; nil when the annotated function is not a method.
func (d *declIndex) method(file, name string, line int) (*methodDecl, error) {
	f, err := d.parse(file)
	if err != nil {
		return nil, err
	}
	for _, decl := range f.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if !ok || fn.Recv == nil || fn.Name.Name != name || fn.Doc == nil || len(fn.Recv.List) == 0 {
			continue
		}
		if line < d.fset.Position(fn.Doc.Pos()).Line || line > d.fset.Position(fn.Doc.End()).Line {
			continue
		}
		t := fn.Recv.List[0].Type
		m := &methodDecl{name: name}
		if star, ok := t.(*ast.StarExpr); ok {
			m.ptr, t = true, star.X
		}
		id, ok := t.(*ast.Ident)
		if !ok {
			return nil, fmt.Errorf("the receiver of %s is generic — annotated methods need a plain (non-generic) receiver type", name)
		}
		m.recv = id.Name
		return m, nil
	}
	return nil, nil
}

// typeDirectiveKeywords are the //@ directives read from type doc comments:
// //@controller and the modifiers it shares with every action. Other nexus
// keywords found there are passed on so the generator can reject them.
var typeDirectiveKeywords = map[string]bool{"controller": true, "auth": true, "session": true, "use": true}

// typeSites returns the //@ directives on the type declarations of the given
// package directories, as type-level sites.
func (d *declIndex) typeSites(dirs map[string]bool, res *selectorResolver) ([]handlergen.Site, error) {
	sorted := make([]string, 0, len(dirs))
	for dir := range dirs {
		sorted = append(sorted, dir)
	}
	sort.Strings(sorted)
	var out []handlergen.Site
	for _, dir := range sorted {
		entries, err := os.ReadDir(dir)
		if err != nil {
			return nil, err
		}
		for _, e := range entries {
			name := e.Name()
			if e.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") ||
				strings.HasSuffix(name, "_gen.go") || strings.HasPrefix(name, ".") || strings.HasPrefix(name, "_") {
				continue
			}
			file := filepath.Join(dir, name)
			f, err := d.parse(file)
			if err != nil {
				continue // the build reports unparseable files
			}
			for _, decl := range f.Decls {
				gd, ok := decl.(*ast.GenDecl)
				if !ok || gd.Tok != token.TYPE {
					continue
				}
				for _, spec := range gd.Specs {
					ts := spec.(*ast.TypeSpec)
					doc := ts.Doc
					if doc == nil && len(gd.Specs) == 1 {
						doc = gd.Doc
					}
					if doc == nil {
						continue
					}
					for _, c := range doc.List {
						// Like the function scan: gofmt rewrites //@x in a doc
						// comment as // @x, and both forms are directives.
						text, ok := strings.CutPrefix(strings.TrimSpace(strings.TrimLeft(c.Text, "/")), "@")
						if !ok {
							continue
						}
						fields := strings.Fields(text)
						if len(fields) == 0 || (!typeDirectiveKeywords[fields[0]] && !builtinHandlerKeyword(fields[0])) {
							continue
						}
						line := d.fset.Position(c.Pos()).Line
						site := handlergen.Site{
							Dir: dir, Pkg: f.Name.Name, File: displayRel(file), Func: ts.Name.Name,
							Keyword: fields[0], Args: fields[1:], Line: line, TypeLevel: true,
						}
						if site.Keyword == "use" {
							imps, err := resolveUseImports(res, file, site.Args)
							if err != nil {
								return nil, fmt.Errorf("%s:%d: //@use on %s: %w", displayRel(file), line, ts.Name.Name, err)
							}
							site.Imports = imps
						}
						out = append(out, site)
					}
				}
			}
		}
	}
	return out, nil
}

// displayRel shows a path relative to the cwd when it sits beneath it (how go
// prints positions), else unchanged.
func displayRel(path string) string {
	if cwd, err := os.Getwd(); err == nil {
		if rel, err := filepath.Rel(cwd, path); err == nil && !strings.HasPrefix(rel, "..") {
			return rel
		}
	}
	return path
}

// nearHandlerKeyword reports whether an unknown keyword is close enough to a
// nexus handler keyword to be a probable typo: same word ignoring case, or —
// with the same first letter, since typos rarely change it — within one edit
// (two for longer words). Distant keywords (or same-distance words starting
// differently, like //@test vs rest) belong to other tools and are ignored,
// so the strictness never breaks coexistence.
func nearHandlerKeyword(kw string) (want string, close bool) {
	lower := strings.ToLower(kw)
	best, bestDist := "", 3
	for _, k := range handlerKeywords {
		if lower == k {
			return k, true // case typo, e.g. //@Rest
		}
		if lower == "" || lower[0] != k[0] {
			continue
		}
		limit := 1
		if len(k) >= 5 {
			limit = 2
		}
		if d := editDistance(lower, k); d <= limit && d < bestDist {
			best, bestDist = k, d
		}
	}
	return best, best != ""
}

// editDistance is the Levenshtein distance between two short ASCII words.
func editDistance(a, b string) int {
	prev := make([]int, len(b)+1)
	for j := range prev {
		prev[j] = j
	}
	for i := 1; i <= len(a); i++ {
		cur := make([]int, len(b)+1)
		cur[0] = i
		for j := 1; j <= len(b); j++ {
			cost := 1
			if a[i-1] == b[j-1] {
				cost = 0
			}
			cur[j] = min(prev[j]+1, cur[j-1]+1, prev[j-1]+cost)
		}
		prev = cur
	}
	return prev[len(b)]
}

// handlerKeywordSet is handlerKeywords as a set for O(1) membership.
var handlerKeywordSet = func() map[string]bool {
	m := make(map[string]bool, len(handlerKeywords))
	for _, k := range handlerKeywords {
		m[k] = true
	}
	return m
}()

func builtinHandlerKeyword(kw string) bool { return handlerKeywordSet[kw] }

// selectorResolver maps a package selector from a qualified //@pkg.Func
// decorator (e.g. "inertia") to the import line the generated file should carry,
// so the emitted pkg.Func(...) call compiles. It never edits the user's source:
// the import lands only in the generated nexus_handlers_gen.go.
//
// Resolution is a cascade, cheapest/most-authoritative first (see resolve). All
// layers are cached; the module import graph (the costly one) is built lazily
// and at most once per scan, only when the cheap layers miss.
type selectorResolver struct {
	root string

	fileCache map[string]map[string]string // file -> selector -> import line
	dirCache  map[string]map[string]string // package dir -> merged selector -> import line
	declCache map[string]map[string]bool   // package dir -> top-level declared names
	hints     map[string]string            // [decorators.imports] from nexus.toml
}

func newSelectorResolver(root string) *selectorResolver {
	return &selectorResolver{
		root:      root,
		fileCache: map[string]map[string]string{},
		dirCache:  map[string]map[string]string{},
		declCache: map[string]map[string]bool{},
		hints:     loadDecoratorHints(root),
	}
}

// resolve returns the import line for selector sel as referenced from file.
func (r *selectorResolver) resolve(file, sel string) (string, error) {
	// Layer 1 — the annotated file's own imports (honors aliases + blank opt-in).
	if line, ok := r.fileImports(file)[sel]; ok {
		return line, nil
	}
	// Layer 2 — any sibling file in the same package (e.g. module.go).
	if line, ok := r.dirImports(filepath.Dir(file))[sel]; ok {
		return line, nil
	}
	// Layer 4 — explicit nexus.toml [decorators.imports] override.
	if path, ok := r.hints[sel]; ok {
		return importLineFor(sel, path), nil
	}
	// Layer 3 — the module import graph, matched on real package name. It's
	// cached across scans (see pkgIndex); a selector that isn't in the cached
	// copy earns one rebuild, since a dependency added mid-session is exactly
	// what a miss looks like. The main module's own packages outrank
	// dependencies: `utils` means the project's utils even when gorm and two
	// other deps ship a package by that name — only a tie *inside* the module
	// (or between foreign packages with no local candidate) is ambiguous.
	graph, local, err := pkgs.moduleGraph(r.root, false)
	if err == nil && len(graph[sel]) == 0 {
		graph, local, err = pkgs.moduleGraph(r.root, true)
	}
	if err != nil {
		return "", fmt.Errorf("package %q is not imported here and the module graph could not be read (%v) — import it or set [decorators.imports].%s in nexus.toml", sel, err, sel)
	}
	if paths := local[sel]; len(paths) == 1 {
		return importLineFor(sel, paths[0]), nil
	} else if len(paths) > 1 {
		sort.Strings(paths)
		return "", fmt.Errorf("package %q is ambiguous across %s — import it explicitly or set [decorators.imports].%s in nexus.toml", sel, strings.Join(paths, ", "), sel)
	}
	switch paths := graph[sel]; len(paths) {
	case 1:
		return importLineFor(sel, paths[0]), nil
	case 0:
		return "", fmt.Errorf("package %q is not a dependency — import it, run `go get`, or set [decorators.imports].%s in nexus.toml", sel, sel)
	default:
		sort.Strings(paths)
		return "", fmt.Errorf("package %q is ambiguous across %s — import it explicitly or set [decorators.imports].%s in nexus.toml", sel, strings.Join(paths, ", "), sel)
	}
}

// fileImports returns (cached) the selector->import map for a single file.
func (r *selectorResolver) fileImports(file string) map[string]string {
	if m, ok := r.fileCache[file]; ok {
		return m
	}
	m, err := importsOfFile(file)
	if err != nil || m == nil {
		m = map[string]string{}
	}
	r.fileCache[file] = m
	return m
}

// dirImports returns (cached) the merged selector->import map for every .go file
// in a package directory, so an import in any sibling file resolves.
// packageDecls returns the top-level declared names (vars, consts, types,
// plain funcs) of the non-test package files in dir, cached. A //@use
// expression identifier that names one of them is a package-level VALUE, not a
// package selector: it must not be import-resolved — a synthesized import
// would either collide with the declaration in the generated file or, worse,
// miss into the module graph and force a rebuild on every scan.
func (r *selectorResolver) packageDecls(dir string) map[string]bool {
	if m, ok := r.declCache[dir]; ok {
		return m
	}
	decls := map[string]bool{}
	entries, _ := os.ReadDir(dir)
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") || strings.HasSuffix(e.Name(), "_test.go") {
			continue
		}
		// Best-effort: a file mid-edit that doesn't parse contributes nothing.
		f, err := parser.ParseFile(token.NewFileSet(), filepath.Join(dir, e.Name()), nil, parser.SkipObjectResolution)
		if err != nil || f == nil {
			continue
		}
		for _, d := range f.Decls {
			switch d := d.(type) {
			case *ast.FuncDecl:
				if d.Recv == nil && d.Name != nil {
					decls[d.Name.Name] = true
				}
			case *ast.GenDecl:
				for _, spec := range d.Specs {
					switch s := spec.(type) {
					case *ast.ValueSpec:
						for _, n := range s.Names {
							decls[n.Name] = true
						}
					case *ast.TypeSpec:
						decls[s.Name.Name] = true
					}
				}
			}
		}
	}
	r.declCache[dir] = decls
	return decls
}

func (r *selectorResolver) dirImports(dir string) map[string]string {
	if m, ok := r.dirCache[dir]; ok {
		return m
	}
	merged := map[string]string{}
	entries, _ := os.ReadDir(dir)
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") {
			continue
		}
		for sel, line := range r.fileImports(filepath.Join(dir, e.Name())) {
			if _, ok := merged[sel]; !ok {
				merged[sel] = line
			}
		}
	}
	r.dirCache[dir] = merged
	return merged
}

// importLineFor builds the import line so the generated file's `sel.Func(...)`
// call binds: a plain import when the path's last segment already is sel,
// otherwise an explicit alias.
func importLineFor(sel, path string) string {
	if pathTail(path) == sel {
		return strconv.Quote(path)
	}
	return sel + " " + strconv.Quote(path)
}

func pathTail(path string) string { return path[strings.LastIndexByte(path, '/')+1:] }

// loadDecoratorHints reads the optional [decorators.imports] table from the
// project's nexus.toml (selector -> import path). Absent/unparsable -> nil.
func loadDecoratorHints(root string) map[string]string {
	dir := root
	if fi, err := os.Stat(root); err == nil && !fi.IsDir() {
		dir = filepath.Dir(root)
	}
	b, err := os.ReadFile(filepath.Join(dir, "nexus.toml"))
	if err != nil {
		return nil
	}
	var cfg struct {
		Decorators struct {
			Imports map[string]string `toml:"imports"`
		} `toml:"decorators"`
	}
	if err := toml.Unmarshal(b, &cfg); err != nil {
		return nil
	}
	return cfg.Decorators.Imports
}

// resolveUseImports returns the import lines a //@use expression needs, by
// matching the package selectors in the expression against the annotated file's
// own import block. Selectors that aren't imported packages (a local var or
// type referenced in the expression) are left out — they resolve in the
// generated file's own package.
func resolveUseImports(res *selectorResolver, file string, exprArgs []string) ([]string, error) {
	expr := strings.Join(exprArgs, " ")
	e, err := parser.ParseExpr(expr)
	if err != nil {
		return nil, fmt.Errorf("parse expression %q: %w", expr, err)
	}
	seen := map[string]bool{}
	var lines []string
	decls := res.packageDecls(filepath.Dir(file))
	ast.Inspect(e, func(n ast.Node) bool {
		if sel, ok := n.(*ast.SelectorExpr); ok {
			if id, ok := sel.X.(*ast.Ident); ok {
				if decls[id.Name] {
					return true // a package-level value of the annotated package, not a package
				}
				// The full cascade (file imports, siblings, nexus.toml hints,
				// module graph with the module-local tie-break) — so
				// `//@use utils.Wrap(...)` needs no import anywhere. A miss is
				// tolerated: the identifier may be a package-level value of the
				// annotated package (cfg.Timeout), not a package selector; a
				// wrong guess can't misbehave silently, since an import that
				// collides with a package-level name fails the overlay compile.
				line, err := res.resolve(file, id.Name)
				if err == nil && !seen[line] {
					seen[line] = true
					lines = append(lines, line)
				}
			}
		}
		return true
	})
	return lines, nil
}

// importsOfFile parses file's import block into selector -> import line
// (`"path"` or `alias "path"`). Dot imports are skipped. A blank import
// (`_ "path"`) is recorded under its path-tail selector as a PLAIN import: it's
// a codegen opt-in for a file that doesn't otherwise use the package (a normal
// import there would be "imported and not used"), and the generated file does
// reference the package, so it needs a real, non-blank import.
func importsOfFile(file string) (map[string]string, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, file, nil, parser.ImportsOnly)
	if err != nil {
		return nil, err
	}
	out := map[string]string{}
	for _, spec := range f.Imports {
		path, err := strconv.Unquote(spec.Path.Value)
		if err != nil {
			continue
		}
		sel := pathTail(path)
		line := strconv.Quote(path)
		if spec.Name != nil {
			n := spec.Name.Name
			switch n {
			case ".":
				continue // dot import: no usable selector
			case "_":
				// keep the path-tail selector + plain import line above
			default:
				sel = n
				line = n + " " + strconv.Quote(path)
			}
		}
		out[sel] = line
	}
	return out, nil
}

// buildHandlerOverlay scans root, generates the registration files, and writes
// them to a temp dir as a `go build -overlay` JSON — so `nexus dev` injects the
// decorator-form registrations WITHOUT writing anything into the source tree
// (zero churn). The overlay's keys are the absolute paths the committed files
// would occupy, so an existing committed file is transparently shadowed.
//
// Returns ("", noop, nil) when no annotations are found. cleanup removes the
// temp dir; callers must invoke it once the build that consumes the overlay has
// finished.
func buildHandlerOverlay(root string) (overlayPath string, cleanup func(), err error) {
	return buildOverlay(root, "", true)
}

// buildDevOverlay is buildHandlerOverlay plus, when distStubRoot is non-empty,
// the frontend-bundle stubs described in distStubReplacements. Go takes a
// single -overlay file, so the two contributions have to share one document.
//
// Only `nexus dev` passes a distStubRoot: `nexus build` produces the real
// binary and must embed the real bundle.
//
// nexus dev keeps views out of the overlay: its generator writes them to
// disk, where gopls reads them too.
func buildDevOverlay(root, distStubRoot string) (overlayPath string, cleanup func(), err error) {
	return buildOverlay(root, distStubRoot, false)
}

// buildOverlay assembles the overlay: handler registrations, the dist stubs
// (dev), and, with views, the compiled .templ views (nexus build) — so a
// fresh clone builds without generated files in the tree.
func buildOverlay(root, distStubRoot string, views bool) (overlayPath string, cleanup func(), err error) {
	noop := func() {}
	results, err := allHandlerArtifacts(root, handlerGenFileName)
	if err != nil {
		return "", noop, err
	}
	var plan *viewgen.Plan
	if views && viewgen.HasTemplates(root) {
		if plan, err = viewgen.Generate(root); err != nil {
			return "", noop, fmt.Errorf("views: %w", err)
		}
	}
	if len(results) == 0 && distStubRoot == "" && plan == nil {
		return "", noop, nil
	}

	tmp, err := os.MkdirTemp("", "nexus-handlers-overlay-")
	if err != nil {
		return "", noop, err
	}
	cleanup = func() { _ = os.RemoveAll(tmp) }

	replace := make(map[string]string, len(results))
	for i, r := range results {
		shadow := filepath.Join(tmp, fmt.Sprintf("%d_%s", i, filepath.Base(r.Path)))
		if err := os.WriteFile(shadow, r.Content, 0o644); err != nil {
			cleanup()
			return "", noop, err
		}
		replace[r.Path] = shadow
	}

	if plan != nil {
		i := len(results)
		for path, content := range plan.Files {
			shadow := filepath.Join(tmp, fmt.Sprintf("%d_%s", i, filepath.Base(path)))
			i++
			if err := os.WriteFile(shadow, content, 0o644); err != nil {
				cleanup()
				return "", noop, err
			}
			replace[path] = shadow
		}
		for _, path := range plan.Remove {
			if _, err := os.Stat(path); err == nil {
				replace[path] = ""
			}
		}
	}

	stubs, err := distStubReplacements(distStubRoot, tmp)
	if err != nil {
		cleanup()
		return "", noop, err
	}
	for path, shadow := range stubs {
		// Handler artifacts win: they're .go files, the stubs are assets, so
		// a collision shouldn't happen — but a generated file silently
		// replaced by an empty stub would be baffling to debug.
		if _, taken := replace[path]; !taken {
			replace[path] = shadow
		}
	}
	if len(replace) == 0 {
		cleanup()
		return "", noop, nil
	}

	overlayPath = filepath.Join(tmp, "overlay.json")
	doc := struct{ Replace map[string]string }{Replace: replace}
	data, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		cleanup()
		return "", noop, err
	}
	if err := os.WriteFile(overlayPath, data, 0o644); err != nil {
		cleanup()
		return "", noop, err
	}
	return overlayPath, cleanup, nil
}
