package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/spf13/cobra"

	"github.com/paulmanoni/nexus/orm"
)

// The ORM's migration commands run the app as their tool: built with the
// generated code nexus build overlays, an init that serves orm.ServeCLI
// before main, and imports of its migrations packages, then run with the
// request in orm.CLIEnv.

func newMigrateCmd(stdout, stderr io.Writer) *cobra.Command {
	var root, db string
	cmd := &cobra.Command{
		Use:   "migrate [target]",
		Short: "Apply the ORM's migrations, or take a database back to one",
		Long: `Apply the ORM's migrations: every database's pending ones, each after its
dependencies, as orm.Migrate does at boot.

With a target (a migration's name or its number), take one database (--db,
default the default database) to it: the migrations up to it applied, those
after it unapplied, last first, by their operations' reverses. "zero"
unapplies them all. The databases are nexus.toml's [databases] blocks.

nexus migrate v2 is the v1 → v2 codemod (see nexus migrate v2 --help).`,
		Args: cobra.MaximumNArgs(1),
		RunE: func(_ *cobra.Command, args []string) error {
			req := orm.CLIRequest{Command: "migrate"}
			if len(args) == 1 {
				req.Target = args[0]
			}
			return runMigrationCommand(root, db, req, stdout, stderr)
		},
	}
	cmd.Flags().StringVar(&root, "root", ".", "project directory")
	cmd.Flags().StringVar(&db, "db", "", "the [databases.<db>] block a target is of (default: the default database)")
	cmd.AddCommand(newMigrateV2Cmd(stdout, stderr))
	return cmd
}

func newShowMigrationsCmd(stdout, stderr io.Writer) *cobra.Command {
	var root string
	cmd := &cobra.Command{
		Use:   "showmigrations",
		Short: "List each database's migrations: [X] applied, [ ] not",
		Args:  cobra.NoArgs,
		RunE: func(*cobra.Command, []string) error {
			return runMigrationCommand(root, "", orm.CLIRequest{Command: "show"}, stdout, stderr)
		},
	}
	cmd.Flags().StringVar(&root, "root", ".", "project directory")
	return cmd
}

func newSQLMigrateCmd(stdout, stderr io.Writer) *cobra.Command {
	var root, db, dialect string
	var backwards bool
	cmd := &cobra.Command{
		Use:   "sqlmigrate <name>",
		Short: "Print the SQL a migration runs",
		Long: `Print the SQL a migration (its name, or its number) runs on its database's
dialect (the [databases.<db>] block's driver, or --dialect), or with
--backwards the SQL unapplying it. Go code (a RunGo) is marked, not shown.`,
		Args: cobra.ExactArgs(1),
		RunE: func(_ *cobra.Command, args []string) error {
			r := findModuleRoot(root)
			if r == "" {
				return fmt.Errorf("no go.mod at or above %s", root)
			}
			target, err := migrationTarget(r, db, dialect)
			if err != nil {
				return err
			}
			req := orm.CLIRequest{Command: "sql", DB: target.ormName(), Dialect: target.driver, Target: args[0], Backwards: backwards}
			return runORMTool(r, req, nil, stdout, stderr, nil)
		},
	}
	cmd.Flags().StringVar(&root, "root", ".", "project directory")
	cmd.Flags().StringVar(&db, "db", "", "the [databases.<db>] block (default: the default database)")
	cmd.Flags().StringVar(&dialect, "dialect", "", "postgres | mysql | sqlite (default: the block's driver)")
	cmd.Flags().BoolVar(&backwards, "backwards", false, "the SQL unapplying the migration")
	return cmd
}

// runMigrationCommand runs a command that connects to the databases.
func runMigrationCommand(root, db string, req orm.CLIRequest, stdout, stderr io.Writer) error {
	r := findModuleRoot(root)
	if r == "" {
		return fmt.Errorf("no go.mod at or above %s", root)
	}
	_, def, err := databaseBlocks(r)
	if err != nil {
		return err
	}
	if db != def {
		req.DB = db
	}
	c, err := conns(r)
	if err != nil {
		return err
	}
	req.Conns = c
	return runORMTool(r, req, os.Stdin, stdout, stderr, nil)
}

// toolFileName is the tool's file in the main package: an init that, with
// orm.CLIEnv set, does what it asks and exits before main. Named to sort
// first, so its init runs before the app's own.
const toolFileName = "0_nexus_orm_tool.go"

// toolFile is the tool's source: orm.ServeCLI, and imports of the
// migrations packages so their migrations register.
func toolFile(imports []string) []byte {
	var b strings.Builder
	b.WriteString("// Code generated by the nexus CLI; DO NOT EDIT.\n\npackage main\n\nimport (\n\tnexusorm \"github.com/paulmanoni/nexus/orm\"\n")
	for _, p := range imports {
		b.WriteString("\t_ " + strconv.Quote(p) + "\n")
	}
	b.WriteString(")\n\nfunc init() { nexusorm.ServeCLI() }\n")
	return []byte(b.String())
}

// migrationsImports is the import paths of the app's migrations packages:
// migrations and the directories in it, those holding Go files.
func migrationsImports(root string) ([]string, error) {
	dirs := []string{filepath.Join(root, "migrations")}
	if entries, err := os.ReadDir(dirs[0]); err == nil {
		for _, e := range entries {
			if e.IsDir() {
				dirs = append(dirs, filepath.Join(dirs[0], e.Name()))
			}
		}
	}
	var out []string
	for _, dir := range dirs {
		entries, err := os.ReadDir(dir)
		if err != nil {
			continue
		}
		hasGo := false
		for _, e := range entries {
			hasGo = hasGo || strings.HasSuffix(e.Name(), ".go") && !strings.HasSuffix(e.Name(), "_test.go")
		}
		if !hasGo {
			continue
		}
		ip, err := pkgs.importPath(root, dir)
		if err != nil {
			return nil, err
		}
		out = append(out, ip)
	}
	sort.Strings(out)
	return out, nil
}

// runORMTool builds the app as the ORM's tool and runs it for req: its
// output to stdout and stderr, questions read from stdin, and plan's
// result into res.
func runORMTool(root string, req orm.CLIRequest, stdin io.Reader, stdout, stderr io.Writer, res *orm.PlanResult) error {
	mainDir, err := pkgs.mainDir(root)
	if err != nil {
		return err
	}
	if mainDir == "" {
		return errors.New("no main package: the migration tool runs the app, so it needs one")
	}
	tmp, err := os.MkdirTemp("", "nexus-orm-tool-")
	if err != nil {
		return err
	}
	defer os.RemoveAll(tmp)

	overlay, cleanup, err := buildOverlay(root, "", true, false)
	if err != nil {
		return err
	}
	defer cleanup()
	doc := struct{ Replace map[string]string }{Replace: map[string]string{}}
	if overlay != "" {
		raw, err := os.ReadFile(overlay)
		if err != nil {
			return err
		}
		if err := json.Unmarshal(raw, &doc); err != nil {
			return err
		}
	}
	imports, err := migrationsImports(root)
	if err != nil {
		return err
	}
	shadow := filepath.Join(tmp, toolFileName)
	if err := os.WriteFile(shadow, toolFile(imports), 0o644); err != nil {
		return err
	}
	doc.Replace[filepath.Join(mainDir, toolFileName)] = shadow
	overlayPath := filepath.Join(tmp, "overlay.json")
	raw, _ := json.Marshal(doc)
	if err := os.WriteFile(overlayPath, raw, 0o644); err != nil {
		return err
	}

	bin := filepath.Join(tmp, "tool")
	build := exec.Command("go", "build", "-overlay", overlayPath, "-o", bin, ".")
	build.Dir = mainDir
	build.Stdout, build.Stderr = stderr, stderr
	if err := build.Run(); err != nil {
		return fmt.Errorf("building the app as the migration tool: %w", err)
	}
	if res != nil {
		req.Out = filepath.Join(tmp, "plan.json")
	}
	reqJSON, _ := json.Marshal(req)
	run := exec.Command(bin)
	run.Dir = root
	run.Env = append(os.Environ(), orm.CLIEnv+"="+string(reqJSON))
	run.Stdin, run.Stdout, run.Stderr = stdin, stdout, stderr
	if err := run.Run(); err != nil {
		return fmt.Errorf("running the migration tool: %w", err)
	}
	if res == nil {
		return nil
	}
	out, err := os.ReadFile(req.Out)
	if err != nil {
		return fmt.Errorf("the tool wrote no plan (does the app's main package link the orm?): %w", err)
	}
	return json.Unmarshal(out, res)
}
