// Auto-generated by the nexus frontend extension — DO NOT EDIT.
// Role: per-op typed exports.
// Regenerate with: nexus generate

import { client } from './_client'
import type * as T from './types'
import type { NexusOpts } from './_client'

export { client, NexusClient, NexusError, memoryTokenStore, localStorageTokenStore } from './_client'
export type { NexusOpts, TokenStore } from './_client'

export const deletePetsById = (vars?: idArg, opts?: NexusOpts) =>
  client.rest<{}>('DELETE', '/pets/:id', vars, opts)

export const me = (vars?: Record<string, never>, opts?: NexusOpts) =>
  client.rest<T.User>('GET', '/me', vars, opts)

export const getPets = (vars?: T.ListOptions, opts?: NexusOpts) =>
  client.rest<T.PageOfPet>('GET', '/pets', vars, opts)

export const getPetsById = (vars?: idArg, opts?: NexusOpts) =>
  client.rest<T.Pet | undefined>('GET', '/pets/:id', vars, opts)

export const patchPetsById = (vars?: T.Pet, opts?: NexusOpts) =>
  client.rest<T.Pet | undefined>('PATCH', '/pets/:id', vars, opts)

export const login = (vars?: T.Credentials, opts?: NexusOpts) =>
  client.rest<T.LoginResp>('POST', '/login', vars, opts)

export const logout = (vars?: Record<string, never>, opts?: NexusOpts) =>
  client.rest<void>('POST', '/logout', vars, opts)

export const postPets = (vars?: T.Pet, opts?: NexusOpts) =>
  client.rest<T.Pet | undefined>('POST', '/pets', vars, opts)

