// Auto-generated by the nexus frontend extension — DO NOT EDIT.
// Role: Vue 3 composables.
// Regenerate with: nexus generate

import { ref, toValue, watch, type MaybeRefOrGetter, type Ref } from 'vue'
import { client, NexusError } from './_client'
import type * as T from './types'

interface QueryState<R> {
  data: Ref<R | undefined>
  loading: Ref<boolean>
  error: Ref<NexusError | undefined>
  refresh: () => Promise<void>
}

interface MutationState<V, R> {
  data: Ref<R | undefined>
  loading: Ref<boolean>
  error: Ref<NexusError | undefined>
  mutate: (vars: V) => Promise<R>
}

