package orm_test

import (
	"context"
	"math"
	"slices"
	"strings"
	"testing"

	"github.com/paulmanoni/nexus/v2"
	"github.com/paulmanoni/nexus/v2/config"
	"github.com/paulmanoni/nexus/v2/db"

	"github.com/paulmanoni/nexus/orm"
	"github.com/paulmanoni/nexus/orm/ormtest"
)

type Doc struct {
	ID        int64
	Title     string
	Body      string
	Search    orm.TSVector `orm:"generated"`
	Embedding orm.Vector   `orm:"vector:3"`
	Score     float64      `orm:"computed"`
}

func (Doc) Generated() map[string]orm.Expr {
	return map[string]orm.Expr{"Search": orm.SearchVector("title").Weight("A").Add(orm.SearchVector("body").Weight("B")).Config("english")}
}

func (Doc) Indexes() []orm.Index {
	return []orm.Index{
		orm.GinIndex("search"),
		orm.HnswIndex("embedding").Ops(orm.Cosine),
	}
}

var Docs = orm.For[Doc]()

func docOpen(t *testing.T) []Doc {
	t.Helper()
	ctx := ormtest.Open(t, Docs)
	ormtest.Seed(t, ctx, Docs,
		&Doc{Title: "Go web servers", Body: "net/http and routing", Embedding: orm.Vector{1, 0, 0}},
		&Doc{Title: "Rust in practice", Body: "a web server in Rust", Embedding: orm.Vector{0, 1, 0}},
		&Doc{Title: "Java streams", Body: "collections, not the web", Embedding: orm.Vector{0.9, 0.1, 0}},
		&Doc{Title: "Gardening", Body: "tomatoes", Embedding: orm.Vector{0, 0, 1}})
	docs, err := Docs.OrderBy("id").All(ctx)
	if err != nil {
		t.Fatal(err)
	}
	return docs
}

func docTitles(ds []Doc) []string {
	out := make([]string, len(ds))
	for i, d := range ds {
		out[i] = d.Title
	}
	return out
}

func TestTextSearch(t *testing.T) {
	ctx := ormtest.Open(t, Docs)
	ormtest.Seed(t, ctx, Docs,
		&Doc{Title: "Go web servers", Body: "net/http and routing"},
		&Doc{Title: "Rust in practice", Body: "a web server in Rust"},
		&Doc{Title: "Java streams", Body: "collections, not the web"},
		&Doc{Title: "Gardening", Body: "tomatoes"})
	all, err := Docs.OrderBy("id").All(ctx)
	if err != nil || all[1].Search != "Rust in practice a web server in Rust" {
		t.Fatalf("the generated column: %q, %v", all[1].Search, err)
	}
	for _, c := range []struct {
		q    orm.Cond
		want []string
	}{
		{orm.Q{"search__search": "web -java"}, []string{"Go web servers", "Rust in practice"}},
		{orm.Q{"title__search": `"in practice" or tomatoes`}, []string{"Rust in practice", "Gardening"}},
		{orm.Match(orm.SearchVector("title", "body"), orm.SearchQuery("server rust")), []string{"Rust in practice"}},
		{orm.Q{"title__trigram_similar": "gardenin"}, []string{"Gardening"}},
	} {
		got, err := Docs.Filter(c.q).OrderBy("id").All(ctx)
		if err != nil || !slices.Equal(docTitles(got), c.want) {
			t.Errorf("%v: %v, %v", c.q, docTitles(got), err)
		}
	}
	doc := orm.SearchVector("title").Weight("A").Add(orm.SearchVector("body").Weight("B"))
	q := orm.SearchQuery("web")
	ranked, err := Docs.Filter(orm.Match(doc, q)).Annotate("score", orm.SearchRank(doc, q)).OrderBy("-score", "id").All(ctx)
	if err != nil || !slices.Equal(docTitles(ranked), []string{"Go web servers", "Rust in practice", "Java streams"}) || ranked[0].Score <= ranked[1].Score {
		t.Fatalf("ranked %v %v, %v", docTitles(ranked), ranked, err)
	}
	heads, err := Docs.Filter(orm.Q{"id": 3}).Annotate("head", orm.Headline("body", orm.SearchQuery("web"))).Values[string]("head").All(ctx)
	if err != nil || !slices.Equal(heads, []string{"collections, not the web"}) {
		t.Fatalf("headline %v, %v", heads, err)
	}
	sim, err := Docs.Filter(orm.Q{"id": 4}).Annotate("sim", orm.Similarity("title", "gardenin")).Values[float64]("sim").All(ctx)
	if err != nil || sim[0] < 0.5 || sim[0] >= 1 {
		t.Fatalf("similarity %v, %v", sim, err)
	}
	if _, err := Docs.Filter(orm.Q{"id": 1}).Update(ctx, orm.Set{"search": "x"}); err == nil || !strings.Contains(err.Error(), "generated by the database") {
		t.Fatalf("wrote a generated column: %v", err)
	}
}

func TestVectorSearch(t *testing.T) {
	docs := docOpen(t)
	if !slices.Equal(docs[2].Embedding, orm.Vector{0.9, 0.1, 0}) {
		t.Fatalf("read %v", docs[2].Embedding)
	}
	ctx := ormtest.Open(t, Docs)
	for _, d := range docs {
		d.ID = 0
		if err := Docs.Create(ctx, &d); err != nil {
			t.Fatal(err)
		}
	}
	near, err := Docs.Nearest("embedding", orm.Vector{1, 0, 0}, orm.Cosine).Limit(3).All(ctx)
	if err != nil || !slices.Equal(docTitles(near), []string{"Go web servers", "Java streams", "Rust in practice"}) {
		t.Fatalf("nearest %v, %v", docTitles(near), err)
	}
	for _, c := range []struct {
		e    orm.Expr
		want float64
	}{
		{orm.L2Distance("embedding", orm.Vector{0, 1, 0}), math.Sqrt(2)},
		{orm.CosineDistance("embedding", orm.Vector{2, 0, 0}), 0},
		{orm.InnerProduct("embedding", orm.Vector{3, 0, 0}), -3},
	} {
		got, err := Docs.Filter(orm.Q{"title": "Go web servers"}).Annotate("d", c.e).Values[float64]("d").All(ctx)
		if err != nil || math.Abs(got[0]-c.want) > 1e-6 {
			t.Errorf("%v = %v, %v", c.e, got, err)
		}
	}
	q := orm.SearchQuery("web")
	doc := orm.SearchVector("title", "body")
	hybrid, err := Docs.Filter(orm.Match(doc, q)).
		Annotate("rank", orm.SearchRank(orm.SearchVector("title").Weight("A").Add(orm.SearchVector("body")), q)).
		Annotate("distance", orm.CosineDistance("embedding", orm.Vector{0, 1, 0})).
		Annotate("score", orm.Fuse("-rank", "distance")).OrderBy("-score", "id").All(ctx)
	if err != nil || !slices.Equal(docTitles(hybrid), []string{"Rust in practice", "Go web servers", "Java streams"}) {
		t.Fatalf("hybrid %v %v, %v", docTitles(hybrid), hybrid, err)
	}
}

var Vectors = orm.CreateExtension("vector")

func TestSearchCheck(t *testing.T) {
	_, stop, err := nexus.InProcess(config.Runtime{},
		db.Bind[mainDB]("main", func() db.Config { return db.Config{Driver: db.SQLite, Database: ":memory:", LogLevel: "silent"} }, db.WithDefault()),
		Vectors, orm.Schema{}.Check(Doc{}))
	if err != nil {
		t.Fatalf("SQLite searches unindexed: %v", err)
	}
	_ = stop(context.Background())
}
