// Auto-generated by the nexus client SDK as a one-time scaffold.
// Edit freely — re-running the dump will NOT overwrite this file
// once it exists. Delete it to regenerate from scratch.
//
// Optional barrel: re-exports every composable + shared types so
// the rest of the app imports from one place. Skipping this file
// and importing from './vue.js' directly is equally fine — the
// useNexus() singleton already reads Vite env vars
// (VITE_NEXUS_API, VITE_NEXUS_TOKEN) on first call.

export {
  useNexus,
  setNexus,
  useAuth,
  useQuery,
  useMutation,
  useGqlQuery,
  useGqlMutation,
  useCrud,
  useWS,
} from './vue.js'

// Re-export the discriminated maps so apps can write
//   const r: GraphqlOps['listPets']['return'] = …
export type {
  RestEndpoints,
  GraphqlOps,
  WSMessages,
} from './client.js'

// Manifest-derived named types — annotate locals via `import type`.
export type {
  Credentials,
  ListOptions,
  LoginResp,
  PageOfPet,
  Pet,
  User,
  idArg,
} from './client.js'
