// Code generated by 'nexus gen clients'; DO NOT EDIT.
// To regenerate, run: nexus gen clients ./...

package users

import (
	"context"

	"github.com/paulmanoni/nexus"
)

// UsersClient is the typed client surface for the "users" module.
// One method per AsRest handler in that module's declaration. The
// implementation is selected at construction time based on the running
// binary's deployment.
type UsersClient interface {
	Get(ctx context.Context, args GetArgs) (*User, error)
	List(ctx context.Context, args ListArgs) ([]*User, error)
}

// NewUsersClient returns the appropriate implementation for the
// running binary:
//   - In-process LocalInvoker when this binary owns the "users-svc"
//     deployment, OR when no deployment is set (monolith mode).
//   - HTTP RemoteCaller reading USERS_SVC_URL otherwise. The local
//     binary's version is threaded in so RemoteCaller can detect
//     peer-version skew on the first call (single warning line, no
//     fail-fast).
func NewUsersClient(app *nexus.App) UsersClient {
	if dep := app.Deployment(); dep == "" || dep == "users-svc" {
		return &usersClientLocal{inv: nexus.NewLocalInvoker(app)}
	}
	return &usersClientRemote{r: nexus.NewRemoteCallerFromEnv(
		"USERS_SVC_URL",
		nexus.WithLocalVersion(app.Version()),
	)}
}

type usersClientLocal struct{ inv *nexus.LocalInvoker }

func (c *usersClientLocal) Get(ctx context.Context, args GetArgs) (*User, error) {
	var out *User
	err := c.inv.Invoke(ctx, "GET", "/users/:id", args, &out)
	return out, err
}

func (c *usersClientLocal) List(ctx context.Context, args ListArgs) ([]*User, error) {
	var out []*User
	err := c.inv.Invoke(ctx, "GET", "/users", args, &out)
	return out, err
}

type usersClientRemote struct{ r *nexus.RemoteCaller }

func (c *usersClientRemote) Get(ctx context.Context, args GetArgs) (*User, error) {
	var out *User
	err := c.r.Call(ctx, "GET", "/users/:id", args, &out)
	return out, err
}

func (c *usersClientRemote) List(ctx context.Context, args ListArgs) ([]*User, error) {
	var out []*User
	err := c.r.Call(ctx, "GET", "/users", args, &out)
	return out, err
}
