// Code generated by "nexus generate handlers"; DO NOT EDIT.

package handlers

import (
	"github.com/paulmanoni/nexus"
	"github.com/paulmanoni/nexus/decorate"
	"github.com/paulmanoni/nexus/extension/auth"
	"github.com/paulmanoni/nexus/extension/inertia"
	"github.com/paulmanoni/nexus/extension/ratelimit"
	"time"
)

func init() {
	decorate.Register(nexus.Module("handlers",
		nexus.Provide(NewUsersService),
		nexus.AsRest("GET", "/users/:id", NewGetUser),
		nexus.AsQuery(NewListUsers),
		nexus.AsMutation(NewCreateUser, auth.Requires("ADMIN")),
		nexus.AsSubscription(NewUserEvents),
		nexus.AsWS("/events", "chat.send", NewChatSend, auth.Required()),
		nexus.AsRest("POST", "/throttled", NewThrottled, ratelimit.Per(time.Minute, 60)),
		nexus.AsWorker("reaper", NewReaper),
		inertia.Page("GET", "/dash", "Dashboard", NewDashboard, auth.Required()),
	))
}
