// Auto-generated by the nexus auth extension — DO NOT EDIT.
// Role: Vue 3 auth composable.
// Regenerate with: nexus generate frontend

import { ref, computed } from 'vue'
import { client, NexusError } from '../_client'
import { login as _login, logout as _logout, me as _me } from '../index'

// Walk common login-response shapes for the access token. Returns
// "" when no recognised field is present.
function extractToken(r: any): string {
  if (!r || typeof r !== 'object') return ''
  if (typeof r.token === 'string' && r.token) return r.token
  if (typeof r.accessToken === 'string' && r.accessToken) return r.accessToken
  if (r.data && typeof r.data === 'object') {
    if (typeof r.data.token === 'string' && r.data.token) return r.data.token
    if (typeof r.data.accessToken === 'string' && r.data.accessToken) return r.data.accessToken
  }
  return ''
}

// extractUser mirrors extractToken for the identity field — apps
// putting the user under data.user (envelope) get the same depth-2
// tolerance the token side has. Returns undefined when no user
// field is found so the caller can distinguish "no identity in
// response" from "identity was explicitly null/empty".
function extractUser(r: any): unknown {
  if (!r || typeof r !== 'object') return undefined
  if (r.user !== undefined) return r.user
  if (r.data && typeof r.data === 'object' && r.data.user !== undefined) return r.data.user
  return undefined
}

type Identity = unknown

const _identity = ref<Identity | null>(null)
const _loading = ref(false)
const _error = ref<NexusError | undefined>()

export function useAuth() {
  const identity = _identity
  const loading = _loading
  const error = _error
  const isAuthenticated = computed(() => identity.value !== null)

  async function login(creds: Parameters<typeof _login>[0]) {
    loading.value = true
    error.value = undefined
    try {
      const out: any = await _login(creds)
      const tok = extractToken(out)
      if (tok) client.tokens.set(tok)
      const usr = extractUser(out)
      if (usr !== undefined) identity.value = usr
      return out
    } catch (e) {
      error.value = e as NexusError
      throw e
    } finally {
      loading.value = false
    }
  }

  async function logout() {
    loading.value = true
    try {
      await _logout()
    } catch (e) {
      error.value = e as NexusError
    } finally {
      client.tokens.clear()
      identity.value = null
      loading.value = false
    }
  }

  async function bootstrap() {
    if (!client.tokens.get()) return
    loading.value = true
    try {
      identity.value = await _me() as Identity
    } catch {
      client.tokens.clear()
      identity.value = null
    } finally {
      loading.value = false
    }
  }

  return {
    identity, isAuthenticated, loading, error,
    login,
    logout,
    bootstrap,
  }
}
