// Auto-generated by the nexus client SDK — do not edit.
// Pairs with client.js. Re-emitted on every boot when Config.Client.OutDir is set.
// Schema version: client.v1
// Base path:      /api/v1

// ── Type definitions ─────────────────────────────────────────

export interface Owner {
  id: string
  pets: Pet[]
}

export interface Pet {
  id: string
  /** Display name */
  name: string
  age?: number
  tags: string[]
}

// ── REST endpoints (keyed by '<METHOD> <PATH>') ──────────────

export interface RestEndpoints {
  'GET /pets': { args: { limit?: number }; return: Pet[] }
  'POST /pets': { args: Pet; return: Pet }
}

// ── GraphQL ops (keyed by op name) ───────────────────────────

export interface GraphqlOps {
  listPets: { kind: 'query'; args: {}; return: Pet[] }
  createPet: { kind: 'mutation'; args: Pet; return: Pet }
}

// ── WebSocket message types (keyed by path → type) ──────────

export interface WSMessages {
  '/events': {
    'chat.send': { text: string }
    'chat.typing': {}
  }
}

// ── Typed runtime surface ────────────────────────────────────

// Helpers — extract the METHOD and PATH halves of a 'METHOD PATH' literal.
export type ExtractRestMethod<K> = K extends `${infer M} ${string}` ? M : never
export type ExtractRestPath<K>   = K extends `${string} ${infer P}` ? P : never

/** Throws on non-2xx responses; status + payload + endpoint surfaced. */
export class NexusError extends Error {
  status?: number
  code?: string
  payload?: unknown
  endpoint?: string
}

export interface TokenStore {
  get(): string | null
  set(token: string | null): void
  clear(): void
}

export function memoryTokenStore(): TokenStore
export function localStorageTokenStore(key?: string): TokenStore

export interface NexusClientOptions {
  origin?: string
  manifestPath?: string
  fetch?: typeof globalThis.fetch
  tokenStore?: TokenStore
  /**
   * Pre-fetched manifest. When set, the client skips the runtime
   * fetch of /__nexus/client/manifest.json — bundle the file via
   *   import manifest from '../sdk/manifest.json'
   * to drop all /__nexus/client/* traffic from the prod bundle and
   * eliminate cross-origin CORS issues entirely.
   */
  manifest?: unknown
}

export class NexusClient {
  constructor(opts?: NexusClientOptions)
  readonly auth: AuthNamespace

  /** Fetch + cache the manifest. */
  ready(): Promise<unknown>
  /** Force a manifest re-fetch (rare; use in dev hot-reload). */
  reload(): Promise<unknown>

  /** Typed REST call — completion picks key from RestEndpoints. */
  rest<K extends keyof RestEndpoints>(
    method: ExtractRestMethod<K>,
    path:   ExtractRestPath<K>,
    args?:  RestEndpoints[K]['args'],
    opts?:  { headers?: Record<string, string>; signal?: AbortSignal },
  ): Promise<RestEndpoints[K]['return']>
  /** Untyped escape hatch. */
  rest(method: string, path: string, args?: object, opts?: object): Promise<unknown>

  /** Typed GraphQL query. opts.select narrows the auto-expanded
   *  selection set AND narrows the response type — the await
   *  result reflects exactly what was selected. */
  query<
    K extends keyof GraphqlOps,
    const S extends
      | string
      | ReadonlyArray<GqlKeyOf<GraphqlOps[K]['return']>>
      | SelectionFor<GraphqlOps[K]['return']> = never,
  >(
    name: K, vars?: GraphqlOps[K]['args'],
    opts?: GqlCallOpts<GraphqlOps[K]['return'], S>,
  ): Promise<Selected<GraphqlOps[K]['return'], S>>
  /** Typed GraphQL mutation. Same options as query(). */
  mutate<
    K extends keyof GraphqlOps,
    const S extends
      | string
      | ReadonlyArray<GqlKeyOf<GraphqlOps[K]['return']>>
      | SelectionFor<GraphqlOps[K]['return']> = never,
  >(
    name: K, vars?: GraphqlOps[K]['args'],
    opts?: GqlCallOpts<GraphqlOps[K]['return'], S>,
  ): Promise<Selected<GraphqlOps[K]['return'], S>>

  /** CRUD handle for AsCRUD-registered entities. */
  crud(name: string): CrudHandle

  /** WebSocket handle — typed by path via WSMessages. */
  ws<P extends keyof WSMessages>(path: P): WSHandle<P>
}

/** Scalar leaves — no sub-selection possible on these in GraphQL. */
type GqlScalar = string | number | boolean | bigint | null | undefined

/** Top-level scalar field names of T (or T's array element). */
export type GqlKeyOf<T> =
  T extends ReadonlyArray<infer U> ? Extract<keyof U, string>
  : Extract<keyof T, string>

/** Selection shape for one field F of a parent type. */
type GqlField<F> =
  F extends GqlScalar ? boolean
  : F extends ReadonlyArray<infer U>
    ? (U extends object
        ? boolean | SelectionFor<U> | ReadonlyArray<Extract<keyof U, string>>
        : boolean)
    : F extends object
      ? boolean | SelectionFor<F> | ReadonlyArray<Extract<keyof F, string>>
      : boolean

/** Recursive selection-set tree shaped to mirror T. The IDE
 *  autocompletes T's field names; nested objects recurse the same
 *  way. true selects a leaf, an array shorthand lists scalar
 *  children of an object/array field. */
export type SelectionFor<T> =
  T extends GqlScalar ? never
  : T extends ReadonlyArray<infer U> ? SelectionFor<U>
  : T extends object ? { [K in keyof T]?: GqlField<T[K]> }
  : never

/** Internal: opts shape for nx.query / nx.mutate. Generic over both
 *  the return type T and the literal selection S so the response
 *  type narrows to exactly what was selected. */
export interface GqlCallOpts<T, S> {
  headers?: Record<string, string>
  signal?: AbortSignal
  /** Override the auto-expanded selection set. */
  select?: S & (
    | string
    | ReadonlyArray<GqlKeyOf<T>>
    | SelectionFor<T>
  )
}

/** Public alias kept for hand-built untyped calls. The two-generic
 *  GqlCallOpts is what the typed query/mutate signatures use. */
export type GqlCallOptions<T = unknown> = GqlCallOpts<T, unknown>

/** Computes the response shape after applying selection S to T.
 *
 *    no select / never        → T (full shape, auto-expanded server-side)
 *    string                   → T (passthrough; TS can't introspect a raw doc)
 *    readonly K[]             → Pick<T, K> (or array of Pick for list T)
 *    SelectionFor<T>          → recursive narrowed tree
 *
 *  null/undefined union members pass through at every level so
 *  optional fields (data?: LoginData) keep their optionality in the
 *  narrowed result instead of collapsing to {}.
 */
export type Selected<T, S> =
  [S] extends [never] ? T
  : S extends string ? T
  : T extends null | undefined ? T
  : SelectedCore<T, S>

type SelectedCore<T, S> =
  S extends readonly (infer F)[]
    ? T extends readonly (infer U)[]
      ? PickFields<NonNullable<U>, F>[]
      : PickFields<T, F>
  : S extends Record<string, unknown>
    ? T extends readonly (infer U)[]
      ? Selected<U, S>[]
      : PickObject<T, S>
  : T

type PickFields<T, F> = F extends keyof T ? Pick<T, F> : T

/** PickObject narrows T's fields to those present in S, recursing
 *  through Selected on each value so nested optional/union fields
 *  stay correctly typed. NonNullable is applied around T to defend
 *  against the keyof (X | undefined) = never collapse. */
type PickObject<T, S> = {
  [K in Extract<keyof S, keyof NonNullable<T>>]:
    S[K] extends true ? NonNullable<T>[K]
    : S[K] extends readonly (infer F)[]
      ? NonNullable<T>[K] extends readonly (infer U)[]
        ? PickFields<NonNullable<U>, F>[]
        : PickFields<NonNullable<T>[K], F>
    : S[K] extends Record<string, unknown>
      ? Selected<NonNullable<T>[K], S[K]>
      : NonNullable<T>[K]
}

/** Loose, untyped selection tree — used by hand-written documents
 *  and as the escape hatch when the return type is unknown. */
export interface GqlSelection {
  [field: string]: boolean | readonly string[] | GqlSelection
}

export interface CrudHandle {
  list(args?: object): Promise<unknown[]>
  get(id: string | number): Promise<unknown>
  create(body: object): Promise<unknown>
  update(id: string | number, body: object): Promise<unknown>
  delete(id: string | number): Promise<void>
}

export class WSHandle<P extends keyof WSMessages> {
  /** Register a per-message-type handler. */
  on<T extends keyof WSMessages[P]>(
    type: T, handler: (data: WSMessages[P][T], envelope: WSEnvelope) => void,
  ): this
  /** Wildcard handler — fires for every message regardless of type. */
  on(type: '*', handler: (data: unknown, envelope: WSEnvelope) => void): this
  /** Lifecycle hooks. */
  on(type: '@close' | '@error', handler: (e?: unknown) => void): this

  send<T extends keyof WSMessages[P]>(type: T, data: WSMessages[P][T]): this
  connect(): Promise<this>
  close(): void
  readonly socket: WebSocket | null
}

export interface WSEnvelope {
  type: string
  data: unknown
  timestamp?: number
}

export interface AuthNamespace {
  readonly token: string | null
  setToken(t: string): void
  clearToken(): void
  /** POSTs to the manifest's auth.loginPath; auto-stashes returned token. */
  login(creds: object): Promise<unknown>
  /** POSTs to auth.logoutPath (if declared); always clears local token. */
  logout(): Promise<void>
  /** GETs auth.mePath. */
  me(): Promise<unknown>
}

export default NexusClient
