package auth

import (
	"fmt"
	"strings"

	"github.com/paulmanoni/nexus"
	"github.com/paulmanoni/nexus/extension"
	"github.com/paulmanoni/nexus/registry"
)

// authContributor is auth's ClientContributor — emits framework-
// flavored TS that wraps the codegen-emitted login/logout/me typed
// functions in a stateful composable (Vue today; React/Svelte
// follow the same pattern). Lives next to auth.Module so contributor
// changes ride the same package's CI signal as the runtime behavior.
type authContributor struct{}

// NexusContribute walks the GenerateContext for endpoints tagged
// auth.flow and, when the consumer's framework selection makes sense,
// emits an auth-shaped composable file. The renderer has already
// produced typed `login` / `logout` / `me` functions in the parent
// index — this contributor only adds the reactive glue.
//
// Empty output is valid: an app that doesn't register any AuthRoute-
// tagged endpoints gets no auth/* files. That keeps the generated
// tree from carrying dead imports for apps that gate authentication
// some other way (cookie-only flows that resolve via the middleware
// and never expose a typed login endpoint).
func (authContributor) NexusContribute(ctx extension.GenerateContext) ([]extension.File, error) {
	if ctx.Registry == nil {
		return nil, fmt.Errorf("auth.NexusContribute: GenerateContext.Registry is nil")
	}

	flows := discoverFlows(ctx.Registry)
	if !flows.any() {
		return nil, nil
	}

	framework, _ := ctx.Extras["frontend.framework"].(string)
	switch framework {
	case "vue":
		return []extension.File{
			{Path: "auth/vue.ts", Body: []byte(renderAuthVue(flows))},
		}, nil
	default:
		// React / Svelte / "" — phase-2 ships Vue only. The contributor
		// returns no files for other frameworks rather than emitting
		// a stale stub the consumer would have to delete by hand.
		return nil, nil
	}
}

// authFlows captures which of the three flows (login / logout / me)
// the app has typed endpoints for. The composable's surface adapts:
// no `login` function when nothing is tagged "login"; no `bootstrap`
// when there's no `me` endpoint to read identity from.
type authFlows struct {
	loginName  string
	logoutName string
	meName     string
}

func (f authFlows) any() bool {
	return f.loginName != "" || f.logoutName != "" || f.meName != ""
}

// discoverFlows scans the registry for endpoints tagged with the
// auth-flow marker AuthRoute installs. Multiple endpoints tagged the
// same way (rare but possible — a REST and a GraphQL login on the
// same app) collapse to the first found; the composable can only
// reference one symbol per flow without becoming awkwardly generic.
func discoverFlows(reg *registry.Registry) authFlows {
	out := authFlows{}
	for _, e := range reg.Endpoints() {
		flow := e.Tags[nexus.AuthFlowTag]
		if flow == "" {
			continue
		}
		// Use the flow tag itself as the import symbol — that matches
		// what the renderer's index.ts emits for auth-flow endpoints
		// (see frontend.restOpName's auth-flow special case). Reading
		// e.Name would pick up AsRest's "METHOD PATH" form ("POST
		// /login") and produce an import line that doesn't even parse
		// as TS.
		switch flow {
		case "login":
			if out.loginName == "" {
				out.loginName = flow
			}
		case "logout":
			if out.logoutName == "" {
				out.logoutName = flow
			}
		case "me":
			if out.meName == "" {
				out.meName = flow
			}
		}
	}
	return out
}

// renderAuthVue produces the Vue 3 auth composable. The output uses
// the codegen-emitted `login` / `logout` / `me` functions (imported
// from the parent index) for the actual calls — this file owns only
// the reactive state machine and the token-store glue.
//
// Module-level identity ref is intentional: every component that
// reaches for useAuth() shares the same logged-in user. A per-call
// instance would race when two components try to login concurrently.
func renderAuthVue(f authFlows) string {
	var b strings.Builder
	b.WriteString("// Auto-generated by the nexus auth extension — DO NOT EDIT.\n")
	b.WriteString("// Role: Vue 3 auth composable.\n")
	b.WriteString("// Regenerate with: nexus generate frontend\n\n")
	b.WriteString("import { ref, computed } from 'vue'\n")
	b.WriteString("import { client, NexusError } from '../_client'\n")

	imports := []string{}
	if f.loginName != "" {
		imports = append(imports, f.loginName+" as _login")
	}
	if f.logoutName != "" {
		imports = append(imports, f.logoutName+" as _logout")
	}
	if f.meName != "" {
		imports = append(imports, f.meName+" as _me")
	}
	if len(imports) > 0 {
		fmt.Fprintf(&b, "import { %s } from '../index'\n", strings.Join(imports, ", "))
	}
	b.WriteString("\n")

	// Module-level state: one identity / loading / error per page.
	b.WriteString("type Identity = unknown\n\n")
	b.WriteString("const _identity = ref<Identity | null>(null)\n")
	b.WriteString("const _loading = ref(false)\n")
	b.WriteString("const _error = ref<NexusError | undefined>()\n\n")

	b.WriteString("export function useAuth() {\n")
	b.WriteString("  const identity = _identity\n")
	b.WriteString("  const loading = _loading\n")
	b.WriteString("  const error = _error\n")
	b.WriteString("  const isAuthenticated = computed(() => identity.value !== null)\n\n")

	if f.loginName != "" {
		fmt.Fprintf(&b, "  async function login(creds: Parameters<typeof _login>[0]) {\n")
		b.WriteString("    loading.value = true\n")
		b.WriteString("    error.value = undefined\n")
		b.WriteString("    try {\n")
		b.WriteString("      const out: any = await _login(creds)\n")
		// Stash the token if the response carries one. The check is
		// runtime-shaped because we don't know the response type at
		// codegen time — different apps name it `token`/`accessToken`/etc.
		b.WriteString("      if (out && typeof out === 'object' && typeof (out as any).token === 'string') {\n")
		b.WriteString("        client.tokens.set((out as any).token)\n")
		b.WriteString("      }\n")
		b.WriteString("      if (out && typeof out === 'object' && (out as any).user) {\n")
		b.WriteString("        identity.value = (out as any).user\n")
		b.WriteString("      }\n")
		b.WriteString("      return out\n")
		b.WriteString("    } catch (e) {\n")
		b.WriteString("      error.value = e as NexusError\n")
		b.WriteString("      throw e\n")
		b.WriteString("    } finally {\n")
		b.WriteString("      loading.value = false\n")
		b.WriteString("    }\n")
		b.WriteString("  }\n\n")
	}

	if f.logoutName != "" {
		b.WriteString("  async function logout() {\n")
		b.WriteString("    loading.value = true\n")
		b.WriteString("    try {\n")
		b.WriteString("      await _logout()\n")
		b.WriteString("    } catch (e) {\n")
		b.WriteString("      error.value = e as NexusError\n")
		b.WriteString("    } finally {\n")
		b.WriteString("      client.tokens.clear()\n")
		b.WriteString("      identity.value = null\n")
		b.WriteString("      loading.value = false\n")
		b.WriteString("    }\n")
		b.WriteString("  }\n\n")
	}

	if f.meName != "" {
		b.WriteString("  async function bootstrap() {\n")
		// bootstrap is the "page loaded with a stashed token; rehydrate
		// identity" path. Without a stored token there's nothing to do.
		b.WriteString("    if (!client.tokens.get()) return\n")
		b.WriteString("    loading.value = true\n")
		b.WriteString("    try {\n")
		b.WriteString("      identity.value = await _me() as Identity\n")
		b.WriteString("    } catch {\n")
		b.WriteString("      client.tokens.clear()\n")
		b.WriteString("      identity.value = null\n")
		b.WriteString("    } finally {\n")
		b.WriteString("      loading.value = false\n")
		b.WriteString("    }\n")
		b.WriteString("  }\n\n")
	}

	b.WriteString("  return {\n")
	b.WriteString("    identity, isAuthenticated, loading, error,\n")
	if f.loginName != "" {
		b.WriteString("    login,\n")
	}
	if f.logoutName != "" {
		b.WriteString("    logout,\n")
	}
	if f.meName != "" {
		b.WriteString("    bootstrap,\n")
	}
	b.WriteString("  }\n")
	b.WriteString("}\n")

	return b.String()
}
