package auth

import (
	"context"
	"fmt"
	"reflect"

	"github.com/paulmanoni/nexus"
	"github.com/paulmanoni/nexus/di"
)

// BackendOption declares the cohesive auth backend for a Config — one type
// that supplies request resolution and, optionally, login and
// authorization, so those three concerns live together instead of being
// scattered across a Scheme resolver, a login handler, and a separate
// Authorization block. Build it with UseBackend (DI-constructed) or
// StaticBackend (a ready value). The zero value means "no backend" and
// leaves every existing Config field in charge — fully backward compatible.
//
// A backend is any value; the framework discovers what it can do by type
// assertion against three capability interfaces:
//
//   - Resolve(ctx, token) (*Identity, error)     — fills any Scheme whose
//     Resolve is nil (the per-request "who are you?").
//   - Login(ctx, Credentials) (*Identity, error) — powers Manager.Login.
//   - Authorize(id, required) bool               — replaces
//     Config.Authorization's permission check when present.
//
// A backend implements whichever subset it needs; Resolve is the only one
// required for it to drive request authentication.
type BackendOption struct {
	set   bool
	value any // StaticBackend: a ready value
	ctor  any // UseBackend: a DI constructor func(deps...) Backend
}

// UseBackend declares a DI-constructed backend. constructor is a function
// run in the container — func(deps...) T (optionally (T, error)) — so the
// backend can close over app services (a *DB, a token server) without
// package globals or a backfill Invoke:
//
//	Backend: auth.UseBackend(func(srv *Server, db *DB) auth.Backend {
//	    return NewAuthBackend(srv, db)
//	}),
func UseBackend(constructor any) BackendOption {
	return BackendOption{set: true, ctor: constructor}
}

// StaticBackend declares a ready backend value that needs no DI
// dependencies (e.g. one built entirely from a Config literal).
func StaticBackend(b any) BackendOption {
	return BackendOption{set: true, value: b}
}

// --- capability interfaces (discovered by assertion) ---

type resolveCapable interface {
	Resolve(ctx context.Context, token string) (*Identity, error)
}
type loginCapable interface {
	Login(ctx context.Context, cred Credentials) (*Identity, error)
}
type authorizeCapable interface {
	Authorize(id *Identity, required []string) bool
}

// finalizeBackend attaches a resolved backend to the module state: it fills
// every scheme that omitted a Resolver with the backend's Resolve, and —
// when the backend authorizes — replaces the permission check. It runs
// inline for StaticBackend and inside a DI invoke for UseBackend, always
// before the first request.
func finalizeBackend(state *moduleState, backend any) error {
	if backend == nil {
		return fmt.Errorf("Backend resolved to nil")
	}
	state.backend = backend

	if br, ok := backend.(resolveCapable); ok {
		for i := range state.schemes {
			if state.schemes[i].resolve == nil {
				state.schemes[i].resolve = br.Resolve
			}
		}
	}
	for i := range state.schemes {
		if state.schemes[i].resolve == nil {
			return fmt.Errorf("scheme %q has no Resolve and the Backend does not implement Resolve(ctx, token)", state.schemes[i].name)
		}
	}

	// Authorization on the backend takes precedence over Config.Authorization
	// — the "authorization lives with the backend" design. The deny-by-default
	// gate (Config.Authorization.Default) is independent and already wired.
	if ba, ok := backend.(authorizeCapable); ok {
		state.permissions = ba.Authorize
	}
	return nil
}

var errorType = reflect.TypeFor[error]()

// backendFinalizeOption returns the options that build a UseBackend
// constructor in DI and finalize the module state once it's resolved. The
// finalize invoke is generated by reflection so it demands the
// constructor's exact return type — DI then injects the built backend.
func backendFinalizeOption(state *moduleState, ctor any) (nexus.Option, error) {
	ct := reflect.TypeOf(ctor)
	if ct == nil || ct.Kind() != reflect.Func || ct.NumOut() == 0 {
		return nil, fmt.Errorf("UseBackend: constructor must be a function returning a backend")
	}
	backendType := ct.Out(0)

	invokeType := reflect.FuncOf([]reflect.Type{backendType}, []reflect.Type{errorType}, false)
	invokeFn := reflect.MakeFunc(invokeType, func(args []reflect.Value) []reflect.Value {
		err := finalizeBackend(state, args[0].Interface())
		ev := reflect.New(errorType).Elem()
		if err != nil {
			ev.Set(reflect.ValueOf(err))
		}
		return []reflect.Value{ev}
	})

	return nexus.Options(nexus.Provide(ctor), nexus.Invoke(invokeFn.Interface())), nil
}

// raiseBackendError wraps a backend-wiring failure as a boot-time option
// error, matching how Module surfaces scheme-binding failures.
func raiseBackendError(err error) nexus.Option {
	return nexus.Raw(di.Error(fmt.Errorf("auth: %w", err)))
}
