// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"github.com/a-h/templ"
	templ_nx_view "github.com/paulmanoni/nexus/v2/view"
)
import templruntime "github.com/a-h/templ/runtime"

// iconPaths are the kit's own icons: 24×24, stroked, drawn with
// currentColor.
var iconPaths = map[string]string{
	"x":                `<path d="M18 6 6 18M6 6l12 12"/>`,
	"chevron-down":     `<path d="m6 9 6 6 6-6"/>`,
	"chevron-up":       `<path d="m18 15-6-6-6 6"/>`,
	"chevron-left":     `<path d="m15 18-6-6 6-6"/>`,
	"chevron-right":    `<path d="m9 18 6-6-6-6"/>`,
	"chevrons-up-down": `<path d="m7 15 5 5 5-5M7 9l5-5 5 5"/>`,
	"more-vertical":    `<circle cx="12" cy="5" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="12" cy="19" r="1"/>`,
	"more-horizontal":  `<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>`,
	"search":           `<circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/>`,
	"check":            `<path d="M20 6 9 17l-5-5"/>`,
	"plus":             `<path d="M12 5v14M5 12h14"/>`,
	"copy":             `<rect x="9" y="9" width="12" height="12" rx="2"/><path d="M5 15V5a2 2 0 0 1 2-2h10"/>`,
	"link":             `<path d="M10 13a5 5 0 0 0 7.5.5l3-3a5 5 0 0 0-7-7l-1.7 1.7"/><path d="M14 11a5 5 0 0 0-7.5-.5l-3 3a5 5 0 0 0 7 7l1.7-1.7"/>`,
	"trash":            `<path d="M3 6h18M8 6V4h8v2M6 6l1 14h10l1-14"/>`,
	"pencil":           `<path d="M4 20h4L19 9l-4-4L4 16z"/>`,
	"info":             `<circle cx="12" cy="12" r="9"/><path d="M12 16v-4M12 8h.01"/>`,
	"alert":            `<circle cx="12" cy="12" r="9"/><path d="M12 8v4M12 16h.01"/>`,
	"inbox":            `<path d="M22 12h-6l-2 3h-4l-2-3H2"/><path d="M5.5 5h13L22 12v6a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2v-6z"/>`,
	"spinner":          `<path d="M21 12a9 9 0 1 1-6.2-8.56"/>`,
}

// Icon draws one of the kit's icons by name — x, check, plus, search,
// copy, link, trash, pencil, info, alert, inbox, spinner, more-vertical,
// more-horizontal, chevron-up/down/left/right, chevrons-up-down — sized by
// its class (size-4 when empty). An unknown name draws nothing.
func Icon(name string, class ...string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Rec := templ_nx_view.Record(ctx, templ_7745c5c3_Buffer)
		_ = templ_7745c5c3_Rec
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Rec.Open(templ_7745c5c3_Buffer)
		if d, ok := iconPaths[name]; ok {
			var templ_7745c5c3_Var2 = []any{iconClass(name, class)}
			templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ_7745c5c3_Rec.S(templ_7745c5c3_Buffer, 1, "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\" class=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue(templ.CSSClasses(templ_7745c5c3_Var2).String())
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `icon.templ`, Line: 1, Col: 0}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ_7745c5c3_Rec.S(templ_7745c5c3_Buffer, 2, "\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Rec.Open(templ_7745c5c3_Buffer)
			templ_7745c5c3_Err = templ.Raw(d).Render(ctx, templ_7745c5c3_Buffer)
			templ_7745c5c3_Rec.Close(templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ_7745c5c3_Rec.S(templ_7745c5c3_Buffer, 3, "</svg>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Rec.Close(templ_7745c5c3_Buffer)
		return nil
	})
}

func iconClass(name string, class []string) string {
	c := join(class...)
	if c == "" {
		c = "size-4"
	}
	if name == "spinner" {
		c = join("animate-spin", c)
	}
	return join("shrink-0", c)
}

var _ = templruntime.GeneratedTemplate
