// Package notes is the canonical AsCRUD demo: an entire module
// surface — five REST endpoints + five GraphQL ops, with paging,
// validation, and a per-request store — boils down to a single
// `nexus.AsCRUD[Note](...)` line.
//
// The resolver takes fx-injected deps after ctx, so the user's DB
// (or DBM, cache, queue, …) drops in just by appearing in the
// signature. Any dep that implements NexusResources() — the
// framework's resource provider interface — is automatically linked
// to the generated endpoints on the dashboard's architecture canvas:
// no manual edge declarations.
package notes

import (
	"context"

	"github.com/paulmanoni/nexus"
	"github.com/paulmanoni/nexus/resource"
)

// Note is the resource type. AsCRUD reflects on it to:
//
//   - Generate URL paths from the lowercased pluralized type name
//     ("Note" → "/notes").
//   - Locate the "ID" field as the primary key for the in-memory
//     store. Any exported `string`-typed field literally named ID
//     works; rename or pass explicit accessors otherwise.
//   - Build the GraphQL input/output types from the struct fields.
//
// Validation tags (validate:"...") flow through the same path as
// every other nexus handler — invalid Create/Update bodies surface
// as 400s on REST and as resolver errors on GraphQL.
type Note struct {
	ID    string `json:"id"`
	Title string `json:"title" validate:"required,len=1|120"`
	Body  string `json:"body"`
}

// DB stands in for the user's real DB wrapper (DBM, *gorm.DB,
// whatever). It implements NexusResourceProvider so the framework
// registers a Resource node for it on the dashboard, and AsCRUD's
// auto-attach pass links every generated endpoint to that resource.
type DB struct {
	store *nexus.MemoryStore[Note]
}

// NewNotesDB builds the DB wrapper around an in-memory store. In a
// real app this would dial Postgres or open a GORM session.
func NewNotesDB() *DB {
	return &DB{
		store: nexus.NewMemoryStore[Note](
			func(n *Note) string { return n.ID },
			func(n *Note, id string) { n.ID = id },
			nil,
		),
	}
}

// NexusResources is what tells the framework "this dep is a resource
// the dashboard should know about." AsCRUD's resolver walker picks
// this up and links the resource to every generated endpoint —
// canvas edges and per-row chips both light up automatically.
func (d *DB) NexusResources() []resource.Resource {
	return []resource.Resource{
		resource.NewDatabase("notes-store", "In-memory note store", nil, func() bool { return true }, resource.AsDefault()),
	}
}

// Module wires the entire CRUD surface in a single declaration.
// Compare with users/module.go: that module hand-writes Get/List/
// Create/Search across REST and GraphQL; this one declares the
// shape and lets the framework generate everything.
//
// REST endpoints generated by default:
//
//	GET    /notes              → list (with ?limit / ?offset / ?sort)
//	GET    /notes/:id          → read
//	POST   /notes              → create
//	PATCH  /notes/:id          → update (shallow merge)
//	DELETE /notes/:id          → delete
//
// GraphQL is opt-in — pass nexus.WithGraphQL() to expose:
//
//	query    listNotes(limit, offset, sort)
//	query    getNote(id)
//	mutation createNote(...)
//	mutation updateNote(id, ...)
//	mutation deleteNote(id) → Boolean
//
// To go GraphQL-only, pair WithGraphQL() with nexus.WithoutREST().
var Module = nexus.Module("notes",
	nexus.Provide(NewService, NewNotesDB),
	nexus.AsCRUD[Note](
		// Resolver takes fx deps after ctx — *DB is fx-resolved
		// from the Provide above. Because DB implements
		// NexusResources(), the dashboard auto-draws an edge from
		// the notes-store resource node to each generated endpoint.
		func(ctx context.Context, db *DB) (nexus.Store[Note], error) {
			return db.store, nil
		},
		nexus.WithGraphQL(),
		nexus.WithoutREST(),
	),
)
